export const culturaCorporal = {
  id: "educacao-fisica_cultura_corporal",
  materia: "Educacao Fisica",
  serie: [1],
  topico: "Cultura Corporal",
  metadados: {
    disciplinaId: "educacao-fisica",
    base: "ESCOLAR",
    eixo: "Educacao Fisica",
    frente: "Cultura Corporal",
    searchAliases: [
      "cultura corporal",
      "corpo e movimento",
      "saude",
      "expressao corporal",
      "jogos e brincadeiras",
      "qualidade de vida",
      "atividade fisica",
      "bem-estar"
    ],
    subtopicosBase: [
      "Conceito de cultura corporal",
      "Corpo e movimento",
      "Saude e qualidade de vida",
      "Expressao corporal",
      "Jogos e brincadeiras",
      "Habilidades motoras",
      "Relacao corpo-mente",
      "Inclusao e diversidade"
    ],
    habilidadesBase: [
      "identificar conceitos fundamentais da cultura corporal",
      "relacionar corpo e movimento com saude e bem-estar",
      "reconhecer importancia da expressao corporal",
      "compreender papel de jogos e brincadeiras no desenvolvimento",
      "aplicar principios de inclusao na pratica fisica",
      "interpretar situacoes aplicadas em cultura corporal"
    ],
    auditado: false
  },
  questoes: [
    {
      id: "cc_001",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que se entende por cultura corporal?",
      opcoes: [
        "Apenas a pratica de esportes profissionais",
        "O conjunto de conhecimentos e praticas relacionadas ao corpo e ao movimento",
        "Exclusivamente a educacao fisica escolar",
        "A alimentacao e os habitos de higiene"
      ],
      correta: "O conjunto de conhecimentos e praticas relacionadas ao corpo e ao movimento",
      comentario: "Cultura corporal engloba todas as manifestacoes culturais relacionadas ao corpo humano, incluindo esportes, danças, jogos e expressoes corporais.",
      tempoEstimado: 20,
      tags: ["cultura-corporal", "conceito"],
      habilidades: ["identificar-conceito-de-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_002",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual e a importancia do movimento para o corpo humano?",
      opcoes: [
        "Apenas para fins esteticos",
        "Para manter a saude fisica e mental",
        "Exclusivamente para competicoes esportivas",
        "Nao tem importancia significativa"
      ],
      correta: "Para manter a saude fisica e mental",
      comentario: "O movimento e essencial para o desenvolvimento harmonico do corpo, prevencao de doencas e bem-estar psicologico.",
      tempoEstimado: 25,
      tags: ["movimento", "saude"],
      habilidades: ["relacionar-movimento-a-saude"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_003",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos seguintes fatores contribui diretamente para uma boa qualidade de vida?",
      opcoes: [
        "Pratica regular de atividade fisica",
        "Consumo excessivo de alimentos industrializados",
        "Sedentarismo prolongado",
        "Falta de higiene pessoal"
      ],
      correta: "Pratica regular de atividade fisica",
      comentario: "A atividade fisica regular melhora a saude cardiovascular, fortalece os musculos e contribui para o bem-estar geral.",
      tempoEstimado: 30,
      tags: ["saude", "qualidade-vida", "atividade-fisica"],
      habilidades: ["identificar-fatores-de-qualidade-vida"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_004",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "A expressao corporal pode ser manifestada atraves de:",
      opcoes: [
        "Apenas da fala e gestos",
        "Danca, teatro e artes marciais",
        "Exclusivamente de esportes coletivos",
        "Nao inclui movimentos artisticos"
      ],
      correta: "Danca, teatro e artes marciais",
      comentario: "A expressao corporal utiliza o corpo como meio de comunicacao e criacao artistica, incluindo diversas formas de arte.",
      tempoEstimado: 25,
      tags: ["expressao-corporal", "danca", "teatro"],
      habilidades: ["reconhecer-formas-de-expressao-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_006",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade motora envolve coordenacao olho-mao?",
      opcoes: [
        "Equilibrio",
        "Agilidade",
        "Precisao",
        "Forca"
      ],
      correta: "Precisao",
      comentario: "Precisao refere-se a capacidade de controlar movimentos finos, como lancar uma bola com acuracia.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "coordenacao"],
      habilidades: ["identificar-habilidades-motoras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_007",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como a atividade fisica influencia a saude mental?",
      opcoes: [
        "Aumenta estresse",
        "Reduz ansiedade e depressao",
        "Diminui concentracao",
        "Nao tem efeito"
      ],
      correta: "Reduz ansiedade e depressao",
      comentario: "Exercicios liberam endorfinas, melhorando humor e reduzindo sintomas de ansiedade.",
      tempoEstimado: 35,
      tags: ["corpo-mente", "saude-mental"],
      habilidades: ["relacionar-atividade-fisica-a-mente"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_008",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual estrategia promove inclusao em atividades fisicas?",
      opcoes: [
        "Competicao intensa",
        "Adaptacao de regras para todos",
        "Exclusao de participantes fracos",
        "Foco apenas em vencedores"
      ],
      correta: "Adaptacao de regras para todos",
      comentario: "Adaptar regras garante participacao de todos, independente de habilidades ou limitacoes.",
      tempoEstimado: 40,
      tags: ["inclusao", "diversidade"],
      habilidades: ["aplicar-principios-inclusivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_009",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "A cultura corporal inclui quais elementos?",
      opcoes: [
        "Apenas esportes olimpicos",
        "Esportes, danças, jogos e expressoes",
        "Exclusivamente alimentacao",
        "Somente higiene"
      ],
      correta: "Esportes, danças, jogos e expressoes",
      comentario: "Cultura corporal abrange todas as manifestacoes culturais relacionadas ao corpo.",
      tempoEstimado: 20,
      tags: ["cultura-corporal", "elementos"],
      habilidades: ["identificar-elementos-da-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_010",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento corporal e fundamental para o desenvolvimento?",
      opcoes: [
        "Sedentarismo",
        "Locomocao",
        "Imobilidade",
        "Paralisia"
      ],
      correta: "Locomocao",
      comentario: "Locomocao permite deslocamento, essencial para exploracao e independencia.",
      tempoEstimado: 30,
      tags: ["movimento", "desenvolvimento"],
      habilidades: ["compreender-importancia-da-locomocao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_011",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habito contribui para qualidade de vida?",
      opcoes: [
        "Dieta balanceada com atividade fisica",
        "Fumar e beber",
        "Dormir pouco",
        "Estresse constante"
      ],
      correta: "Dieta balanceada com atividade fisica",
      comentario: "Combinacao de nutricao adequada e exercicio previne doencas e melhora bem-estar.",
      tempoEstimado: 35,
      tags: ["saude", "habitos"],
      habilidades: ["interpretar-habitos-saudaveis"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_012",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica de expressao corporal usa gestos?",
      opcoes: [
        "Mímica",
        "Corrida",
        "Salto",
        "Nado"
      ],
      correta: "Mímica",
      comentario: "Mímica utiliza gestos e expressoes faciais para comunicar sem palavras.",
      tempoEstimado: 40,
      tags: ["expressao-corporal", "mimica"],
      habilidades: ["analisar-tecnicas-de-expressao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_013",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual jogo desenvolve cooperacao?",
      opcoes: [
        "Corrida individual",
        "Queimada",
        "Competicao solitaria",
        "Brincadeira sozinha"
      ],
      correta: "Queimada",
      comentario: "Queimada envolve equipes trabalhando juntas para eliminar oponentes.",
      tempoEstimado: 25,
      tags: ["jogos", "cooperacao"],
      habilidades: ["identificar-jogos-cooperativos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_014",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade motora e importante para esportes?",
      opcoes: [
        "Agilidade",
        "Leitura",
        "Matematica",
        "Musica"
      ],
      correta: "Agilidade",
      comentario: "Agilidade permite mudancas rapidas de direcao e velocidade em atividades fisicas.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "agilidade"],
      habilidades: ["compreender-habilidades-esportivas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_015",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Como o estresse afeta o corpo?",
      opcoes: [
        "Melhora performance",
        "Aumenta tensao muscular",
        "Reduz fadiga",
        "Nao afeta"
      ],
      correta: "Aumenta tensao muscular",
      comentario: "Estresse causa contracao muscular, levando a dores e fadiga.",
      tempoEstimado: 35,
      tags: ["corpo-mente", "estresse"],
      habilidades: ["interpretar-efeitos-do-estresse"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_016",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual desafio da inclusao em educacao fisica?",
      opcoes: [
        "Diversidade de habilidades",
        "Homogeneidade",
        "Falta de interesse",
        "Excesso de equipamentos"
      ],
      correta: "Diversidade de habilidades",
      comentario: "Diferencas em capacidades fisicas exigem adaptacoes para inclusao.",
      tempoEstimado: 40,
      tags: ["inclusao", "desafios"],
      habilidades: ["analisar-desafios-inclusivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_017",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Cultura corporal e transmitida por?",
      opcoes: [
        "Familia e sociedade",
        "Apenas escola",
        "Exclusivamente midia",
        "Nao e transmitida"
      ],
      correta: "Familia e sociedade",
      comentario: "Familia e sociedade ensinam valores e praticas corporais desde cedo.",
      tempoEstimado: 20,
      tags: ["cultura-corporal", "transmissao"],
      habilidades: ["identificar-transmissao-cultural"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_018",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio do movimento diario?",
      opcoes: [
        "Aumento de peso",
        "Melhoria da circulacao",
        "Diminuicao de energia",
        "Reducao de forca"
      ],
      correta: "Melhoria da circulacao",
      comentario: "Movimento estimula circulacao sanguinea, oxigenando tecidos.",
      tempoEstimado: 30,
      tags: ["movimento", "circulacao"],
      habilidades: ["compreender-beneficios-circulatorios"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_019",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual indicador de qualidade de vida?",
      opcoes: [
        "Sedentarismo",
        "Bem-estar subjetivo",
        "Doencas frequentes",
        "Estresse alto"
      ],
      correta: "Bem-estar subjetivo",
      comentario: "Bem-estar inclui satisfacao pessoal, saude fisica e mental.",
      tempoEstimado: 35,
      tags: ["qualidade-vida", "bem-estar"],
      habilidades: ["interpretar-indicadores-de-qualidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_021",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual brincadeira desenvolve criatividade?",
      opcoes: [
        "Pula-corda repetitiva",
        "Jogo de faz-de-conta",
        "Corrida cronometrada",
        "Exercicio de forca"
      ],
      correta: "Jogo de faz-de-conta",
      comentario: "Faz-de-conta estimula imaginacao e criatividade atraves de narrativas corporais.",
      tempoEstimado: 30,
      tags: ["brincadeiras", "criatividade"],
      habilidades: ["compreender-brincadeiras-criativas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_022",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade motora e treinada em corridas?",
      opcoes: [
        "Forca",
        "Resistencia",
        "Flexibilidade",
        "Equilibrio"
      ],
      correta: "Resistencia",
      comentario: "Corridas longas desenvolvem resistencia cardiovascular e muscular.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "resistencia"],
      habilidades: ["interpretar-treinamento-de-resistencia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_023",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como a meditacao afeta o corpo?",
      opcoes: [
        "Aumenta frequencia cardiaca",
        "Reduz estresse e melhora foco",
        "Diminui forca muscular",
        "Nao tem efeito fisico"
      ],
      correta: "Reduz estresse e melhora foco",
      comentario: "Meditacao regula respostas de estresse, melhorando concentracao e relaxamento.",
      tempoEstimado: 40,
      tags: ["corpo-mente", "meditacao"],
      habilidades: ["analisar-efeitos-da-meditacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_024",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Inclusao em cultura corporal significa?",
      opcoes: [
        "Excluir participantes",
        "Incluir todos independente de habilidades",
        "Focar em elite",
        "Competir apenas"
      ],
      correta: "Incluir todos independente de habilidades",
      comentario: "Inclusao garante acesso a atividades fisicas para pessoas de todas as capacidades.",
      tempoEstimado: 25,
      tags: ["inclusao", "diversidade"],
      habilidades: ["identificar-principios-inclusivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_025",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Cultura corporal e influenciada por?",
      opcoes: [
        "Apenas biologia",
        "Sociedade e cultura",
        "Exclusivamente genetica",
        "Nao e influenciada"
      ],
      correta: "Sociedade e cultura",
      comentario: "Valores sociais moldam praticas corporais, como danças tradicionais.",
      tempoEstimado: 30,
      tags: ["cultura-corporal", "influencias"],
      habilidades: ["compreender-influencias-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_026",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento corporal previne doencas?",
      opcoes: [
        "Imobilidade",
        "Atividade fisica regular",
        "Sedentarismo",
        "Repouso excessivo"
      ],
      correta: "Atividade fisica regular",
      comentario: "Exercicio regular reduz risco de doencas cardiovasculares e metabolicas.",
      tempoEstimado: 35,
      tags: ["movimento", "prevencao"],
      habilidades: ["interpretar-movimento-prevencao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_027",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual componente da qualidade de vida?",
      opcoes: [
        "Renda alta",
        "Saude fisica e mental",
        "Carro novo",
        "Casa grande"
      ],
      correta: "Saude fisica e mental",
      comentario: "Saude e base para bem-estar, incluindo atividade fisica e equilibrio emocional.",
      tempoEstimado: 40,
      tags: ["qualidade-vida", "componentes"],
      habilidades: ["analisar-componentes-qualidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_028",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Expressao corporal inclui?",
      opcoes: [
        "Falar",
        "Gestos e posturas",
        "Escrever",
        "Ler"
      ],
      correta: "Gestos e posturas",
      comentario: "Expressao corporal usa corpo para comunicar emocao e ideia sem palavras.",
      tempoEstimado: 20,
      tags: ["expressao-corporal", "gestos"],
      habilidades: ["identificar-formas-expressao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_029",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual jogo ensina regras?",
      opcoes: [
        "Brincadeira livre",
        "Jogo estruturado",
        "Danca improvisada",
        "Exercicio solo"
      ],
      correta: "Jogo estruturado",
      comentario: "Jogos com regras ensinam respeito, estrategia e cooperacao.",
      tempoEstimado: 30,
      tags: ["jogos", "regras"],
      habilidades: ["compreender-aprendizado-regras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_031",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Como o corpo e a mente se relacionam?",
      opcoes: [
        "Nao se relacionam",
        "Movimento corporal afeta humor",
        "Apenas fisicamente",
        "Mentalmente isolado"
      ],
      correta: "Movimento corporal afeta humor",
      comentario: "Atividade fisica libera endorfinas, melhorando estado emocional.",
      tempoEstimado: 25,
      tags: ["corpo-mente", "humor"],
      habilidades: ["identificar-relacao-corpo-mente"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_032",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio da diversidade em atividades fisicas?",
      opcoes: [
        "Homogeneidade",
        "Aprendizado mutuo",
        "Exclusao",
        "Competicao desigual"
      ],
      correta: "Aprendizado mutuo",
      comentario: "Diversidade permite troca de experiencias e habilidades diferentes.",
      tempoEstimado: 30,
      tags: ["inclusao", "aprendizado"],
      habilidades: ["compreender-beneficios-diversidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_033",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo de cultura corporal?",
      opcoes: [
        "Ler livro",
        "Praticar yoga",
        "Assistir TV",
        "Comer"
      ],
      correta: "Praticar yoga",
      comentario: "Yoga combina movimento, respiracao e concentracao mental.",
      tempoEstimado: 35,
      tags: ["cultura-corporal", "yoga"],
      habilidades: ["interpretar-exemplos-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_034",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto do movimento no desenvolvimento cognitivo?",
      opcoes: [
        "Diminui concentracao",
        "Melhora oxigenacao cerebral",
        "Aumenta sedentarismo",
        "Reduz atividade mental"
      ],
      correta: "Melhora oxigenacao cerebral",
      comentario: "Movimento aumenta fluxo sanguineo, beneficiando funcoes cerebrais.",
      tempoEstimado: 40,
      tags: ["movimento", "cognitivo"],
      habilidades: ["analisar-impactos-cognitivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_035",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habito para qualidade de vida?",
      opcoes: [
        "Atividade fisica diaria",
        "Dormir pouco",
        "Comer junk food",
        "Ficar parado"
      ],
      correta: "Atividade fisica diaria",
      comentario: "Exercicio regular e pilar da saude e bem-estar.",
      tempoEstimado: 20,
      tags: ["qualidade-vida", "habitos"],
      habilidades: ["identificar-habitos-saudaveis"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_036",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual forma de expressao corporal?",
      opcoes: [
        "Pintar quadro",
        "Teatro fisico",
        "Escrever poema",
        "Tocar instrumento"
      ],
      correta: "Teatro fisico",
      comentario: "Teatro fisico usa corpo para narrar historias sem palavras.",
      tempoEstimado: 30,
      tags: ["expressao-corporal", "teatro"],
      habilidades: ["compreender-formas-expressao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_037",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual brincadeira desenvolve imaginacao?",
      opcoes: [
        "Corrida cronometrada",
        "Jogo de roles",
        "Exercicio repetitivo",
        "Alongamento passivo"
      ],
      correta: "Jogo de roles",
      comentario: "Jogo de roles estimula criacao de cenarios e personagens.",
      tempoEstimado: 35,
      tags: ["brincadeiras", "imaginacao"],
      habilidades: ["interpretar-brincadeiras-imaginativas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_038",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade motora para danca?",
      opcoes: [
        "Ritmo",
        "Forca bruta",
        "Velocidade maxima",
        "Resistencia longa"
      ],
      correta: "Ritmo",
      comentario: "Ritmo coordena movimentos com musica, essencial na danca.",
      tempoEstimado: 40,
      tags: ["habilidades-motoras", "ritmo"],
      habilidades: ["analisar-habilidades-danca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_039",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como o estresse afeta o corpo?",
      opcoes: [
        "Relaxa musculos",
        "Aumenta tensao",
        "Melhora sono",
        "Reduz ansiedade"
      ],
      correta: "Aumenta tensao",
      comentario: "Estresse causa contracao muscular, levando a dores.",
      tempoEstimado: 30,
      tags: ["corpo-mente", "estresse"],
      habilidades: ["compreender-efeitos-estresse"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_040",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual estrategia para inclusao?",
      opcoes: [
        "Modificar regras",
        "Excluir participantes",
        "Focar em vencedores",
        "Ignorar diferencas"
      ],
      correta: "Modificar regras",
      comentario: "Adaptar regras permite participacao de todos os niveis.",
      tempoEstimado: 35,
      tags: ["inclusao", "estrategias"],
      habilidades: ["interpretar-estrategias-inclusivas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_041",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual dimensao da cultura corporal?",
      opcoes: [
        "Somente fisica",
        "Fisica, social e cultural",
        "Apenas mental",
        "Exclusivamente esportiva"
      ],
      correta: "Fisica, social e cultural",
      comentario: "Cultura corporal integra corpo, sociedade e valores culturais.",
      tempoEstimado: 40,
      tags: ["cultura-corporal", "dimensoes"],
      habilidades: ["analisar-dimensoes-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_042",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento basico?",
      opcoes: [
        "Caminhar",
        "Voar",
        "Teletransportar",
        "Flutuar no ar"
      ],
      correta: "Caminhar",
      comentario: "Caminhar e movimento fundamental para locomocao.",
      tempoEstimado: 20,
      tags: ["movimento", "basico"],
      habilidades: ["identificar-movimentos-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_043",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio da atividade fisica?",
      opcoes: [
        "Aumento de peso",
        "Fortalecimento ósseo",
        "Diminuicao de energia",
        "Reducao de forca"
      ],
      correta: "Fortalecimento ósseo",
      comentario: "Exercicio estimula densidade ossea, previne osteoporose.",
      tempoEstimado: 30,
      tags: ["saude", "ossos"],
      habilidades: ["compreender-beneficios-osseos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_044",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica de expressao?",
      opcoes: [
        "Mímica",
        "Correr",
        "Saltar",
        "Nadar"
      ],
      correta: "Mímica",
      comentario: "Mímica comunica ideias atraves de gestos silenciosos.",
      tempoEstimado: 35,
      tags: ["expressao-corporal", "mimica"],
      habilidades: ["interpretar-tecnicas-mimica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_045",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual valor ensinado em jogos?",
      opcoes: [
        "Egoismo",
        "Cooperacao",
        "Competicao desleal",
        "Isolamento"
      ],
      correta: "Cooperacao",
      comentario: "Jogos promovem trabalho em equipe e ajuda mutua.",
      tempoEstimado: 40,
      tags: ["jogos", "cooperacao"],
      habilidades: ["analisar-valores-jogos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_046",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para equilibrio?",
      opcoes: [
        "Equilibrio estatico",
        "Corrida rapida",
        "Lancamento forte",
        "Salto alto"
      ],
      correta: "Equilibrio estatico",
      comentario: "Equilibrio estatico mantem posicao sem movimento.",
      tempoEstimado: 25,
      tags: ["habilidades-motoras", "equilibrio"],
      habilidades: ["identificar-equilibrio-estatico"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_047",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como a respiracao afeta a mente?",
      opcoes: [
        "Aumenta confusao",
        "Reduz ansiedade",
        "Diminui foco",
        "Aumenta estresse"
      ],
      correta: "Reduz ansiedade",
      comentario: "Respiracao profunda acalma sistema nervoso, reduzindo ansiedade.",
      tempoEstimado: 30,
      tags: ["corpo-mente", "respiracao"],
      habilidades: ["compreender-efeitos-respiracao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_048",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual desafio da diversidade?",
      opcoes: [
        "Aprendizado",
        "Preconceito",
        "Igualdade",
        "Respeito"
      ],
      correta: "Preconceito",
      comentario: "Preconceito impede inclusao baseada em esteriotipos.",
      tempoEstimado: 35,
      tags: ["inclusao", "preconceito"],
      habilidades: ["interpretar-desafios-preconceito"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_049",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Cultura corporal inclui?",
      opcoes: [
        "Apenas esportes",
        "Esportes e danças",
        "Somente alimentacao",
        "Exclusivamente higiene"
      ],
      correta: "Esportes e danças",
      comentario: "Inclui todas as expressoes culturais relacionadas ao corpo.",
      tempoEstimado: 30,
      tags: ["cultura-corporal", "esportes-dancas"],
      habilidades: ["compreender-inclusao-esportes-dancas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_051",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como a atividade fisica afeta a concentracao?",
      opcoes: [
        "Diminui foco",
        "Melhora concentracao",
        "Aumenta confusao",
        "Nao afeta"
      ],
      correta: "Melhora concentracao",
      comentario: "Exercicio libera neurotransmissores que melhoram foco mental.",
      tempoEstimado: 30,
      tags: ["corpo-mente", "concentracao"],
      habilidades: ["compreender-efeitos-concentracao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_052",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual importancia da diversidade corporal?",
      opcoes: [
        "Homogeneidade",
        "Aceitacao de diferencas",
        "Exclusao",
        "Competicao desigual"
      ],
      correta: "Aceitacao de diferencas",
      comentario: "Diversidade corporal ensina respeito e adaptacao.",
      tempoEstimado: 35,
      tags: ["inclusao", "aceitacao"],
      habilidades: ["interpretar-importancia-diversidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_053",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual aspecto social da cultura corporal?",
      opcoes: [
        "Individualismo",
        "Interacao social",
        "Isolamento",
        "Competicao solitaria"
      ],
      correta: "Interacao social",
      comentario: "Cultura corporal promove relacoes e comunidade.",
      tempoEstimado: 40,
      tags: ["cultura-corporal", "social"],
      habilidades: ["analisar-aspectos-sociais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_054",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento essencial para vida?",
      opcoes: [
        "Danca",
        "Respiracao",
        "Corrida",
        "Salto"
      ],
      correta: "Respiracao",
      comentario: "Respiracao e movimento vital para oxigenacao.",
      tempoEstimado: 20,
      tags: ["movimento", "respiracao"],
      habilidades: ["identificar-movimentos-essenciais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_055",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio para o sistema imunologico?",
      opcoes: [
        "Fraqueza",
        "Fortalecimento",
        "Doencas",
        "Sedentarismo"
      ],
      correta: "Fortalecimento",
      comentario: "Atividade fisica estimula defesa do organismo.",
      tempoEstimado: 30,
      tags: ["saude", "imunologico"],
      habilidades: ["compreender-beneficios-imunologicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_056",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual forma de expressao nao-verbal?",
      opcoes: [
        "Falar",
        "Postura",
        "Escrever",
        "Cantar"
      ],
      correta: "Postura",
      comentario: "Postura corporal comunica emocao sem palavras.",
      tempoEstimado: 35,
      tags: ["expressao-corporal", "postura"],
      habilidades: ["interpretar-expressoes-nao-verbais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_057",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual aprendizado em brincadeiras livres?",
      opcoes: [
        "Estrutura rigida",
        "Criatividade",
        "Regras fixas",
        "Competicao intensa"
      ],
      correta: "Criatividade",
      comentario: "Brincadeiras livres estimulam imaginacao e inovacao.",
      tempoEstimado: 40,
      tags: ["brincadeiras", "criatividade"],
      habilidades: ["analisar-aprendizados-brincadeiras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_058",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para danca ritmica?",
      opcoes: [
        "Ritmo",
        "Forca",
        "Velocidade",
        "Agilidade"
      ],
      correta: "Ritmo",
      comentario: "Ritmo coordena movimentos com musica.",
      tempoEstimado: 25,
      tags: ["habilidades-motoras", "ritmo"],
      habilidades: ["identificar-habilidades-danca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_059",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como o sono afeta o corpo?",
      opcoes: [
        "Cansaco",
        "Recuperacao",
        "Estresse",
        "Fraqueza"
      ],
      correta: "Recuperacao",
      comentario: "Sono permite reparo fisico e mental apos atividade.",
      tempoEstimado: 30,
      tags: ["corpo-mente", "sono"],
      habilidades: ["compreender-importancia-sono"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_060",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual desafio em atividades inclusivas?",
      opcoes: [
        "Facilidade",
        "Adaptacao",
        "Homogeneidade",
        "Exclusao"
      ],
      correta: "Adaptacao",
      comentario: "Adaptacao e necessaria para incluir todos os participantes.",
      tempoEstimado: 35,
      tags: ["inclusao", "adaptacao"],
      habilidades: ["interpretar-desafios-adaptacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_061",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Cultura corporal abrange?",
      opcoes: [
        "Apenas esportes",
        "Corpo e sociedade",
        "Somente mente",
        "Exclusivamente tecnologia"
      ],
      correta: "Corpo e sociedade",
      comentario: "Integra corpo com valores e praticas sociais.",
      tempoEstimado: 30,
      tags: ["cultura-corporal", "sociedade"],
      habilidades: ["compreender-abrangencia-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_062",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento para flexibilidade?",
      opcoes: [
        "Alongamento",
        "Corrida rapida",
        "Salto alto",
        "Levantamento"
      ],
      correta: "Alongamento",
      comentario: "Alongamento aumenta amplitude de movimento.",
      tempoEstimado: 35,
      tags: ["movimento", "flexibilidade"],
      habilidades: ["interpretar-movimentos-flexibilidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_063",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto da obesidade?",
      opcoes: [
        "Melhor saude",
        "Riscos cardiovasculares",
        "Maior energia",
        "Flexibilidade"
      ],
      correta: "Riscos cardiovasculares",
      comentario: "Obesidade aumenta chances de doencas cardiacas.",
      tempoEstimado: 40,
      tags: ["saude", "obesidade"],
      habilidades: ["analisar-impactos-obesidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_064",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo de expressao?",
      opcoes: [
        "Correr",
        "Sorrir",
        "Comer",
        "Dormir"
      ],
      correta: "Sorrir",
      comentario: "Sorriso expressa alegria corporalmente.",
      tempoEstimado: 20,
      tags: ["expressao-corporal", "sorriso"],
      habilidades: ["identificar-exemplos-expressao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_065",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio de jogos em grupo?",
      opcoes: [
        "Isolamento",
        "Socializacao",
        "Competicao solitaria",
        "Individualismo"
      ],
      correta: "Socializacao",
      comentario: "Jogos em grupo promovem interacao e amizade.",
      tempoEstimado: 30,
      tags: ["jogos", "socializacao"],
      habilidades: ["compreender-beneficios-grupo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_066",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para esportes aquaticos?",
      opcoes: [
        "Nado",
        "Corrida",
        "Salto",
        "Lancamento"
      ],
      correta: "Nado",
      comentario: "Nado desenvolve resistencia e tecnica na agua.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "nado"],
      habilidades: ["interpretar-habilidades-aquaticas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_067",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como o estresse cronico afeta?",
      opcoes: [
        "Relaxamento",
        "Doencas psicossomaticas",
        "Bem-estar",
        "Energia"
      ],
      correta: "Doencas psicossomaticas",
      comentario: "Estresse prolongado causa sintomas fisicos por tensao mental.",
      tempoEstimado: 40,
      tags: ["corpo-mente", "estresse-cronico"],
      habilidades: ["analisar-efeitos-estresse-cronico"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_068",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Inclusao significa?",
      opcoes: [
        "Excluir",
        "Incluir todos",
        "Competir",
        "Isolar"
      ],
      correta: "Incluir todos",
      comentario: "Inclusao garante participacao sem discriminacao.",
      tempoEstimado: 25,
      tags: ["inclusao", "todos"],
      habilidades: ["identificar-significado-inclusao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_069",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual origem da cultura corporal?",
      opcoes: [
        "Moderna",
        "Ancestral",
        "Tecnologica",
        "Industrial"
      ],
      correta: "Ancestral",
      comentario: "Praticas corporais existem desde tempos antigos.",
      tempoEstimado: 30,
      tags: ["cultura-corporal", "origem"],
      habilidades: ["compreender-origens-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_071",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habito saudavel?",
      opcoes: [
        "Alimentacao balanceada",
        "Fumar",
        "Beber alcool",
        "Sedentarismo"
      ],
      correta: "Alimentacao balanceada",
      comentario: "Dieta equilibrada fornece energia para atividade fisica.",
      tempoEstimado: 20,
      tags: ["saude", "alimentacao"],
      habilidades: ["identificar-habitos-saudaveis"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_072",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual forma de teatro corporal?",
      opcoes: [
        "Palavras",
        "Mímicas",
        "Musica",
        "Danca"
      ],
      correta: "Mímicas",
      comentario: "Mímicas usam gestos para contar historias sem fala.",
      tempoEstimado: 30,
      tags: ["expressao-corporal", "mimicas"],
      habilidades: ["compreender-teatro-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_073",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual brincadeira desenvolve memoria?",
      opcoes: [
        "Jogo de memoria corporal",
        "Corrida simples",
        "Salto",
        "Danca livre"
      ],
      correta: "Jogo de memoria corporal",
      comentario: "Repetir sequencias corporais estimula memoria.",
      tempoEstimado: 35,
      tags: ["brincadeiras", "memoria"],
      habilidades: ["interpretar-brincadeiras-memoria"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_074",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para artes marciais?",
      opcoes: [
        "Coordenacao",
        "Forca",
        "Equilibrio",
        "Todas"
      ],
      correta: "Todas",
      comentario: "Artes marciais combinam coordenacao, forca e equilibrio.",
      tempoEstimado: 40,
      tags: ["habilidades-motoras", "artes-marciais"],
      habilidades: ["analisar-habilidades-artes-marciais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_075",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Como a mente afeta o corpo?",
      opcoes: [
        "Pensamentos positivos melhoram performance",
        "Pensamentos nao afetam",
        "Apenas fisicamente",
        "Mentalmente isolado"
      ],
      correta: "Pensamentos positivos melhoram performance",
      comentario: "Atitude mental influencia resistencia e motivacao.",
      tempoEstimado: 25,
      tags: ["corpo-mente", "pensamentos"],
      habilidades: ["identificar-influencia-mental"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_076",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual estrategia para diversidade?",
      opcoes: [
        "Adaptar atividades",
        "Excluir diferencas",
        "Homogeneizar",
        "Competir apenas"
      ],
      correta: "Adaptar atividades",
      comentario: "Adaptacoes garantem participacao de todos os tipos corporais.",
      tempoEstimado: 30,
      tags: ["inclusao", "adaptar"],
      habilidades: ["compreender-estrategias-diversidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_077",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual evolucao da cultura corporal?",
      opcoes: [
        "De ritual para lazer",
        "Apenas profissional",
        "Somente escolar",
        "Exclusivamente competitiva"
      ],
      correta: "De ritual para lazer",
      comentario: "Praticas evoluiram de rituais para atividades recreativas.",
      tempoEstimado: 35,
      tags: ["cultura-corporal", "evolucao"],
      habilidades: ["interpretar-evolucao-cultura-corporal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_078",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto do movimento na longevidade?",
      opcoes: [
        "Reduz expectativa de vida",
        "Aumenta longevidade",
        "Nao afeta",
        "Diminui saude"
      ],
      correta: "Aumenta longevidade",
      comentario: "Atividade regular previne doencas e prolonga vida.",
      tempoEstimado: 40,
      tags: ["movimento", "longevidade"],
      habilidades: ["analisar-impactos-longevidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_079",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual indicador de bem-estar?",
      opcoes: [
        "Energia diaria",
        "Cansaco constante",
        "Doencas frequentes",
        "Estresse alto"
      ],
      correta: "Energia diaria",
      comentario: "Energia indica saude fisica e mental equilibrada.",
      tempoEstimado: 30,
      tags: ["qualidade-vida", "energia"],
      habilidades: ["compreender-indicadores-bem-estar"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_080",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica de improvisacao?",
      opcoes: [
        "Movimentos livres",
        "Sequencias fixas",
        "Regras rigidas",
        "Competicao"
      ],
      correta: "Movimentos livres",
      comentario: "Improvisacao permite expressao espontanea sem roteiro.",
      tempoEstimado: 35,
      tags: ["expressao-corporal", "improvisacao"],
      habilidades: ["interpretar-tecnicas-improvisacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_081",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual valor em jogos cooperativos?",
      opcoes: [
        "Competicao individual",
        "Solidariedade",
        "Vitoria a qualquer custo",
        "Isolamento"
      ],
      correta: "Solidariedade",
      comentario: "Jogos cooperativos ensinam ajuda mutua e equipe.",
      tempoEstimado: 40,
      tags: ["jogos", "solidariedade"],
      habilidades: ["analisar-valores-cooperativos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_082",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade basica?",
      opcoes: [
        "Agilidade",
        "Leitura",
        "Matematica",
        "Musica"
      ],
      correta: "Agilidade",
      comentario: "Agilidade permite mudancas rapidas de direcao.",
      tempoEstimado: 20,
      tags: ["habilidades-motoras", "agilidade"],
      habilidades: ["identificar-habilidades-basicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_083",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como a motivacao afeta o corpo?",
      opcoes: [
        "Aumenta resistencia",
        "Diminui energia",
        "Causa fadiga",
        "Reduz forca"
      ],
      correta: "Aumenta resistencia",
      comentario: "Motivacao mental prolonga esforco fisico.",
      tempoEstimado: 30,
      tags: ["corpo-mente", "motivacao"],
      habilidades: ["compreender-efeitos-motivacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_084",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio da inclusao?",
      opcoes: [
        "Aprendizado social",
        "Exclusao",
        "Competicao desigual",
        "Homogeneidade"
      ],
      correta: "Aprendizado social",
      comentario: "Inclusao promove empatia e respeito as diferencas.",
      tempoEstimado: 35,
      tags: ["inclusao", "aprendizado-social"],
      habilidades: ["interpretar-beneficios-inclusao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_085",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual dimensao cultural?",
      opcoes: [
        "Fisica e simbolica",
        "Apenas fisica",
        "Somente mental",
        "Exclusivamente tecnica"
      ],
      correta: "Fisica e simbolica",
      comentario: "Cultura corporal inclui simbolos e significados sociais.",
      tempoEstimado: 40,
      tags: ["cultura-corporal", "simbolica"],
      habilidades: ["analisar-dimensoes-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_086",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual movimento para relaxamento?",
      opcoes: [
        "Respiracao profunda",
        "Corrida intensa",
        "Salto alto",
        "Levantamento pesado"
      ],
      correta: "Respiracao profunda",
      comentario: "Respiracao profunda relaxa corpo e mente.",
      tempoEstimado: 25,
      tags: ["movimento", "relaxamento"],
      habilidades: ["identificar-movimentos-relaxamento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_087",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habito previne doencas?",
      opcoes: [
        "Atividade regular",
        "Fumar",
        "Comer fast food",
        "Dormir pouco"
      ],
      correta: "Atividade regular",
      comentario: "Exercicio fortalece sistema imunologico.",
      tempoEstimado: 30,
      tags: ["saude", "prevencao"],
      habilidades: ["compreender-habitos-prevencao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_088",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual arte corporal?",
      opcoes: [
        "Pintura",
        "Danca contemporanea",
        "Escultura",
        "Musica classica"
      ],
      correta: "Danca contemporanea",
      comentario: "Danca contemporanea expressa ideias modernas corporalmente.",
      tempoEstimado: 35,
      tags: ["expressao-corporal", "danca-contemporanea"],
      habilidades: ["interpretar-artes-corporais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_089",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual aprendizado em brincadeiras estruturadas?",
      opcoes: [
        "Criatividade limitada",
        "Respeito a regras",
        "Isolamento",
        "Competicao desleal"
      ],
      correta: "Respeito a regras",
      comentario: "Brincadeiras estruturadas ensinam disciplina e cooperacao.",
      tempoEstimado: 40,
      tags: ["brincadeiras", "regras"],
      habilidades: ["analisar-aprendizados-estruturados"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_090",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para esportes de raquete?",
      opcoes: [
        "Precisao no golpe",
        "Forca bruta",
        "Velocidade linear",
        "Equilibrio estatico"
      ],
      correta: "Precisao no golpe",
      comentario: "Precisao direciona bola com acuracia.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "raquete"],
      habilidades: ["compreender-habilidades-raquete"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_091",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Como o foco mental ajuda no esporte?",
      opcoes: [
        "Melhora tecnica",
        "Distrai",
        "Causa erro",
        "Reduz concentracao"
      ],
      correta: "Melhora tecnica",
      comentario: "Foco mental refina execucao de movimentos.",
      tempoEstimado: 35,
      tags: ["corpo-mente", "foco"],
      habilidades: ["interpretar-efeitos-foco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_092",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual desafio em atividades para deficientes?",
      opcoes: [
        "Adaptacao de equipamentos",
        "Facilidade",
        "Homogeneidade",
        "Exclusao facil"
      ],
      correta: "Adaptacao de equipamentos",
      comentario: "Equipamentos adaptados garantem participacao igualitaria.",
      tempoEstimado: 40,
      tags: ["inclusao", "deficientes"],
      habilidades: ["analisar-desafios-deficientes"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_093",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Conceito de cultura corporal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Cultura corporal e?",
      opcoes: [
        "Conjunto de praticas corporais",
        "Apenas esportes",
        "Somente alimentacao",
        "Exclusivamente higiene"
      ],
      correta: "Conjunto de praticas corporais",
      comentario: "Inclui movimentos, jogos e expressoes relacionadas ao corpo.",
      tempoEstimado: 20,
      tags: ["cultura-corporal", "praticas"],
      habilidades: ["identificar-conceito-praticas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_094",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Corpo e movimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual beneficio do movimento diario?",
      opcoes: [
        "Melhora circulacao",
        "Aumenta peso",
        "Diminui energia",
        "Reduz forca"
      ],
      correta: "Melhora circulacao",
      comentario: "Movimento estimula sangue e oxigenacao.",
      tempoEstimado: 30,
      tags: ["movimento", "circulacao"],
      habilidades: ["compreender-beneficios-circulacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_095",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Saude e qualidade de vida",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual componente da qualidade de vida?",
      opcoes: [
        "Saude fisica",
        "Renda baixa",
        "Estresse constante",
        "Doencas"
      ],
      correta: "Saude fisica",
      comentario: "Saude fisica e base para bem-estar geral.",
      tempoEstimado: 35,
      tags: ["qualidade-vida", "saude-fisica"],
      habilidades: ["interpretar-componentes-qualidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_096",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Expressao corporal",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica de pantomima?",
      opcoes: [
        "Usar objetos invisiveis",
        "Falar alto",
        "Cantar",
        "Dancar"
      ],
      correta: "Usar objetos invisiveis",
      comentario: "Pantomima simula objetos com gestos sem props.",
      tempoEstimado: 40,
      tags: ["expressao-corporal", "pantomima"],
      habilidades: ["analisar-tecnicas-pantomima"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_097",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Jogos e brincadeiras",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual brincadeira para criancas?",
      opcoes: [
        "Pula-corda",
        "Levantamento de peso",
        "Corrida longa",
        "Nado profissional"
      ],
      correta: "Pula-corda",
      comentario: "Pula-corda desenvolve coordenacao em criancas.",
      tempoEstimado: 25,
      tags: ["brincadeiras", "criancas"],
      habilidades: ["identificar-brincadeiras-criancas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_098",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Habilidades motoras",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para basquete?",
      opcoes: [
        "Drible",
        "Nado",
        "Ciclismo",
        "Ginastica"
      ],
      correta: "Drible",
      comentario: "Drible permite controle de bola em movimento.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "basquete"],
      habilidades: ["compreender-habilidades-basquete"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_099",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Relacao corpo-mente",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Como a ansiedade afeta o esporte?",
      opcoes: [
        "Melhora performance",
        "Diminui concentracao",
        "Aumenta forca",
        "Reduz fadiga"
      ],
      correta: "Diminui concentracao",
      comentario: "Ansiedade dispersa foco e prejudica execucao.",
      tempoEstimado: 35,
      tags: ["corpo-mente", "ansiedade"],
      habilidades: ["interpretar-efeitos-ansiedade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "cc_100",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Cultura Corporal",
      subtopico: "Inclusao e diversidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto da diversidade cultural em jogos?",
      opcoes: [
        "Enriquecimento de experiencias",
        "Conflitos",
        "Homogeneidade",
        "Exclusao"
      ],
      correta: "Enriquecimento de experiencias",
      comentario: "Diversidade cultural traz novas formas de jogar e interagir.",
      tempoEstimado: 40,
      tags: ["inclusao", "diversidade-cultural"],
      habilidades: ["analisar-impactos-diversidade-cultural"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    }
  ]
};
