export const numerosReais = {
  id: "matematica_numeros_reais",
  materia: "Matemática",
  serie: [1],
  topico: "Números Reais",

  metadados: {
    disciplinaId: "matematica",
    eixo: "Numeros",
    subtopicosBase: [
      "Conjuntos numericos",
      "Reta numerica",
      "Intervalos",
      "Modulo",
      "Comparacao",
      "Operacoes",
      "Dizimas"
    ]
  },

  questoes: [
    {
      id: "nr_001",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "calculo",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é natural?",
      opcoes: ["-1", "0", "1/2", "√2"],
      correta: "0",
      comentario: "0 pertence ao conjunto dos números naturais.",
      tempoEstimado: 20,
      tags: ["naturais"]
    },
    {
      id: "nr_002",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "multipla_escolha",
      enunciado: "Qual é um número inteiro?",
      opcoes: ["3,5", "-2", "1/3", "√5"],
      correta: "-2",
      comentario: "Inteiros não possuem parte decimal.",
      tempoEstimado: 20,
      tags: ["inteiros"]
    },
    {
      id: "nr_003",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,5", "0,05"],
      correta: "0,5",
      comentario: "0,5 é maior que 0,05 pois representa metade.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_004",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−5|",
      opcoes: [],
      correta: "5",
      comentario: "Módulo é sempre positivo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_005",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "−3 está à esquerda de 2 na reta numérica.",
      opcoes: [],
      correta: true,
      comentario: "Números negativos ficam à esquerda.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_006",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 2 + (−5)",
      opcoes: [],
      correta: "-3",
      comentario: "Soma com número negativo equivale a subtração.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_007",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["−1/2", "−0,3"],
      correta: "−1/2",
      comentario: "−0,5 é menor que −0,3.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_008",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene em ordem crescente",
      opcoes: ["2", "-1", "0"],
      correta: ["-1", "0", "2"],
      comentario: "Menor para maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_009",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−3 + 1|",
      opcoes: [],
      correta: "2",
      comentario: "Primeiro resolve dentro do módulo.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_010",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,333... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica é racional.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_011",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−2)² − 5",
      opcoes: [],
      correta: "-1",
      comentario: "Potência primeiro, depois subtração.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_012",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√4", "1,9"],
      correta: "√4",
      comentario: "√4 = 2.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_013",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: −1, √2, 0",
      opcoes: ["-1", "√2", "0"],
      correta: ["-1", "0", "√2"],
      comentario: "√2 ≈ 1,41.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
        {
      id: "nr_014",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é racional?",
      opcoes: ["√3", "π", "1/4", "√5"],
      correta: "1/4",
      comentario: "Racionais podem ser escritos como fração.",
      tempoEstimado: 20,
      tags: ["racionais"]
    },
    {
      id: "nr_015",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 7 − 10",
      opcoes: [],
      correta: "-3",
      comentario: "Subtração resulta em número negativo.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_016",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["-2", "-5"],
      correta: "-2",
      comentario: "Mais próximo de zero é maior.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_017",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |4|",
      opcoes: [],
      correta: "4",
      comentario: "Módulo de número positivo é ele mesmo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_018",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0 está entre −1 e 1.",
      opcoes: [],
      correta: true,
      comentario: "0 fica entre números negativos e positivos.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_019",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −3 + 7",
      opcoes: [],
      correta: "4",
      comentario: "Soma de números com sinais diferentes.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_020",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,75", "3/5"],
      correta: "0,75",
      comentario: "0,75 = 3/4, maior que 3/5.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_021",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene em ordem decrescente",
      opcoes: ["-1", "2", "0"],
      correta: ["2", "0", "-1"],
      comentario: "Maior para menor.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_022",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−8|",
      opcoes: [],
      correta: "8",
      comentario: "Módulo remove sinal negativo.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_023",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,121212... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica é racional.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_024",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−3)² + (−4)",
      opcoes: [],
      correta: "5",
      comentario: "9 − 4 = 5.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_025",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["√9", "2,9"],
      correta: "2,9",
      comentario: "√9 = 3.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_026",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √2, −2, 1",
      opcoes: ["√2", "-2", "1"],
      correta: ["-2", "1", "√2"],
      comentario: "√2 ≈ 1,41.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
        {
      id: "nr_027",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual número é irracional?",
      opcoes: ["2", "3/2", "√7", "0,25"],
      correta: "√7",
      comentario: "Raiz não exata gera número irracional.",
      tempoEstimado: 20,
      tags: ["irracionais"]
    },
    {
      id: "nr_028",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −6 + 2",
      opcoes: [],
      correta: "-4",
      comentario: "Soma de sinais diferentes.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_029",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["1", "0,9"],
      correta: "1",
      comentario: "1 é maior que 0,9.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_030",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−10|",
      opcoes: [],
      correta: "10",
      comentario: "Módulo sempre positivo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_031",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "−5 está à direita de −10.",
      opcoes: [],
      correta: true,
      comentario: "−5 é maior que −10.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_032",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 4 × (−2)",
      opcoes: [],
      correta: "-8",
      comentario: "Produto de sinais diferentes é negativo.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_033",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["2/3", "0,6"],
      correta: "2/3",
      comentario: "2/3 ≈ 0,66.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_034",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene em ordem crescente",
      opcoes: ["3", "-2", "1"],
      correta: ["-2", "1", "3"],
      comentario: "Do menor para o maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_035",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |5 − 9|",
      opcoes: [],
      correta: "4",
      comentario: "Resultado interno é −4.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_036",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,101001000... é periódico.",
      opcoes: [],
      correta: false,
      comentario: "Não há repetição fixa.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_037",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−2)³ + 10",
      opcoes: [],
      correta: "2",
      comentario: "−8 + 10 = 2.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_038",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√16", "3,9"],
      correta: "√16",
      comentario: "√16 = 4.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_039",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 0,5; 1/3; √2",
      opcoes: ["0,5", "1/3", "√2"],
      correta: ["1/3", "0,5", "√2"],
      comentario: "1/3 ≈ 0,33 e √2 ≈ 1,41.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_040",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−3²|",
      opcoes: [],
      correta: "9",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_041",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,142857142857... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },

    {
      id: "nr_042",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 9 ÷ (−3)",
      opcoes: [],
      correta: "-3",
      comentario: "Divisão de sinais diferentes é negativa.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_043",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["−0,2", "−1/5"],
      correta: "−0,2",
      comentario: "São iguais, mas opção decimal representa.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_044",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: −3, −1, −2",
      opcoes: ["-3", "-1", "-2"],
      correta: ["-3", "-2", "-1"],
      comentario: "Mais negativo é menor.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_045",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |2 − 7|",
      opcoes: [],
      correta: "5",
      comentario: "Resultado interno −5.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_046",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Todo número decimal finito é racional.",
      opcoes: [],
      correta: true,
      comentario: "Pode virar fração.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_047",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−5)² − (−3)",
      opcoes: [],
      correta: "28",
      comentario: "25 + 3 = 28.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_048",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√25", "4,9"],
      correta: "√25",
      comentario: "√25 = 5.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_049",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √3, 1,5, 1,7",
      opcoes: ["√3", "1,5", "1,7"],
      correta: ["1,5", "1,7", "√3"],
      comentario: "√3 ≈ 1,73.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_050",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−4²|",
      opcoes: [],
      correta: "16",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
        {
      id: "nr_051",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é irracional?",
      opcoes: ["0,2", "1/5", "√11", "-3"],
      correta: "√11",
      comentario: "Raiz não exata é irracional.",
      tempoEstimado: 20,
      tags: ["irracionais"]
    },
    {
      id: "nr_052",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −8 + 5",
      opcoes: [],
      correta: "-3",
      comentario: "Sinais diferentes, subtrai.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_053",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,7", "0,65"],
      correta: "0,7",
      comentario: "0,70 > 0,65.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_054",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−2|",
      opcoes: [],
      correta: "2",
      comentario: "Módulo remove o sinal.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_055",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "3 está à direita de 1.",
      opcoes: [],
      correta: true,
      comentario: "Maior valor fica à direita.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_056",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 6 × (−3)",
      opcoes: [],
      correta: "-18",
      comentario: "Produto negativo.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_057",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["2/5", "0,45"],
      correta: "2/5",
      comentario: "2/5 = 0,4.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_058",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 4, −1, 2",
      opcoes: ["4", "-1", "2"],
      correta: ["-1", "2", "4"],
      comentario: "Menor para maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_059",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−6 + 2|",
      opcoes: [],
      correta: "4",
      comentario: "−6 + 2 = −4.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_060",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,777... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_061",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−4)² − 6",
      opcoes: [],
      correta: "10",
      comentario: "16 − 6 = 10.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_062",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√36", "5,9"],
      correta: "√36",
      comentario: "√36 = 6.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_063",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √5, 2, 2,3",
      opcoes: ["√5", "2", "2,3"],
      correta: ["2", "2,3", "√5"],
      comentario: "√5 ≈ 2,23.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_064",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−5²|",
      opcoes: [],
      correta: "25",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_065",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,123123... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
        {
      id: "nr_066",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual é um número inteiro?",
      opcoes: ["2,5", "-3", "1/2", "√4"],
      correta: "-3",
      comentario: "Inteiros não possuem parte decimal.",
      tempoEstimado: 20,
      tags: ["inteiros"]
    },
    {
      id: "nr_067",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 10 − 4",
      opcoes: [],
      correta: "6",
      comentario: "Subtração simples.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_068",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,2", "0,25"],
      correta: "0,25",
      comentario: "0,25 > 0,2.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_069",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−1|",
      opcoes: [],
      correta: "1",
      comentario: "Módulo sempre positivo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_070",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "−2 é menor que 1.",
      opcoes: [],
      correta: true,
      comentario: "Negativos são menores que positivos.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_071",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 3 × (−5)",
      opcoes: [],
      correta: "-15",
      comentario: "Produto negativo.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_072",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["3/4", "0,7"],
      correta: "3/4",
      comentario: "3/4 = 0,75.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_073",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 1, −3, 0",
      opcoes: ["1", "-3", "0"],
      correta: ["-3", "0", "1"],
      comentario: "Ordem crescente.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_074",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |3 − 8|",
      opcoes: [],
      correta: "5",
      comentario: "Resultado interno −5.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_075",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,909090... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_076",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−6)² − 10",
      opcoes: [],
      correta: "26",
      comentario: "36 − 10 = 26.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_077",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√49", "6,8"],
      correta: "√49",
      comentario: "√49 = 7.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_078",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √6, 2,4, 2",
      opcoes: ["√6", "2,4", "2"],
      correta: ["2", "2,4", "√6"],
      comentario: "√6 ≈ 2,45.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_079",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−7²|",
      opcoes: [],
      correta: "49",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_080",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,454545... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
        {
      id: "nr_081",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números é irracional?",
      opcoes: ["1/2", "0,4", "√13", "-2"],
      correta: "√13",
      comentario: "Raiz não exata é irracional.",
      tempoEstimado: 20,
      tags: ["irracionais"]
    },
    {
      id: "nr_082",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −9 + 4",
      opcoes: [],
      correta: "-5",
      comentario: "Sinais diferentes.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_083",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,8", "0,75"],
      correta: "0,8",
      comentario: "0,8 > 0,75.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_084",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−12|",
      opcoes: [],
      correta: "12",
      comentario: "Módulo remove sinal.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_085",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "5 é maior que 3.",
      opcoes: [],
      correta: true,
      comentario: "Maior valor fica à direita.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_086",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 12 ÷ (−4)",
      opcoes: [],
      correta: "-3",
      comentario: "Divisão negativa.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_087",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,6", "5/8"],
      correta: "5/8",
      comentario: "5/8 = 0,625.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_088",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 5, −2, 3",
      opcoes: ["5", "-2", "3"],
      correta: ["-2", "3", "5"],
      comentario: "Menor para maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_089",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |7 − 10|",
      opcoes: [],
      correta: "3",
      comentario: "Resultado interno −3.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_090",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,666... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_091",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−8)² − 20",
      opcoes: [],
      correta: "44",
      comentario: "64 − 20 = 44.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_092",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√81", "8,9"],
      correta: "√81",
      comentario: "√81 = 9.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_093",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √7, 2,6, 2,5",
      opcoes: ["√7", "2,6", "2,5"],
      correta: ["2,5", "2,6", "√7"],
      comentario: "√7 ≈ 2,64.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_094",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−9²|",
      opcoes: [],
      correta: "81",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_095",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,232323... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
        {
      id: "nr_096",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é racional?",
      opcoes: ["√10", "π", "2/3", "√3"],
      correta: "2/3",
      comentario: "Número racional pode ser escrito como fração.",
      tempoEstimado: 20,
      tags: ["racionais"]
    },
    {
      id: "nr_097",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −4 + 9",
      opcoes: [],
      correta: "5",
      comentario: "Soma de sinais diferentes.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_098",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,95", "0,9"],
      correta: "0,95",
      comentario: "0,95 > 0,9.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_099",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−15|",
      opcoes: [],
      correta: "15",
      comentario: "Módulo torna positivo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_100",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "−1 está à esquerda de 0.",
      opcoes: [],
      correta: true,
      comentario: "Números negativos ficam à esquerda.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_101",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 15 ÷ 3",
      opcoes: [],
      correta: "5",
      comentario: "Divisão simples.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_102",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["0,4", "2/5"],
      correta: "0,4",
      comentario: "São iguais, mas representações equivalentes.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_103",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: −4, 0, 3",
      opcoes: ["-4", "0", "3"],
      correta: ["-4", "0", "3"],
      comentario: "Ordem crescente.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_104",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |10 − 13|",
      opcoes: [],
      correta: "3",
      comentario: "Resultado interno −3.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_105",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,888... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_106",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−10)² − 30",
      opcoes: [],
      correta: "70",
      comentario: "100 − 30 = 70.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_107",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√100", "9,9"],
      correta: "√100",
      comentario: "√100 = 10.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_108",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √8, 2,8, 3",
      opcoes: ["√8", "2,8", "3"],
      correta: ["2,8", "√8", "3"],
      comentario: "√8 ≈ 2,82.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_109",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−11²|",
      opcoes: [],
      correta: "121",
      comentario: "Potência antes do sinal.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_110",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,121212... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
        {
      id: "nr_111",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é irracional?",
      opcoes: ["0,3", "3/10", "√14", "-5"],
      correta: "√14",
      comentario: "Raiz não exata é irracional.",
      tempoEstimado: 20,
      tags: ["irracionais"]
    },
    {
      id: "nr_112",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 11 − 15",
      opcoes: [],
      correta: "-4",
      comentario: "Subtração com resultado negativo.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_113",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,45", "0,5"],
      correta: "0,5",
      comentario: "0,50 é maior que 0,45.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_114",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−20|",
      opcoes: [],
      correta: "20",
      comentario: "Módulo remove o sinal negativo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_115",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "2 está à direita de −2.",
      opcoes: [],
      correta: true,
      comentario: "Números maiores ficam à direita na reta.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_116",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −7 × 2",
      opcoes: [],
      correta: "-14",
      comentario: "Produto de sinais diferentes é negativo.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_117",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["7/10", "0,68"],
      correta: "7/10",
      comentario: "7/10 = 0,7.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_118",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 2, −4, 1",
      opcoes: ["2", "-4", "1"],
      correta: ["-4", "1", "2"],
      comentario: "Ordem crescente: menor para maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_119",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |4 − 11|",
      opcoes: [],
      correta: "7",
      comentario: "4 − 11 = −7, então o módulo é 7.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_120",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,252525... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Toda dízima periódica é racional.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_121",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−12)² − 40",
      opcoes: [],
      correta: "104",
      comentario: "144 − 40 = 104.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_122",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√121", "10,9"],
      correta: "√121",
      comentario: "√121 = 11.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_123",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √10, 3,1, 3",
      opcoes: ["√10", "3,1", "3"],
      correta: ["3", "3,1", "√10"],
      comentario: "√10 ≈ 3,16.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_124",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−13²|",
      opcoes: [],
      correta: "169",
      comentario: "A potência vem antes do sinal: −13² = −169.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_125",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,565656... é racional.",
      opcoes: [],
      correta: true,
      comentario: "É uma dízima periódica.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },

    {
      id: "nr_126",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é racional?",
      opcoes: ["√15", "π", "5/6", "√17"],
      correta: "5/6",
      comentario: "Racional pode ser escrito como fração de inteiros.",
      tempoEstimado: 20,
      tags: ["racionais"]
    },
    {
      id: "nr_127",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −14 + 6",
      opcoes: [],
      correta: "-8",
      comentario: "Sinais diferentes: subtrai e mantém o sinal do maior módulo.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_128",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,11", "0,09"],
      correta: "0,11",
      comentario: "0,11 é maior que 0,09.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_129",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−25|",
      opcoes: [],
      correta: "25",
      comentario: "Módulo representa distância até zero.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_130",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "−6 está à esquerda de −3.",
      opcoes: [],
      correta: true,
      comentario: "−6 é menor que −3.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_131",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 18 ÷ (−6)",
      opcoes: [],
      correta: "-3",
      comentario: "Divisão de sinais diferentes é negativa.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_132",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["4/5", "0,79"],
      correta: "4/5",
      comentario: "4/5 = 0,8.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_133",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: −5, 2, −1",
      opcoes: ["-5", "2", "-1"],
      correta: ["-5", "-1", "2"],
      comentario: "Do menor para o maior.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_134",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |9 − 14|",
      opcoes: [],
      correta: "5",
      comentario: "9 − 14 = −5, e |−5| = 5.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_135",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,313131... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica pertence aos racionais.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },

    {
      id: "nr_136",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (−15)² − 50",
      opcoes: [],
      correta: "175",
      comentario: "225 − 50 = 175.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_137",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√144", "11,8"],
      correta: "√144",
      comentario: "√144 = 12.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_138",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √12, 3,4, 3,5",
      opcoes: ["√12", "3,4", "3,5"],
      correta: ["3,4", "√12", "3,5"],
      comentario: "√12 ≈ 3,46.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_139",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule |−16²|",
      opcoes: [],
      correta: "256",
      comentario: "−16² = −256, então o módulo é 256.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_140",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,474747... é racional.",
      opcoes: [],
      correta: true,
      comentario: "Dízima periódica é racional.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },

    {
      id: "nr_141",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual dos números abaixo é irracional?",
      opcoes: ["0,125", "1/8", "√19", "-7"],
      correta: "√19",
      comentario: "Raiz não exata não é racional.",
      tempoEstimado: 20,
      tags: ["irracionais"]
    },
    {
      id: "nr_142",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: 13 − 20",
      opcoes: [],
      correta: "-7",
      comentario: "Subtração com resultado negativo.",
      tempoEstimado: 20,
      tags: ["operacoes"]
    },
    {
      id: "nr_143",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,33", "0,303"],
      correta: "0,33",
      comentario: "0,330 é maior que 0,303.",
      tempoEstimado: 20,
      tags: ["comparacao"]
    },
    {
      id: "nr_144",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |−30|",
      opcoes: [],
      correta: "30",
      comentario: "Módulo é sempre não negativo.",
      tempoEstimado: 20,
      tags: ["modulo"]
    },
    {
      id: "nr_145",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "7 está à direita de 4.",
      opcoes: [],
      correta: true,
      comentario: "Na reta, valores maiores ficam à direita.",
      tempoEstimado: 20,
      tags: ["reta"]
    },

    {
      id: "nr_146",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 4,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule: −9 × 3",
      opcoes: [],
      correta: "-27",
      comentario: "Produto de negativo por positivo é negativo.",
      tempoEstimado: 25,
      tags: ["operacoes"]
    },
    {
      id: "nr_147",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["9/10", "0,89"],
      correta: "9/10",
      comentario: "9/10 = 0,9.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_148",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 4, −6, −2",
      opcoes: ["4", "-6", "-2"],
      correta: ["-6", "-2", "4"],
      comentario: "Mais negativo é menor.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_149",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "calculo",
      tipo: "input",
      enunciado: "Calcule |12 − 18|",
      opcoes: [],
      correta: "6",
      comentario: "12 − 18 = −6, então o módulo é 6.",
      tempoEstimado: 25,
      tags: ["modulo"]
    },
    {
      id: "nr_150",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "0,787878... é racional.",
      opcoes: [],
      correta: true,
      comentario: "É uma dízima periódica.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },
        {
      id: "nr_151",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,499", "1/2"],
      correta: "1/2",
      comentario: "1/2 = 0,5.",
      tempoEstimado: 25,
      tags: ["comparacao"]
    },
    {
      id: "nr_152",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fração representa 0,333...?",
      opcoes: ["1/2", "1/3", "3/10", "2/3"],
      correta: "1/3",
      comentario: "Dízima periódica simples.",
      tempoEstimado: 25,
      tags: ["dizima"]
    },
    {
      id: "nr_153",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual intervalo representa −2 ≤ x < 3?",
      opcoes: ["(−2,3)", "[−2,3)", "(−2,3]", "[−2,3]"],
      correta: "[−2,3)",
      comentario: "Inclui −2 e exclui 3.",
      tempoEstimado: 25,
      tags: ["intervalos"]
    },
    {
      id: "nr_154",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x| = 5",
      opcoes: [],
      correta: "5 ou -5",
      comentario: "Duas soluções simétricas.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_155",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Entre −1 e 0 existem infinitos números reais.",
      opcoes: [],
      correta: true,
      comentario: "Os reais são densos.",
      tempoEstimado: 25,
      tags: ["reta"]
    },

    {
      id: "nr_156",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√5", "2,2"],
      correta: "2,2",
      comentario: "√5 ≈ 2,236.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_157",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: (3/4) + 0,25",
      opcoes: [],
      correta: "1",
      comentario: "0,25 = 1/4.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_158",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √2, 1,4, 1,5",
      opcoes: ["√2", "1,4", "1,5"],
      correta: ["1,4", "√2", "1,5"],
      comentario: "√2 ≈ 1,414.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_159",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual é a fração de 0,121212...?",
      opcoes: ["12/99", "11/99", "1/12", "6/11"],
      correta: "12/99",
      comentario: "Período de 2 dígitos.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
    {
      id: "nr_160",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 5,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "O intervalo (0,1) inclui 0?",
      opcoes: [],
      correta: false,
      comentario: "Parênteses não incluem extremos.",
      tempoEstimado: 25,
      tags: ["intervalos"]
    },

    {
      id: "nr_161",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x − 3| = 2",
      opcoes: [],
      correta: "5 ou 1",
      comentario: "x − 3 = ±2.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_162",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,2²", "0,04"],
      correta: "iguais",
      comentario: "0,2² = 0,04.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_163",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 0,5 × 0,2",
      opcoes: [],
      correta: "0,1",
      comentario: "Multiplicação de decimais.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_164",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 1/2, 0,49, 0,5",
      opcoes: ["1/2", "0,49", "0,5"],
      correta: ["0,49", "1/2", "0,5"],
      comentario: "1/2 = 0,5.",
      tempoEstimado: 30,
      tags: ["ordenacao"]
    },
    {
      id: "nr_165",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Existe número real entre 0,1 e 0,11.",
      opcoes: [],
      correta: true,
      comentario: "Infinitos números entre dois reais.",
      tempoEstimado: 25,
      tags: ["reta"]
    },

    {
      id: "nr_166",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual intervalo representa x > −1 e x ≤ 2?",
      opcoes: ["(−1,2]", "[−1,2)", "(−1,2)", "[−1,2]"],
      correta: "(−1,2]",
      comentario: "Aberto em −1 e fechado em 2.",
      tempoEstimado: 30,
      tags: ["intervalos"]
    },
    {
      id: "nr_167",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |2x| = 6",
      opcoes: [],
      correta: "3 ou -3",
      comentario: "2x = ±6.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_168",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["(0,9)²", "0,8"],
      correta: "(0,9)²",
      comentario: "(0,9)² = 0,81.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_169",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 1/3 + 0,666...",
      opcoes: [],
      correta: "1",
      comentario: "0,666... = 2/3.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_170",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: √3, 1,7, 1,73",
      opcoes: ["√3", "1,7", "1,73"],
      correta: ["1,7", "1,73", "√3"],
      comentario: "√3 ≈ 1,732.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
        {
      id: "nr_171",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual é a fração equivalente a 0,090909...?",
      opcoes: ["1/9", "9/99", "9/100", "10/99"],
      correta: "9/99",
      comentario: "0,090909... = 9/99 = 1/11.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
    {
      id: "nr_172",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Se a < b, então a está à esquerda de b na reta numérica.",
      opcoes: [],
      correta: true,
      comentario: "Na reta numérica, menor fica à esquerda de maior.",
      tempoEstimado: 30,
      tags: ["reta"]
    },
    {
      id: "nr_173",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual intervalo representa todos os reais x tais que x < 4?",
      opcoes: ["(−∞,4)", "(−∞,4]", "[4,+∞)", "(4,+∞)"],
      correta: "(−∞,4)",
      comentario: "Como 4 não está incluído, usa parêntese em 4.",
      tempoEstimado: 25,
      tags: ["intervalos"]
    },
    {
      id: "nr_174",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 2,5 − 0,75",
      opcoes: [],
      correta: "1,75",
      comentario: "Alinhe as casas decimais para subtrair.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_175",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["0,09", "1/12"],
      correta: "0,09",
      comentario: "1/12 ≈ 0,0833, então 0,09 é maior.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },

    {
      id: "nr_176",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x + 4| = 3",
      opcoes: [],
      correta: "-1 ou -7",
      comentario: "x + 4 = 3 ou x + 4 = -3.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_177",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "vf",
      enunciado: "Toda dízima não periódica é irracional.",
      opcoes: [],
      correta: true,
      comentario: "Se não termina e não repete período, é irracional.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },
    {
      id: "nr_178",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual número pertence aos racionais, mas não aos inteiros?",
      opcoes: ["-4", "3/2", "√9", "0"],
      correta: "3/2",
      comentario: "3/2 é racional e não é inteiro.",
      tempoEstimado: 25,
      tags: ["racionais", "inteiros"]
    },
    {
      id: "nr_179",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 2/5, 0,39, √0,16",
      opcoes: ["2/5", "0,39", "√0,16"],
      correta: ["0,39", "2/5", "√0,16"],
      comentario: "2/5 = 0,4 e √0,16 = 0,4.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_180",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "comparacao",
      enunciado: "Qual está mais próximo de zero?",
      opcoes: ["-0,08", "0,1"],
      correta: "-0,08",
      comentario: "O menor módulo indica maior proximidade de zero.",
      tempoEstimado: 25,
      tags: ["reta", "comparacao"]
    },

    {
      id: "nr_181",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual intervalo representa x ≥ 0 e x < 5?",
      opcoes: ["[0,5)", "(0,5]", "[0,5]", "(0,5)"],
      correta: "[0,5)",
      comentario: "Inclui 0 e exclui 5.",
      tempoEstimado: 30,
      tags: ["intervalos"]
    },
    {
      id: "nr_182",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 0,25 ÷ 0,5",
      opcoes: [],
      correta: "0,5",
      comentario: "0,25 é metade de 0,5.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_183",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["√2,25", "1,49"],
      correta: "√2,25",
      comentario: "√2,25 = 1,5.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },
    {
      id: "nr_184",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x − 1| = 4",
      opcoes: [],
      correta: "5 ou -3",
      comentario: "x − 1 = 4 ou x − 1 = -4.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_185",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual é a fração equivalente a 0,666...?",
      opcoes: ["1/3", "2/3", "3/5", "6/10"],
      correta: "2/3",
      comentario: "A dízima 0,666... representa 2/3.",
      tempoEstimado: 30,
      tags: ["dizima"]
    },

    {
      id: "nr_186",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 6,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Todo número inteiro é racional.",
      opcoes: [],
      correta: true,
      comentario: "Qualquer inteiro n pode ser escrito como n/1.",
      tempoEstimado: 25,
      tags: ["inteiros", "racionais"]
    },
    {
      id: "nr_187",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Se dois números reais são diferentes, sempre existe outro número real entre eles.",
      opcoes: [],
      correta: true,
      comentario: "Os números reais são densos na reta.",
      tempoEstimado: 30,
      tags: ["reta"]
    },
    {
      id: "nr_188",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual intervalo representa todos os reais x tais que x ≤ -2?",
      opcoes: ["(−∞,−2)", "(−∞,−2]", "[−2,+∞)", "(−2,+∞)"],
      correta: "(−∞,−2]",
      comentario: "Inclui −2, então usa colchete nele.",
      tempoEstimado: 30,
      tags: ["intervalos"]
    },
    {
      id: "nr_189",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 1,2 + 0,08",
      opcoes: [],
      correta: "1,28",
      comentario: "Some alinhando as casas decimais.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_190",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é menor?",
      opcoes: ["-√9", "-2,9"],
      correta: "-√9",
      comentario: "-√9 = -3, que é menor que -2,9.",
      tempoEstimado: 30,
      tags: ["comparacao"]
    },

    {
      id: "nr_191",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: −√4, −1,9, −2,1",
      opcoes: ["−√4", "−1,9", "−2,1"],
      correta: ["−2,1", "−√4", "−1,9"],
      comentario: "−√4 = −2.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_192",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x + 2| = 0",
      opcoes: [],
      correta: "-2",
      comentario: "Só ocorre quando a expressão interna vale zero.",
      tempoEstimado: 30,
      tags: ["modulo"]
    },
    {
      id: "nr_193",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Dizimas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "multipla_escolha",
      enunciado: "Qual decimal representa 5/8?",
      opcoes: ["0,625", "0,58", "0,8", "0,125"],
      correta: "0,625",
      comentario: "5 ÷ 8 = 0,625.",
      tempoEstimado: 30,
      tags: ["dizima", "racionais"]
    },
    {
      id: "nr_194",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Conjuntos numericos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "Todo número irracional é real.",
      opcoes: [],
      correta: true,
      comentario: "Os irracionais formam um subconjunto dos reais.",
      tempoEstimado: 30,
      tags: ["irracionais", "reais"]
    },
    {
      id: "nr_195",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Reta numerica",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual está mais distante de zero?",
      opcoes: ["-4,5", "4,2"],
      correta: "-4,5",
      comentario: "Compara-se o módulo: 4,5 > 4,2.",
      tempoEstimado: 30,
      tags: ["reta", "modulo", "comparacao"]
    },

    {
      id: "nr_196",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Intervalos",
      dificuldadeLabel: "media",
      dificuldadeNivel: 7,
      cognicao: "interpretacao",
      tipo: "vf",
      enunciado: "O intervalo [2,5] inclui 2 e 5.",
      opcoes: [],
      correta: true,
      comentario: "Colchetes indicam inclusão dos extremos.",
      tempoEstimado: 25,
      tags: ["intervalos"]
    },
    {
      id: "nr_197",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Operacoes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Calcule: 0,04 + 0,006",
      opcoes: [],
      correta: "0,046",
      comentario: "Alinhe as casas decimais antes de somar.",
      tempoEstimado: 30,
      tags: ["operacoes"]
    },
    {
      id: "nr_198",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Comparacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "comparacao",
      enunciado: "Qual é maior?",
      opcoes: ["1,01", "√1,0201"],
      correta: "iguais",
      comentario: "Como 1,01² = 1,0201, então √1,0201 = 1,01.",
      tempoEstimado: 30,
      tags: ["comparacao", "raiz"]
    },
    {
      id: "nr_199",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Ordenacao",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "ordenacao",
      enunciado: "Ordene: 0,707; √0,49; 7/10",
      opcoes: ["0,707", "√0,49", "7/10"],
      correta: ["7/10", "√0,49", "0,707"],
      comentario: "7/10 = 0,7 e √0,49 = 0,7.",
      tempoEstimado: 35,
      tags: ["ordenacao"]
    },
    {
      id: "nr_200",
      serie: [1],
      materia: "Matemática",
      topico: "Números Reais",
      subtopico: "Modulo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "estrategia",
      tipo: "input",
      enunciado: "Resolva: |x| = 0,4",
      opcoes: [],
      correta: "0,4 ou -0,4",
      comentario: "O módulo admite dois valores simétricos.",
      tempoEstimado: 30,
      tags: ["modulo"]
    }
  ]
};