export const historiaDaArteClassica = {
  id: "artes_historia_da_arte_classica",
  materia: "Artes",
  serie: [1],
  topico: "Historia da Arte Classica",
  metadados: {
    disciplinaId: "artes",
    base: "ESCOLAR",
    eixo: "Artes",
    frente: "Historia da arte",
    subtopicosBase: ["arte-antiga", "renascimento", "barroco", "classicos-infantis", "periodos-basicos", "influencias-culturais"],
    habilidadesBase: ["compreender-periodos", "identificar-artistas", "analisar-obras-classicas", "relacionar-cultura"],
    searchAliases: ["historia arte classica", "arte antiga renascimento"],
    auditado: false
  },
  questoes: [
    {
      id: "hac_001",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual civilizacao antiga usava piramides?",
      opcoes: [
        "Gregos",
        "Romanos",
        "Egipcios",
        "Maias"
      ],
      correta: "Egipcios",
      comentario: "Egipcios construiram piramides como tumbas.",
      tempoEstimado: 20,
      tags: ["egito", "arte-antiga"],
      habilidades: ["identificar-civilizacoes-antigas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_002",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os gregos criaram?",
      opcoes: [
        "Piramides",
        "Coliseu",
        "Estatuas de marmore",
        "Castelos"
      ],
      correta: "Estatuas de marmore",
      comentario: "Gregos famosos por esculturas realistas.",
      tempoEstimado: 20,
      tags: ["grecia", "escultura"],
      habilidades: ["compreender-arte-grega"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_003",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou a Mona Lisa?",
      opcoes: [
        "Michelangelo",
        "Leonardo da Vinci",
        "Caravaggio",
        "Rembrandt"
      ],
      correta: "Leonardo da Vinci",
      comentario: "Leonardo da Vinci e artista renascentista italiano.",
      tempoEstimado: 25,
      tags: ["renascimento", "pintura"],
      habilidades: ["identificar-artistas-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_004",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que caracterizou o Renascimento?",
      opcoes: [
        "Foco em deuses",
        "Estudo da anatomia",
        "Arte abstrata",
        "Pintura primitiva"
      ],
      correta: "Estudo da anatomia",
      comentario: "Renascimento enfatizou ciencia e anatomia humana.",
      tempoEstimado: 30,
      tags: ["renascimento", "caracteristicas"],
      habilidades: ["compreender-renascimento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_005",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual artista barroco usava luz e sombra?",
      opcoes: [
        "Leonardo",
        "Caravaggio",
        "Michelangelo",
        "Rafael"
      ],
      correta: "Caravaggio",
      comentario: "Caravaggio mestre do chiaroscuro no Barroco.",
      tempoEstimado: 30,
      tags: ["barroco", "chiaroscuro"],
      habilidades: ["analisar-tecnicas-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_006",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O Barroco surgiu onde?",
      opcoes: [
        "Italia",
        "Franca",
        "Alemanha",
        "Espanha"
      ],
      correta: "Italia",
      comentario: "Barroco iniciou na Italia no seculo XVII.",
      tempoEstimado: 30,
      tags: ["barroco", "origem"],
      habilidades: ["compreender-origem-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_007",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra classica mostra uma mulher sorrindo?",
      opcoes: [
        "David",
        "Mona Lisa",
        "Ceia",
        "Capela Sistina"
      ],
      correta: "Mona Lisa",
      comentario: "Mona Lisa e retrato famoso de Leonardo.",
      tempoEstimado: 35,
      tags: ["renascimento", "obras"],
      habilidades: ["identificar-obras-classicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_008",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo veio apos o Renascimento?",
      opcoes: [
        "Antiguidade",
        "Barroco",
        "Romantismo",
        "Impressionismo"
      ],
      correta: "Barroco",
      comentario: "Barroco seguiu o Renascimento na historia da arte.",
      tempoEstimado: 40,
      tags: ["periodos", "sequencia"],
      habilidades: ["analisar-sequencia-periodos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_009",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como a arte egipcia influenciou outras?",
      opcoes: [
        "Pintura abstrata",
        "Esculturas monumentais",
        "Arte digital",
        "Fotografia"
      ],
      correta: "Esculturas monumentais",
      comentario: "Egipcios influenciaram monumentos em outras culturas.",
      tempoEstimado: 40,
      tags: ["influencias", "cultura"],
      habilidades: ["analisar-influencias-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_010",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que o Renascimento foi importante?",
      opcoes: [
        "Foco em mitos",
        "Revival da ciencia",
        "Arte primitiva",
        "Pintura religiosa apenas"
      ],
      correta: "Revival da ciencia",
      comentario: "Renascimento reviveu ideias cientificas e artisticas.",
      tempoEstimado: 40,
      tags: ["renascimento", "importancia"],
      habilidades: ["avaliar-impacto-renascimento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_011",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte romana famosa?",
      opcoes: [
        "Piramides",
        "Coliseu",
        "Partenon",
        "Esfinge"
      ],
      correta: "Coliseu",
      comentario: "Coliseu e anfiteatro romano para jogos.",
      tempoEstimado: 20,
      tags: ["roma", "arquitetura"],
      habilidades: ["identificar-obras-romanas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_012",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os maias criaram?",
      opcoes: [
        "Piramides",
        "Templos",
        "Ambos",
        "Nenhum"
      ],
      correta: "Ambos",
      comentario: "Maias construiram piramides e templos.",
      tempoEstimado: 20,
      tags: ["maias", "arquitetura"],
      habilidades: ["compreender-arte-maia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_013",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou a Capela Sistina?",
      opcoes: [
        "Leonardo",
        "Michelangelo",
        "Rafael",
        "Botticelli"
      ],
      correta: "Michelangelo",
      comentario: "Michelangelo pintou o teto da Capela Sistina.",
      tempoEstimado: 25,
      tags: ["renascimento", "capela-sistina"],
      habilidades: ["identificar-obras-michelangelo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_014",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica renascentista?",
      opcoes: [
        "Perspectiva",
        "Abstracao",
        "Cubismo",
        "Surrealismo"
      ],
      correta: "Perspectiva",
      comentario: "Perspectiva cria profundidade realista.",
      tempoEstimado: 30,
      tags: ["renascimento", "perspectiva"],
      habilidades: ["compreender-tecnicas-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_015",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual caracteristica barroca?",
      opcoes: [
        "Simplicidade",
        "Dramatismo",
        "Minimalismo",
        "Abstracao"
      ],
      correta: "Dramatismo",
      comentario: "Barroco usa dramatismo e movimento.",
      tempoEstimado: 30,
      tags: ["barroco", "dramatismo"],
      habilidades: ["analisar-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_016",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Quem foi Rembrandt?",
      opcoes: [
        "Pintor barroco",
        "Escultor grego",
        "Arquitet o romano",
        "Artista renascentista"
      ],
      correta: "Pintor barroco",
      comentario: "Rembrandt e mestre da pintura barroca holandesa.",
      tempoEstimado: 30,
      tags: ["barroco", "rembrandt"],
      habilidades: ["identificar-artistas-barrocos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_017",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra a Ultima Ceia?",
      opcoes: [
        "Mona Lisa",
        "David",
        "Ceia",
        "Pieta"
      ],
      correta: "Ceia",
      comentario: "A Ultima Ceia e pintura de Leonardo da Vinci.",
      tempoEstimado: 35,
      tags: ["renascimento", "ultima-ceia"],
      habilidades: ["identificar-obras-famosas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_018",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo antes do Renascimento?",
      opcoes: [
        "Idade Media",
        "Barroco",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Idade Media",
      comentario: "Idade Media precedeu o Renascimento.",
      tempoEstimado: 40,
      tags: ["periodos", "sequencia"],
      habilidades: ["analisar-cronologia-arte"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_019",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como a arte grega influenciou a romana?",
      opcoes: [
        "Copiando estatuas",
        "Criando novas formas",
        "Ignorando",
        "Destruindo"
      ],
      correta: "Copiando estatuas",
      comentario: "Romanos copiaram e adaptaram arte grega.",
      tempoEstimado: 40,
      tags: ["influencias", "grecia-roma"],
      habilidades: ["analisar-influencias-historicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_020",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que a perspectiva foi revolucionaria?",
      opcoes: [
        "Criou realismo",
        "Simplificou arte",
        "Removeu cores",
        "Focou em abstrato"
      ],
      correta: "Criou realismo",
      comentario: "Perspectiva fez arte parecer tridimensional.",
      tempoEstimado: 40,
      tags: ["renascimento", "perspectiva"],
      habilidades: ["avaliar-inovacoes-artisticas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_041",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte azteca?",
      opcoes: [
        "Piramides",
        "Templos com esculturas",
        "Castelos",
        "Igrejas"
      ],
      correta: "Templos com esculturas",
      comentario: "Astecas criavam templos monumentais com esculturas.",
      tempoEstimado: 20,
      tags: ["aztecas", "templos"],
      habilidades: ["identificar-arte-azteca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_042",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os gregos esculpiam?",
      opcoes: [
        "Deuses",
        "Animais modernos",
        "Carros",
        "Computadores"
      ],
      correta: "Deuses",
      comentario: "Gregos esculpiam estatuas de deuses e herois.",
      tempoEstimado: 20,
      tags: ["grecia", "esculturas"],
      habilidades: ["compreender-arte-grega"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_043",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou Mona Lisa?",
      opcoes: [
        "Leonardo",
        "Michelangelo",
        "Rafael",
        "Botticelli"
      ],
      correta: "Leonardo",
      comentario: "Mona Lisa e pintura famosa de Leonardo da Vinci.",
      tempoEstimado: 25,
      tags: ["renascimento", "mona-lisa"],
      habilidades: ["identificar-obras-leonardo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_044",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual ideia renascentista?",
      opcoes: [
        "Humanismo",
        "Misticismo",
        "Abstracao",
        "Surrealismo"
      ],
      correta: "Humanismo",
      comentario: "Humanismo valoriza o individuo e razao.",
      tempoEstimado: 30,
      tags: ["renascimento", "humanismo"],
      habilidades: ["compreender-ideias-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_045",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra de Bernini?",
      opcoes: [
        "David",
        "Apolo e Dafne",
        "Mona Lisa",
        "Capela Sistina"
      ],
      correta: "Apolo e Dafne",
      comentario: "Apolo e Dafne e escultura barroca de Bernini.",
      tempoEstimado: 30,
      tags: ["barroco", "bernini"],
      habilidades: ["analisar-obras-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_046",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Barroco usa?",
      opcoes: [
        "Simplicidade",
        "Dramatismo",
        "Minimalismo",
        "Abstracao"
      ],
      correta: "Dramatismo",
      comentario: "Barroco enfatiza emocao e movimento dramatico.",
      tempoEstimado: 30,
      tags: ["barroco", "dramatismo"],
      habilidades: ["compreender-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_047",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra ceia?",
      opcoes: [
        "Mona Lisa",
        "Ultima Ceia",
        "David",
        "Pieta"
      ],
      correta: "Ultima Ceia",
      comentario: "Ultima Ceia mostra Jesus com discipulos.",
      tempoEstimado: 35,
      tags: ["renascimento", "ultima-ceia"],
      habilidades: ["identificar-obras-famosas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_048",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo apos Barroco?",
      opcoes: [
        "Rococo",
        "Renascimento",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Rococo",
      comentario: "Rococo seguiu o Barroco com ornamentacao elaborada.",
      tempoEstimado: 40,
      tags: ["periodos", "rococo"],
      habilidades: ["analisar-cronologia-arte"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_049",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte refletia poder?",
      opcoes: [
        "Patroes ricos",
        "Pinturas simples",
        "Esculturas pequenas",
        "Desenhos rapidos"
      ],
      correta: "Patroes ricos",
      comentario: "Patroes encomendavam arte para mostrar poder.",
      tempoEstimado: 40,
      tags: ["influencias", "poder"],
      habilidades: ["analisar-influencias-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_050",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Michelangelo e importante?",
      opcoes: [
        "Pintura e escultura",
        "Musica",
        "Danca",
        "Teatro"
      ],
      correta: "Pintura e escultura",
      comentario: "Michelangelo mestre em pintura e escultura renascentista.",
      tempoEstimado: 40,
      tags: ["renascimento", "michelangelo"],
      habilidades: ["avaliar-importancia-artistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_051",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte inca?",
      opcoes: [
        "Piramides",
        "Machu Picchu",
        "Coliseu",
        "Partenon"
      ],
      correta: "Machu Picchu",
      comentario: "Machu Picchu e cidade inca com arquitetura avancada.",
      tempoEstimado: 20,
      tags: ["incas", "machu-picchu"],
      habilidades: ["identificar-arte-inca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_052",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os romanos pintavam?",
      opcoes: [
        "Paredes com afrescos",
        "Carros",
        "Computadores",
        "Aviões"
      ],
      correta: "Paredes com afrescos",
      comentario: "Romanos decoravam paredes com afrescos coloridos.",
      tempoEstimado: 20,
      tags: ["roma", "afrescos"],
      habilidades: ["compreender-arte-romana"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_053",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem criou Escola de Atenas?",
      opcoes: [
        "Leonardo",
        "Rafael",
        "Michelangelo",
        "Botticelli"
      ],
      correta: "Rafael",
      comentario: "Escola de Atenas e afresco de Rafael.",
      tempoEstimado: 25,
      tags: ["renascimento", "escola-atenas"],
      habilidades: ["identificar-obras-rafael"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_054",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica renascentista?",
      opcoes: [
        "Sfumato",
        "Impasto",
        "Pontilhismo",
        "Fresco"
      ],
      correta: "Sfumato",
      comentario: "Sfumato cria transicoes suaves de luz.",
      tempoEstimado: 30,
      tags: ["renascimento", "sfumato"],
      habilidades: ["compreender-tecnicas-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_055",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual pais barroco?",
      opcoes: [
        "Franca",
        "Holanda",
        "Espanha",
        "Italia"
      ],
      correta: "Espanha",
      comentario: "Espanha teve barroco com Velazquez e Murillo.",
      tempoEstimado: 30,
      tags: ["barroco", "espanha"],
      habilidades: ["analisar-origem-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_056",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Rubens pintava?",
      opcoes: [
        "Figuras dramaticas",
        "Naturezas mortas",
        "Abstrato",
        "Minimalista"
      ],
      correta: "Figuras dramaticas",
      comentario: "Rubens conhecido por figuras cheias de movimento.",
      tempoEstimado: 30,
      tags: ["barroco", "rubens"],
      habilidades: ["compreender-tecnicas-rubens"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_057",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra nascimento?",
      opcoes: [
        "Mona Lisa",
        "Nascimento de Venus",
        "David",
        "Pieta"
      ],
      correta: "Nascimento de Venus",
      comentario: "Nascimento de Venus mostra deusa emergindo do mar.",
      tempoEstimado: 35,
      tags: ["renascimento", "venus"],
      habilidades: ["identificar-elementos-obras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_058",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo entre Idade Media e Renascimento?",
      opcoes: [
        "Goticismo",
        "Barroco",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Goticismo",
      comentario: "Goticismo transicao entre Idade Media e Renascimento.",
      tempoEstimado: 40,
      tags: ["periodos", "goticismo"],
      habilidades: ["analisar-transicoes-periodos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_059",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte barroca refletia igreja?",
      opcoes: [
        "Contrarreforma",
        "Revolucao industrial",
        "Renascimento",
        "Modernismo"
      ],
      correta: "Contrarreforma",
      comentario: "Barroco ligado a Contrarreforma catolica.",
      tempoEstimado: 40,
      tags: ["influencias", "igreja"],
      habilidades: ["analisar-contexto-religioso"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_060",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Rafael e mestre?",
      opcoes: [
        "Harmonia composicional",
        "Cores vibrantes",
        "Esculturas grandes",
        "Musica"
      ],
      correta: "Harmonia composicional",
      comentario: "Rafael conhecido por harmonia perfeita em pinturas.",
      tempoEstimado: 40,
      tags: ["renascimento", "rafael"],
      habilidades: ["avaliar-legado-artistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_061",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte olmeca?",
      opcoes: [
        "Cabeças gigantes",
        "Piramides",
        "Templos",
        "Igrejas"
      ],
      correta: "Cabeças gigantes",
      comentario: "Olmecas criaram cabeças colossais de pedra.",
      tempoEstimado: 20,
      tags: ["olmecas", "cabecas"],
      habilidades: ["identificar-arte-olmeca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_062",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os etruscos criaram?",
      opcoes: [
        "Sarcofagos",
        "Piramides",
        "Coliseu",
        "Partenon"
      ],
      correta: "Sarcofagos",
      comentario: "Etruscos faziam sarcofagos decorados com relevos.",
      tempoEstimado: 20,
      tags: ["etruscos", "sarcofagos"],
      habilidades: ["compreender-arte-etrusca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_063",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou A Anunciação?",
      opcoes: [
        "Leonardo",
        "Da Vinci",
        "Rafael",
        "Botticelli"
      ],
      correta: "Da Vinci",
      comentario: "Leonardo da Vinci pintou A Anunciação.",
      tempoEstimado: 25,
      tags: ["renascimento", "anunciacao"],
      habilidades: ["identificar-obras-leonardo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_064",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica renascentista?",
      opcoes: [
        "Sfumato",
        "Impasto",
        "Pontilhismo",
        "Fresco"
      ],
      correta: "Sfumato",
      comentario: "Sfumato cria transicoes suaves de luz e sombra.",
      tempoEstimado: 30,
      tags: ["renascimento", "sfumato"],
      habilidades: ["compreender-tecnicas-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_065",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra de Rembrandt?",
      opcoes: [
        "Ronda Noturna",
        "Mona Lisa",
        "David",
        "Pieta"
      ],
      correta: "Ronda Noturna",
      comentario: "Ronda Noturna e pintura barroca de Rembrandt.",
      tempoEstimado: 30,
      tags: ["barroco", "rembrandt"],
      habilidades: ["analisar-obras-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_066",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Barroco flamengo?",
      opcoes: [
        "Rubens",
        "Caravaggio",
        "Bernini",
        "Velazquez"
      ],
      correta: "Rubens",
      comentario: "Rubens e mestre do Barroco flamengo.",
      tempoEstimado: 30,
      tags: ["barroco", "flamengo"],
      habilidades: ["compreender-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_067",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra Adão e Eva?",
      opcoes: [
        "Mona Lisa",
        "Criacao de Adão",
        "David",
        "Pieta"
      ],
      correta: "Criacao de Adão",
      comentario: "Criacao de Adão mostra Deus criando Adão.",
      tempoEstimado: 35,
      tags: ["renascimento", "adao"],
      habilidades: ["identificar-obras-famosas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_068",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo apos Renascimento?",
      opcoes: [
        "Maneirismo",
        "Barroco",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Maneirismo",
      comentario: "Maneirismo seguiu o Renascimento.",
      tempoEstimado: 40,
      tags: ["periodos", "maneirismo"],
      habilidades: ["analisar-cronologia-arte"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_069",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte refletia sociedade renascentista?",
      opcoes: [
        "Ciencia e razao",
        "Misticismo",
        "Abstracao",
        "Surrealismo"
      ],
      correta: "Ciencia e razao",
      comentario: "Renascimento valorizava ciencia e razao.",
      tempoEstimado: 40,
      tags: ["influencias", "sociedade"],
      habilidades: ["analisar-influencias-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_070",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Michelangelo e genio?",
      opcoes: [
        "Dominio multiplas artes",
        "Pintura so",
        "Escultura so",
        "Arquitetura so"
      ],
      correta: "Dominio multiplas artes",
      comentario: "Michelangelo mestre em pintura, escultura, arquitetura.",
      tempoEstimado: 40,
      tags: ["renascimento", "michelangelo"],
      habilidades: ["avaliar-importancia-artistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_071",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte minoica?",
      opcoes: [
        "Palacios",
        "Piramides",
        "Coliseu",
        "Partenon"
      ],
      correta: "Palacios",
      comentario: "Minoicos construiram palacios elaborados em Creta.",
      tempoEstimado: 20,
      tags: ["minoicos", "palacios"],
      habilidades: ["identificar-arte-minoica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_072",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os assirios criaram?",
      opcoes: [
        "Relevos em pedra",
        "Piramides",
        "Templos gregos",
        "Igrejas"
      ],
      correta: "Relevos em pedra",
      comentario: "Assirios famosos por relevos narrativos em pedra.",
      tempoEstimado: 20,
      tags: ["assirios", "relevos"],
      habilidades: ["compreender-arte-assiria"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_073",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou A Ultima Ceia?",
      opcoes: [
        "Leonardo",
        "Michelangelo",
        "Rafael",
        "Botticelli"
      ],
      correta: "Leonardo",
      comentario: "Leonardo da Vinci pintou A Ultima Ceia.",
      tempoEstimado: 25,
      tags: ["renascimento", "ultima-ceia"],
      habilidades: ["identificar-obras-leonardo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_074",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual ideia renascentista?",
      opcoes: [
        "Proporcao",
        "Misticismo",
        "Abstracao",
        "Surrealismo"
      ],
      correta: "Proporcao",
      comentario: "Renascimento enfatizava proporcao harmoniosa.",
      tempoEstimado: 30,
      tags: ["renascimento", "proporcao"],
      habilidades: ["compreender-ideias-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_075",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra de Velazquez?",
      opcoes: [
        "Meninas",
        "Mona Lisa",
        "David",
        "Pieta"
      ],
      correta: "Meninas",
      comentario: "Las Meninas e pintura barroca de Velazquez.",
      tempoEstimado: 30,
      tags: ["barroco", "velazquez"],
      habilidades: ["analisar-obras-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_076",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Barroco espanhol?",
      opcoes: [
        "Velazquez",
        "Rubens",
        "Caravaggio",
        "Bernini"
      ],
      correta: "Velazquez",
      comentario: "Velazquez e mestre do Barroco espanhol.",
      tempoEstimado: 30,
      tags: ["barroco", "espanhol"],
      habilidades: ["compreender-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_077",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra anjos musicais?",
      opcoes: [
        "Mona Lisa",
        "Capela Sistina",
        "David",
        "Pieta"
      ],
      correta: "Capela Sistina",
      comentario: "Capela Sistina tem afrescos com anjos e musicos.",
      tempoEstimado: 35,
      tags: ["renascimento", "capela-sistina"],
      habilidades: ["identificar-elementos-obras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_078",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo entre Barroco e Neoclassicismo?",
      opcoes: [
        "Rococo",
        "Renascimento",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Rococo",
      comentario: "Rococo transicao entre Barroco e Neoclassicismo.",
      tempoEstimado: 40,
      tags: ["periodos", "rococo"],
      habilidades: ["analisar-transicoes-periodos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_079",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte barroca refletia poder?",
      opcoes: [
        "Grandiosidade",
        "Simplicidade",
        "Abstracao",
        "Minimalismo"
      ],
      correta: "Grandiosidade",
      comentario: "Barroco usava grandiosidade para mostrar poder.",
      tempoEstimado: 40,
      tags: ["influencias", "poder"],
      habilidades: ["analisar-contexto-social"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_080",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Rafael e harmonioso?",
      opcoes: [
        "Equilibrio composicional",
        "Cores vibrantes",
        "Esculturas grandes",
        "Musica"
      ],
      correta: "Equilibrio composicional",
      comentario: "Rafael conhecido por equilibrio e harmonia.",
      tempoEstimado: 40,
      tags: ["renascimento", "rafael"],
      habilidades: ["avaliar-legado-artistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_081",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte persa? ",
      opcoes: [
        "Tapetes",
        "Piramides",
        "Coliseu",
        "Partenon"
      ],
      correta: "Tapetes",
      comentario: "Persas criavam tapetes ornamentados com padroes geometricos.",
      tempoEstimado: 20,
      tags: ["persas", "tapetes"],
      habilidades: ["identificar-arte-persa"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_082",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os fenicios criaram?",
      opcoes: [
        "Vidro colorido",
        "Piramides",
        "Templos gregos",
        "Igrejas"
      ],
      correta: "Vidro colorido",
      comentario: "Fenicios pioneiros no vidro colorido e mosaicos.",
      tempoEstimado: 20,
      tags: ["fenicios", "vidro"],
      habilidades: ["compreender-arte-fenicia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_083",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou Nascimento de Venus?",
      opcoes: [
        "Botticelli",
        "Leonardo",
        "Rafael",
        "Michelangelo"
      ],
      correta: "Botticelli",
      comentario: "Botticelli pintou Nascimento de Venus.",
      tempoEstimado: 25,
      tags: ["renascimento", "venus"],
      habilidades: ["identificar-obras-botticelli"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_084",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica renascentista?",
      opcoes: [
        "Fresco",
        "Impasto",
        "Pontilhismo",
        "Cubismo"
      ],
      correta: "Fresco",
      comentario: "Fresco e tecnica de pintura em parede molhada.",
      tempoEstimado: 30,
      tags: ["renascimento", "fresco"],
      habilidades: ["compreender-tecnicas-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_085",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra de Caravaggio?",
      opcoes: [
        "Vocacao de Sao Mateus",
        "Mona Lisa",
        "David",
        "Pieta"
      ],
      correta: "Vocacao de Sao Mateus",
      comentario: "Vocacao de Sao Mateus usa chiaroscuro dramatico.",
      tempoEstimado: 30,
      tags: ["barroco", "caravaggio"],
      habilidades: ["analisar-obras-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_086",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Barroco italiano?",
      opcoes: [
        "Bernini",
        "Rubens",
        "Velazquez",
        "Rembrandt"
      ],
      correta: "Bernini",
      comentario: "Bernini e mestre do Barroco italiano em escultura.",
      tempoEstimado: 30,
      tags: ["barroco", "italiano"],
      habilidades: ["compreender-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_087",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra Pieta?",
      opcoes: [
        "Mona Lisa",
        "David",
        "Pieta",
        "Ceia"
      ],
      correta: "Pieta",
      comentario: "Pieta mostra Maria com Jesus morto.",
      tempoEstimado: 35,
      tags: ["renascimento", "pieta"],
      habilidades: ["identificar-obras-famosas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_088",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo apos Barroco?",
      opcoes: [
        "Neoclassicismo",
        "Renascimento",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Neoclassicismo",
      comentario: "Neoclassicismo seguiu o Barroco.",
      tempoEstimado: 40,
      tags: ["periodos", "neoclassicismo"],
      habilidades: ["analisar-cronologia-arte"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_089",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte renascentista refletia humanismo?",
      opcoes: [
        "Foco no individuo",
        "Misticismo",
        "Abstracao",
        "Surrealismo"
      ],
      correta: "Foco no individuo",
      comentario: "Humanismo renascentista valorizava o individuo.",
      tempoEstimado: 40,
      tags: ["influencias", "humanismo"],
      habilidades: ["analisar-influencias-culturais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_090",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Botticelli e importante?",
      opcoes: [
        "Elegancia e graciosidade",
        "Cores vibrantes",
        "Esculturas grandes",
        "Musica"
      ],
      correta: "Elegancia e graciosidade",
      comentario: "Botticelli conhecido por figuras elegantes.",
      tempoEstimado: 40,
      tags: ["renascimento", "botticelli"],
      habilidades: ["avaliar-legado-artistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_091",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual arte hitita?",
      opcoes: [
        "Relevos em rocha",
        "Piramides",
        "Coliseu",
        "Partenon"
      ],
      correta: "Relevos em rocha",
      comentario: "Hititas criavam relevos narrativos em rocha.",
      tempoEstimado: 20,
      tags: ["hititas", "relevos"],
      habilidades: ["identificar-arte-hitita"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_092",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "arte-antiga",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que os sumérios criavam?",
      opcoes: [
        "Zigurates",
        "Piramides",
        "Templos gregos",
        "Igrejas"
      ],
      correta: "Zigurates",
      comentario: "Sumérios construiram zigurates como templos.",
      tempoEstimado: 20,
      tags: ["sumérios", "zigurates"],
      habilidades: ["compreender-arte-sumeria"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_093",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Quem pintou Primavera?",
      opcoes: [
        "Botticelli",
        "Leonardo",
        "Rafael",
        "Michelangelo"
      ],
      correta: "Botticelli",
      comentario: "Botticelli pintou Primavera.",
      tempoEstimado: 25,
      tags: ["renascimento", "primavera"],
      habilidades: ["identificar-obras-botticelli"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_094",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual ideia renascentista?",
      opcoes: [
        "Anatomia",
        "Misticismo",
        "Abstracao",
        "Surrealismo"
      ],
      correta: "Anatomia",
      comentario: "Renascimento estudava anatomia para realismo.",
      tempoEstimado: 30,
      tags: ["renascimento", "anatomia"],
      habilidades: ["compreender-ideias-renascentistas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_095",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra de Murillo?",
      opcoes: [
        "Menino com cachorro",
        "Mona Lisa",
        "David",
        "Pieta"
      ],
      correta: "Menino com cachorro",
      comentario: "Murillo pintava cenas cotidianas no Barroco espanhol.",
      tempoEstimado: 30,
      tags: ["barroco", "murillo"],
      habilidades: ["analisar-obras-barrocas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_096",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "barroco",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Barroco holandes?",
      opcoes: [
        "Rembrandt",
        "Rubens",
        "Caravaggio",
        "Bernini"
      ],
      correta: "Rembrandt",
      comentario: "Rembrandt e mestre do Barroco holandes.",
      tempoEstimado: 30,
      tags: ["barroco", "holandes"],
      habilidades: ["compreender-estilo-barroco"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_097",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "classicos-infantis",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual obra mostra David?",
      opcoes: [
        "Mona Lisa",
        "David",
        "Pieta",
        "Ceia"
      ],
      correta: "David",
      comentario: "David e escultura de Michelangelo.",
      tempoEstimado: 35,
      tags: ["renascimento", "david"],
      habilidades: ["identificar-obras-famosas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_098",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "periodos-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual periodo entre Antiguidade e Renascimento?",
      opcoes: [
        "Idade Media",
        "Barroco",
        "Antiguidade",
        "Moderno"
      ],
      correta: "Idade Media",
      comentario: "Idade Media entre Antiguidade e Renascimento.",
      tempoEstimado: 40,
      tags: ["periodos", "idade-media"],
      habilidades: ["analisar-cronologia-arte"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_099",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "influencias-culturais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como arte barroca refletia Contrarreforma?",
      opcoes: [
        "Emocao religiosa",
        "Abstracao",
        "Minimalismo",
        "Surrealismo"
      ],
      correta: "Emocao religiosa",
      comentario: "Barroco usava emocao para Contrarreforma.",
      tempoEstimado: 40,
      tags: ["influencias", "contrarreforma"],
      habilidades: ["analisar-contexto-religioso"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "hac_100",
      serie: [1],
      materia: "Artes",
      topico: "Historia da Arte Classica",
      subtopico: "renascimento",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que Caravaggio e inovador?",
      opcoes: [
        "Uso de luz e sombra",
        "Cores vibrantes",
        "Esculturas grandes",
        "Musica"
      ],
      correta: "Uso de luz e sombra",
      comentario: "Caravaggio inovou com chiaroscuro dramatico.",
      tempoEstimado: 40,
      tags: ["renascimento", "caravaggio"],
      habilidades: ["avaliar-inovacoes-artisticas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    }
  ]
};
