export const porcentagem = {
  id: "matematica_porcentagem",
  materia: "Matemática",
  serie: [1],
  topico: "Porcentagem",

  metadados: {
    disciplinaId: "matematica",
    base: "ESCOLAR",
    eixo: "Numeros",
    frente: "Proporcionalidade",
    searchAliases: [
      "percentual",
      "taxa percentual",
      "por cento"
    ],
    subtopicosBase: [
      "Conceito",
      "Conversao percentual fracao decimal",
      "Calculo direto",
      "Aumento percentual",
      "Desconto percentual",
      "Porcentagem de porcentagem",
      "Variacao percentual",
      "Equivalencia percentual"
    ],
    habilidadesBase: [
      "identificar porcentagem",
      "converter percentual",
      "calcular porcentagem",
      "resolver problemas de aumento e desconto"
    ]
  },

  questoes: [

    {
      id: "pc_001",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Conceito",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "O que significa 25%?",
      opcoes: ["25 de 100", "25 de 10", "25 de 1000", "1 de 25"],
      correta: "25 de 100",
      comentario: "Porcentagem representa partes de 100.",
      tempoEstimado: 15,
      tags: ["conceito"],
      habilidades: ["identificar porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_002",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Conversao percentual fracao decimal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "50% em forma decimal é:",
      opcoes: ["0,5", "5", "0,05", "50"],
      correta: "0,5",
      comentario: "Divide-se por 100.",
      tempoEstimado: 15,
      tags: ["conversao"],
      habilidades: ["converter percentual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_003",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Calculo direto",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Quanto é 10% de 200?",
      opcoes: ["20", "10", "2000", "2"],
      correta: "20",
      comentario: "10% de 200 = 200 ÷ 10.",
      tempoEstimado: 20,
      tags: ["calculo"],
      habilidades: ["calcular porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_004",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Conversao percentual fracao decimal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "25% corresponde a:",
      opcoes: ["0,25", "2,5", "0,025", "25"],
      correta: "0,25",
      comentario: "25 ÷ 100 = 0,25.",
      tempoEstimado: 15,
      tags: ["conversao"],
      habilidades: ["converter percentual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_005",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Calculo direto",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "5% de 100 é:",
      opcoes: ["5", "50", "0,5", "500"],
      correta: "5",
      comentario: "5% de 100 = 5.",
      tempoEstimado: 15,
      tags: ["calculo"],
      habilidades: ["calcular porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_006",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Conceito",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "100% representa:",
      opcoes: ["todo o valor", "metade", "um quarto", "dez por cento"],
      correta: "todo o valor",
      comentario: "100% equivale ao total.",
      tempoEstimado: 15,
      tags: ["conceito"],
      habilidades: ["identificar porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_007",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Calculo direto",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "20% de 50 é:",
      opcoes: ["10", "5", "20", "2"],
      correta: "10",
      comentario: "20% = 0,2 → 0,2 × 50.",
      tempoEstimado: 20,
      tags: ["calculo"],
      habilidades: ["calcular porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_008",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Conversao percentual fracao decimal",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "10% em forma decimal:",
      opcoes: ["0,1", "1", "0,01", "10"],
      correta: "0,1",
      comentario: "10 ÷ 100 = 0,1.",
      tempoEstimado: 15,
      tags: ["conversao"],
      habilidades: ["converter percentual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_009",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Calculo direto",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "15% de 200 é:",
      opcoes: ["30", "20", "15", "300"],
      correta: "30",
      comentario: "0,15 × 200 = 30.",
      tempoEstimado: 20,
      tags: ["calculo"],
      habilidades: ["calcular porcentagem"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },

    {
      id: "pc_010",
      serie: [1],
      materia: "Matemática",
      topico: "Porcentagem",
      subtopico: "Aumento percentual",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Um produto custa 100 reais e aumenta 10%. Novo valor:",
      opcoes: ["110", "100", "90", "120"],
      correta: "110",
      comentario: "10% de 100 = 10 → 100 + 10.",
      tempoEstimado: 25,
      tags: ["aumento"],
      habilidades: ["resolver aumento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    }

  ]
}