export const elementosVisuais = {
  id: "artes_elementos_visuais",
  materia: "Artes",
  serie: [1],
  topico: "Elementos Visuais",
  metadados: {
    disciplinaId: "artes",
    base: "ESCOLAR",
    eixo: "Artes",
    frente: "Linguagem visual",
    subtopicosBase: ["linha-forma", "cor-luz", "textura-volume", "composicao-equilibrio", "materiais-basicos", "expressao-visual"],
    habilidadesBase: ["identificar-elementos-visuais", "compreender-conceitos", "analisar-composicao", "expressar-visualmente"],
    searchAliases: ["elementos visuais", "arte visual basica"],
    auditado: false
  },
  questoes: [
    {
      id: "ev_001",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e uma linha em arte?",
      opcoes: [
        "Uma cor",
        "Um traco que conecta pontos",
        "Uma forma",
        "Uma textura"
      ],
      correta: "Um traco que conecta pontos",
      comentario: "Linha e o elemento basico que forma formas e desenhos.",
      tempoEstimado: 20,
      tags: ["linha", "elementos-visuais"],
      habilidades: ["identificar-elementos-visuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_002",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual tipo de linha e reta?",
      opcoes: [
        "Curva",
        "Ziguezague",
        "Reta",
        "Onda"
      ],
      correta: "Reta",
      comentario: "Linha reta vai de um ponto a outro sem curvas.",
      tempoEstimado: 20,
      tags: ["linha-reta", "elementos-visuais"],
      habilidades: ["identificar-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_003",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor primaria?",
      opcoes: [
        "Verde",
        "Azul",
        "Roxo",
        "Laranja"
      ],
      correta: "Azul",
      comentario: "Cores primarias sao azul, vermelho e amarelo.",
      tempoEstimado: 25,
      tags: ["cor-primaria", "elementos-visuais"],
      habilidades: ["identificar-cores-primarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_004",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que acontece ao misturar azul e amarelo?",
      opcoes: [
        "Verde",
        "Roxo",
        "Laranja",
        "Rosa"
      ],
      correta: "Verde",
      comentario: "Mistura de azul e amarelo resulta em verde.",
      tempoEstimado: 30,
      tags: ["mistura-cores", "elementos-visuais"],
      habilidades: ["compreender-mistura-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_005",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que e textura em arte?",
      opcoes: [
        "Cor da obra",
        "Superficie da obra",
        "Forma da obra",
        "Luz da obra"
      ],
      correta: "Superficie da obra",
      comentario: "Textura refere-se a sensacao da superficie, lisa ou rugosa.",
      tempoEstimado: 30,
      tags: ["textura", "elementos-visuais"],
      habilidades: ["compreender-textura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_006",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual elemento da arte cria profundidade?",
      opcoes: [
        "Linha",
        "Volume",
        "Cor",
        "Textura"
      ],
      correta: "Volume",
      comentario: "Volume da sensacao de tridimensionalidade.",
      tempoEstimado: 30,
      tags: ["volume", "elementos-visuais"],
      habilidades: ["compreender-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_007",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "O que e composicao em arte?",
      opcoes: [
        "Arranjo de elementos",
        "Cor da tela",
        "Tipo de pincel",
        "Tamanho da obra"
      ],
      correta: "Arranjo de elementos",
      comentario: "Composicao e como os elementos sao organizados na obra.",
      tempoEstimado: 35,
      tags: ["composicao", "elementos-visuais"],
      habilidades: ["compreender-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_008",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual material para escultura?",
      opcoes: [
        "Tinta",
        "Argila",
        "Papel",
        "Lapis"
      ],
      correta: "Argila",
      comentario: "Argila e moldavel para criar formas tridimensionais.",
      tempoEstimado: 40,
      tags: ["materiais", "escultura"],
      habilidades: ["analisar-materiais-escultura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_009",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como expressar alegria em arte?",
      opcoes: [
        "Cores escuras",
        "Linhas curvas suaves",
        "Cores vibrantes",
        "Formas geometricas rigidas"
      ],
      correta: "Cores vibrantes",
      comentario: "Cores vibrantes transmitem energia e alegria.",
      tempoEstimado: 40,
      tags: ["expressao", "emocoes"],
      habilidades: ["analisar-expressao-visual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_010",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Qual linha cria movimento?",
      opcoes: [
        "Reta horizontal",
        "Curva dinamica",
        "Vertical estatica",
        "Diagonal rigida"
      ],
      correta: "Curva dinamica",
      comentario: "Linhas curvas sugerem movimento e fluidez.",
      tempoEstimado: 40,
      tags: ["linha-movimento", "elementos-visuais"],
      habilidades: ["avaliar-efeito-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_011",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor secundaria?",
      opcoes: [
        "Azul",
        "Verde",
        "Branco",
        "Preto"
      ],
      correta: "Verde",
      comentario: "Verde e cor secundaria, feita de azul e amarelo.",
      tempoEstimado: 20,
      tags: ["cor-secundaria", "elementos-visuais"],
      habilidades: ["identificar-cores-secundarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_012",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e luz em arte?",
      opcoes: [
        "Cor escura",
        "Fonte de iluminacao",
        "Tipo de pincel",
        "Forma geometrica"
      ],
      correta: "Fonte de iluminacao",
      comentario: "Luz cria sombras e destaca formas.",
      tempoEstimado: 20,
      tags: ["luz", "elementos-visuais"],
      habilidades: ["compreender-luz"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_013",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo de textura rugosa?",
      opcoes: [
        "Vidro",
        "Areia",
        "Seda",
        "Agua"
      ],
      correta: "Areia",
      comentario: "Areia tem superficie rugosa ao toque.",
      tempoEstimado: 25,
      tags: ["textura-rugosa", "elementos-visuais"],
      habilidades: ["identificar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_014",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que e equilibrio simetrico?",
      opcoes: [
        "Elementos iguais dos lados",
        "Elementos diferentes",
        "Foco no centro",
        "Movimento diagonal"
      ],
      correta: "Elementos iguais dos lados",
      comentario: "Equilibrio simetrico divide a obra igualmente.",
      tempoEstimado: 30,
      tags: ["equilibrio", "composicao"],
      habilidades: ["compreender-equilibrio"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_015",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual material para pintura a oleo?",
      opcoes: [
        "Aguarela",
        "Tinta oleo",
        "Giz de cera",
        "Carvao"
      ],
      correta: "Tinta oleo",
      comentario: "Tinta a oleo e usada em telas para pintura duradoura.",
      tempoEstimado: 30,
      tags: ["materiais", "pintura"],
      habilidades: ["compreender-materiais-pintura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_016",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como expressar tristeza em arte?",
      opcoes: [
        "Cores quentes",
        "Linhas retas",
        "Cores frias e curvas",
        "Formas grandes"
      ],
      correta: "Cores frias e curvas",
      comentario: "Cores frias e linhas suaves transmitem tristeza.",
      tempoEstimado: 30,
      tags: ["expressao", "tristeza"],
      habilidades: ["compreender-expressao-emocional"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_017",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual forma geometrica?",
      opcoes: [
        "Nuvem",
        "Quadrado",
        "Folha",
        "Pessoa"
      ],
      correta: "Quadrado",
      comentario: "Quadrado e forma geometrica com lados iguais.",
      tempoEstimado: 35,
      tags: ["forma-geometrica", "elementos-visuais"],
      habilidades: ["identificar-formas-geometricas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_018",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como a luz cria sombra?",
      opcoes: [
        "Bloqueando cor",
        "Projetando area escura",
        "Mudando forma",
        "Adicionando textura"
      ],
      correta: "Projetando area escura",
      comentario: "Luz cria sombras onde e bloqueada.",
      tempoEstimado: 40,
      tags: ["luz-sombra", "elementos-visuais"],
      habilidades: ["analisar-efeito-luz"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_019",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para volume em desenho?",
      opcoes: [
        "Hachuras",
        "Pontilhismo",
        "Colagem",
        "Spray"
      ],
      correta: "Hachuras",
      comentario: "Hachuras criam volume com linhas paralelas.",
      tempoEstimado: 40,
      tags: ["volume", "hachuras"],
      habilidades: ["analisar-tecnicas-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_020",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Como avaliar composicao?",
      opcoes: [
        "Contar cores",
        "Ver harmonia visual",
        "Medir tamanho",
        "Ouvir som"
      ],
      correta: "Ver harmonia visual",
      comentario: "Composicao boa tem harmonia e foco.",
      tempoEstimado: 40,
      tags: ["composicao", "harmonia"],
      habilidades: ["avaliar-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_022",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e uma forma?",
      opcoes: [
        "Cor",
        "Espaco fechado por linhas",
        "Textura",
        "Volume"
      ],
      correta: "Espaco fechado por linhas",
      comentario: "Forma e area delimitada por linhas.",
      tempoEstimado: 20,
      tags: ["forma", "elementos-visuais"],
      habilidades: ["compreender-forma"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_023",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor primaria e amarelo?",
      opcoes: [
        "Sim",
        "Nao",
        "Secundaria",
        "Terciaria"
      ],
      correta: "Sim",
      comentario: "Amarelo e cor primaria basica.",
      tempoEstimado: 25,
      tags: ["cor-primaria", "amarelo"],
      habilidades: ["identificar-cores-primarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_024",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que acontece ao misturar vermelho e azul?",
      opcoes: [
        "Verde",
        "Roxo",
        "Laranja",
        "Marrom"
      ],
      correta: "Roxo",
      comentario: "Mistura de vermelho e azul resulta em roxo.",
      tempoEstimado: 30,
      tags: ["mistura-cores", "roxo"],
      habilidades: ["compreender-mistura-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_025",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual textura e lisa?",
      opcoes: [
        "Papel areia",
        "Vidro",
        "Tecido",
        "Madeira"
      ],
      correta: "Vidro",
      comentario: "Vidro tem superficie lisa ao toque.",
      tempoEstimado: 30,
      tags: ["textura-lisa", "elementos-visuais"],
      habilidades: ["identificar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_026",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar volume em pintura?",
      opcoes: [
        "Usando sombras",
        "Pintando plano",
        "Ignorando luz",
        "Cores iguais"
      ],
      correta: "Usando sombras",
      comentario: "Sombras criam ilusao de volume.",
      tempoEstimado: 30,
      tags: ["volume", "sombras"],
      habilidades: ["compreender-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_027",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "O que e ponto de fuga em composicao?",
      opcoes: [
        "Centro da obra",
        "Linha de horizonte",
        "Ponto onde linhas convergem",
        "Cor principal"
      ],
      correta: "Ponto onde linhas convergem",
      comentario: "Ponto de fuga cria profundidade.",
      tempoEstimado: 35,
      tags: ["composicao", "ponto-fuga"],
      habilidades: ["compreender-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_028",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual material para gravura?",
      opcoes: [
        "Tinta",
        "Placa de metal",
        "Argila",
        "Tecido"
      ],
      correta: "Placa de metal",
      comentario: "Gravura usa placas para imprimir imagens.",
      tempoEstimado: 40,
      tags: ["materiais", "gravura"],
      habilidades: ["analisar-materiais-gravura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_029",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como expressar raiva em composicao?",
      opcoes: [
        "Linhas suaves",
        "Cores quentes e angulos",
        "Formas redondas",
        "Espaco vazio"
      ],
      correta: "Cores quentes e angulos",
      comentario: "Angulos e cores quentes transmitem raiva.",
      tempoEstimado: 40,
      tags: ["expressao", "raiva"],
      habilidades: ["analisar-expressao-visual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_030",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Qual efeito de linhas diagonais?",
      opcoes: [
        "Calma",
        "Tensao",
        "Estabilidade",
        "Repouso"
      ],
      correta: "Tensao",
      comentario: "Linhas diagonais criam dinamismo e tensao.",
      tempoEstimado: 40,
      tags: ["linha-diagonal", "efeito"],
      habilidades: ["avaliar-efeito-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_031",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor e quente?",
      opcoes: [
        "Azul",
        "Vermelho",
        "Verde",
        "Roxo"
      ],
      correta: "Vermelho",
      comentario: "Vermelho e cor quente, associada a fogo.",
      tempoEstimado: 20,
      tags: ["cor-quente", "elementos-visuais"],
      habilidades: ["identificar-temperatura-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_032",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e sombra em arte?",
      opcoes: [
        "Area clara",
        "Area escura",
        "Cor primaria",
        "Forma geometrica"
      ],
      correta: "Area escura",
      comentario: "Sombra e area sem luz direta.",
      tempoEstimado: 20,
      tags: ["sombra", "elementos-visuais"],
      habilidades: ["compreender-sombra"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_033",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo de volume?",
      opcoes: [
        "Linha",
        "Esfera",
        "Cor",
        "Textura"
      ],
      correta: "Esfera",
      comentario: "Esfera e forma tridimensional com volume.",
      tempoEstimado: 25,
      tags: ["volume", "esfera"],
      habilidades: ["identificar-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_034",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que e ritmo em composicao?",
      opcoes: [
        "Repeticao de elementos",
        "Cor unica",
        "Forma grande",
        "Luz forte"
      ],
      correta: "Repeticao de elementos",
      comentario: "Ritmo cria movimento visual por repeticao.",
      tempoEstimado: 30,
      tags: ["ritmo", "composicao"],
      habilidades: ["compreender-ritmo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_035",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual material para aquarela?",
      opcoes: [
        "Oleo",
        "Aguarela",
        "Acetato",
        "Metal"
      ],
      correta: "Aguarela",
      comentario: "Aguarela e tinta diluida em agua para papel.",
      tempoEstimado: 30,
      tags: ["materiais", "aquarela"],
      habilidades: ["compreender-materiais-aquarela"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_036",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como expressar paz em arte?",
      opcoes: [
        "Cores frias e horizontais",
        "Angulos agudos",
        "Cores vibrantes",
        "Linhas verticais"
      ],
      correta: "Cores frias e horizontais",
      comentario: "Horizontais e frias transmitem calma e paz.",
      tempoEstimado: 30,
      tags: ["expressao", "paz"],
      habilidades: ["compreender-expressao-emocional"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_037",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual forma organica?",
      opcoes: [
        "Circulo",
        "Folha",
        "Triangulo",
        "Quadrado"
      ],
      correta: "Folha",
      comentario: "Folha e forma organica, natural.",
      tempoEstimado: 35,
      tags: ["forma-organica", "elementos-visuais"],
      habilidades: ["identificar-formas-organicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_038",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como a luz afeta cor?",
      opcoes: [
        "Muda intensidade",
        "Remove forma",
        "Adiciona textura",
        "Cria volume so"
      ],
      correta: "Muda intensidade",
      comentario: "Luz altera brilho e saturacao das cores.",
      tempoEstimado: 40,
      tags: ["luz-cor", "elementos-visuais"],
      habilidades: ["analisar-efeito-luz-cor"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_039",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para textura em pintura?",
      opcoes: [
        "Impasto",
        "Pontilhismo",
        "Sfumato",
        "Fresco"
      ],
      correta: "Impasto",
      comentario: "Impasto cria textura espessa com tinta.",
      tempoEstimado: 40,
      tags: ["textura", "impasto"],
      habilidades: ["analisar-tecnicas-textura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_040",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Como avaliar harmonia?",
      opcoes: [
        "Ver se cores combinam",
        "Contar linhas",
        "Medir tempo",
        "Ouvir musica"
      ],
      correta: "Ver se cores combinam",
      comentario: "Harmonia visual vem de elementos equilibrados.",
      tempoEstimado: 40,
      tags: ["harmonia", "composicao"],
      habilidades: ["avaliar-harmonia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_041",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual linha e reta?",
      opcoes: [
        "Curva",
        "Reta",
        "Zigzag",
        "Onda"
      ],
      correta: "Reta",
      comentario: "Linha reta vai em direcao constante.",
      tempoEstimado: 20,
      tags: ["linha", "reta"],
      habilidades: ["identificar-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_042",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Forma geometrica basica?",
      opcoes: [
        "Circulo",
        "Nuvem",
        "Folha",
        "Montanha"
      ],
      correta: "Circulo",
      comentario: "Circulo e forma geometrica perfeita.",
      tempoEstimado: 20,
      tags: ["forma", "geometrica"],
      habilidades: ["diferenciar-formas-geometricas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_043",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Cor primaria?",
      opcoes: [
        "Vermelho",
        "Rosa",
        "Laranja",
        "Roxo"
      ],
      correta: "Vermelho",
      comentario: "Vermelho e cor primaria basica.",
      tempoEstimado: 25,
      tags: ["cor", "primaria"],
      habilidades: ["identificar-cores-primarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_044",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como misturar azul e amarelo?",
      opcoes: [
        "Verde",
        "Roxo",
        "Laranja",
        "Rosa"
      ],
      correta: "Verde",
      comentario: "Azul e amarelo fazem verde.",
      tempoEstimado: 30,
      tags: ["mistura", "cores"],
      habilidades: ["compreender-mistura-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_045",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Textura rugosa?",
      opcoes: [
        "Lisa",
        "Rugosa",
        "Macia",
        "Sedosa"
      ],
      correta: "Rugosa",
      comentario: "Rugosa significa superficie irregular.",
      tempoEstimado: 30,
      tags: ["textura", "rugosa"],
      habilidades: ["analisar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_046",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar textura em pintura?",
      opcoes: [
        "Usando pincel grosso",
        "Pintando liso",
        "Usando agua",
        "Secando rapido"
      ],
      correta: "Usando pincel grosso",
      comentario: "Pincel grosso cria relevo e textura.",
      tempoEstimado: 30,
      tags: ["textura", "pintura"],
      habilidades: ["compreender-tecnicas-textura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_047",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Equilibrio simetrico?",
      opcoes: [
        "Partes iguais",
        "Partes diferentes",
        "Caotico",
        "Desequilibrado"
      ],
      correta: "Partes iguais",
      comentario: "Equilibrio simetrico tem partes balanceadas.",
      tempoEstimado: 35,
      tags: ["equilibrio", "simetrico"],
      habilidades: ["aplicar-principios-equilibrio"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_048",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "perspectiva-profundidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Perspectiva linear usa?",
      opcoes: [
        "Linhas convergentes",
        "Cores",
        "Sombras",
        "Texturas"
      ],
      correta: "Linhas convergentes",
      comentario: "Linhas convergentes criam ilusao de profundidade.",
      tempoEstimado: 40,
      tags: ["perspectiva", "linear"],
      habilidades: ["analisar-perspectiva"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_049",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "luz-sombra",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como luz cria sombra?",
      opcoes: [
        "Bloqueando luz",
        "Adicionando cor",
        "Mudando forma",
        "Aumentando tamanho"
      ],
      correta: "Bloqueando luz",
      comentario: "Sombra ocorre quando luz e bloqueada.",
      tempoEstimado: 40,
      tags: ["luz", "sombra"],
      habilidades: ["analisar-efeitos-luz"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_050",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "volume-massa",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Volume em escultura?",
      opcoes: [
        "Espaco ocupado",
        "Cor usada",
        "Movimento",
        "Textura"
      ],
      correta: "Espaco ocupado",
      comentario: "Volume e o espaco tridimensional ocupado.",
      tempoEstimado: 40,
      tags: ["volume", "escultura"],
      habilidades: ["avaliar-elementos-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_051",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Linha curva?",
      opcoes: [
        "Reta",
        "Curva",
        "Quebrada",
        "Pontilhada"
      ],
      correta: "Curva",
      comentario: "Linha curva segue arco suave.",
      tempoEstimado: 20,
      tags: ["linha", "curva"],
      habilidades: ["identificar-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_052",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Forma organica?",
      opcoes: [
        "Quadrado",
        "Folha",
        "Triangulo",
        "Circulo"
      ],
      correta: "Folha",
      comentario: "Folha e forma organica natural.",
      tempoEstimado: 20,
      tags: ["forma", "organica"],
      habilidades: ["diferenciar-formas-organicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_053",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Cor secundaria?",
      opcoes: [
        "Azul",
        "Verde",
        "Branco",
        "Preto"
      ],
      correta: "Verde",
      comentario: "Verde e cor secundaria de azul e amarelo.",
      tempoEstimado: 25,
      tags: ["cor", "secundaria"],
      habilidades: ["identificar-cores-secundarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_054",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar tom escuro?",
      opcoes: [
        "Adicionando branco",
        "Adicionando preto",
        "Adicionando agua",
        "Secando"
      ],
      correta: "Adicionando preto",
      comentario: "Adicionar preto escurece a cor.",
      tempoEstimado: 30,
      tags: ["tom", "escuro"],
      habilidades: ["compreender-tons-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_055",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Textura visual?",
      opcoes: [
        "Sentida pelo tato",
        "Vista nos olhos",
        "Ouvida",
        "Cheirada"
      ],
      correta: "Vista nos olhos",
      comentario: "Textura visual e percebida pela vista.",
      tempoEstimado: 30,
      tags: ["textura", "visual"],
      habilidades: ["analisar-texturas-visuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_056",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como simular textura em desenho?",
      opcoes: [
        "Usando linhas",
        "Pintando solido",
        "Usando uma cor",
        "Deixando em branco"
      ],
      correta: "Usando linhas",
      comentario: "Linhas podem simular textura.",
      tempoEstimado: 30,
      tags: ["textura", "desenho"],
      habilidades: ["compreender-simulacao-textura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_057",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Equilibrio assimetrico?",
      opcoes: [
        "Partes iguais",
        "Partes diferentes mas balanceadas",
        "Caotico",
        "Simetrico"
      ],
      correta: "Partes diferentes mas balanceadas",
      comentario: "Equilibrio assimetrico usa pesos visuais diferentes.",
      tempoEstimado: 35,
      tags: ["equilibrio", "assimetrico"],
      habilidades: ["aplicar-equilibrio-assimetrico"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_058",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "perspectiva-profundidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Perspectiva atmosferica usa?",
      opcoes: [
        "Cores desbotadas",
        "Linhas retas",
        "Sombras",
        "Texturas"
      ],
      correta: "Cores desbotadas",
      comentario: "Cores desbotadas criam profundidade atmosferica.",
      tempoEstimado: 40,
      tags: ["perspectiva", "atmosferica"],
      habilidades: ["analisar-perspectiva-atmosferica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_059",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "luz-sombra",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Chiaroscuro e?",
      opcoes: [
        "Tecnica de luz e sombra",
        "Tipo de cor",
        "Forma geometrica",
        "Textura"
      ],
      correta: "Tecnica de luz e sombra",
      comentario: "Chiaroscuro usa contrastes de luz e sombra.",
      tempoEstimado: 40,
      tags: ["chiaroscuro", "luz-sombra"],
      habilidades: ["analisar-tecnicas-luz"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_060",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "movimento-dinamismo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Como sugerir movimento?",
      opcoes: [
        "Linhas diagonais",
        "Formas estaticas",
        "Cores escuras",
        "Texturas lisas"
      ],
      correta: "Linhas diagonais",
      comentario: "Linhas diagonais sugerem movimento e energia.",
      tempoEstimado: 40,
      tags: ["movimento", "linhas"],
      habilidades: ["avaliar-elementos-movimento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_061",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Linha horizontal?",
      opcoes: [
        "Para cima",
        "Esquerda direita",
        "Diagonal",
        "Curva"
      ],
      correta: "Esquerda direita",
      comentario: "Linha horizontal vai da esquerda para direita.",
      tempoEstimado: 20,
      tags: ["linha", "horizontal"],
      habilidades: ["identificar-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_062",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Forma triangular?",
      opcoes: [
        "Tres lados",
        "Quatro lados",
        "Cinco lados",
        "Redonda"
      ],
      correta: "Tres lados",
      comentario: "Triangulo tem tres lados e tres angulos.",
      tempoEstimado: 20,
      tags: ["forma", "triangular"],
      habilidades: ["diferenciar-formas-geometricas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_063",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Cor quente?",
      opcoes: [
        "Azul",
        "Vermelho",
        "Verde",
        "Roxo"
      ],
      correta: "Vermelho",
      comentario: "Cores quentes incluem vermelho, laranja, amarelo.",
      tempoEstimado: 25,
      tags: ["cor", "quente"],
      habilidades: ["identificar-temperaturas-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_064",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar sombra?",
      opcoes: [
        "Adicionando luz",
        "Bloqueando luz",
        "Mudando cor",
        "Aumentando tamanho"
      ],
      correta: "Bloqueando luz",
      comentario: "Sombra ocorre quando luz e bloqueada por objeto.",
      tempoEstimado: 30,
      tags: ["sombra", "luz"],
      habilidades: ["compreender-efeitos-luz"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_065",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Textura lisa?",
      opcoes: [
        "Superficie plana",
        "Superficie rugosa",
        "Superficie irregular",
        "Superficie pontuda"
      ],
      correta: "Superficie plana",
      comentario: "Lisa significa sem irregularidades.",
      tempoEstimado: 30,
      tags: ["textura", "lisa"],
      habilidades: ["analisar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_066",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como simular textura rugosa?",
      opcoes: [
        "Pintando suavemente",
        "Usando pincel grosso",
        "Usando cores claras",
        "Deixando seco"
      ],
      correta: "Usando pincel grosso",
      comentario: "Pincel grosso cria relevo para textura rugosa.",
      tempoEstimado: 30,
      tags: ["textura", "rugosa"],
      habilidades: ["compreender-simulacao-textura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_067",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Equilibrio radial?",
      opcoes: [
        "Elementos em circulo",
        "Elementos simetricos",
        "Elementos assimetricos",
        "Elementos caoticos"
      ],
      correta: "Elementos em circulo",
      comentario: "Equilibrio radial tem elementos irradiando de centro.",
      tempoEstimado: 35,
      tags: ["equilibrio", "radial"],
      habilidades: ["aplicar-equilibrio-radial"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_068",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "perspectiva-profundidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Perspectiva cria?",
      opcoes: [
        "Ilusao 3D",
        "Cores vibrantes",
        "Formas geometricas",
        "Texturas lisas"
      ],
      correta: "Ilusao 3D",
      comentario: "Perspectiva faz superficie plana parecer tridimensional.",
      tempoEstimado: 40,
      tags: ["perspectiva", "ilusao"],
      habilidades: ["analisar-perspectiva"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_069",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "luz-sombra",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como luz cria volume?",
      opcoes: [
        "Sombras e realces",
        "Cores diferentes",
        "Formas variadas",
        "Texturas"
      ],
      correta: "Sombras e realces",
      comentario: "Luz cria sombras e areas iluminadas para volume.",
      tempoEstimado: 40,
      tags: ["luz", "volume"],
      habilidades: ["analisar-efeitos-luz-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_070",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "movimento-dinamismo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Como sugerir movimento estatico?",
      opcoes: [
        "Linhas curvas",
        "Formas repetidas",
        "Cores escuras",
        "Texturas rugosas"
      ],
      correta: "Linhas curvas",
      comentario: "Linhas curvas podem sugerir movimento em imagem estatica.",
      tempoEstimado: 40,
      tags: ["movimento", "estatico"],
      habilidades: ["avaliar-elementos-movimento-estatico"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_071",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Linha vertical?",
      opcoes: [
        "Cima baixo",
        "Esquerda direita",
        "Diagonal",
        "Curva"
      ],
      correta: "Cima baixo",
      comentario: "Linha vertical vai de cima para baixo.",
      tempoEstimado: 20,
      tags: ["linha", "vertical"],
      habilidades: ["identificar-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_072",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Forma quadrada?",
      opcoes: [
        "Quatro lados iguais",
        "Tres lados",
        "Cinco lados",
        "Redonda"
      ],
      correta: "Quatro lados iguais",
      comentario: "Quadrado tem quatro lados iguais e angulos retos.",
      tempoEstimado: 20,
      tags: ["forma", "quadrada"],
      habilidades: ["diferenciar-formas-geometricas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_073",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Cor fria?",
      opcoes: [
        "Azul",
        "Vermelho",
        "Laranja",
        "Amarelo"
      ],
      correta: "Azul",
      comentario: "Cores frias incluem azul, verde, roxo.",
      tempoEstimado: 25,
      tags: ["cor", "fria"],
      habilidades: ["identificar-temperaturas-cores"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_074",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar profundidade com cor?",
      opcoes: [
        "Cores desbotadas",
        "Cores vibrantes",
        "Cores escuras",
        "Cores claras"
      ],
      correta: "Cores desbotadas",
      comentario: "Cores desbotadas sugerem distancia maior.",
      tempoEstimado: 30,
      tags: ["profundidade", "cor"],
      habilidades: ["compreender-perspectiva-cor"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_075",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Textura macia?",
      opcoes: [
        "Superficie plana",
        "Superficie rugosa",
        "Superficie suave",
        "Superficie pontuda"
      ],
      correta: "Superficie suave",
      comentario: "Macia significa superficie suave ao tato.",
      tempoEstimado: 30,
      tags: ["textura", "macia"],
      habilidades: ["analisar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_076",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-superficie",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Como criar textura em escultura?",
      opcoes: [
        "Pintando",
        "Talhando",
        "Usando cola",
        "Secando"
      ],
      correta: "Talhando",
      comentario: "Talhar cria texturas na superficie da escultura.",
      tempoEstimado: 30,
      tags: ["textura", "escultura"],
      habilidades: ["compreender-tecnicas-textura-escultura"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_077",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Equilibrio por peso visual?",
      opcoes: [
        "Tamanhos iguais",
        "Cores iguais",
        "Pesos visuais balanceados",
        "Formas iguais"
      ],
      correta: "Pesos visuais balanceados",
      comentario: "Equilibrio considera tamanho, cor, posicao.",
      tempoEstimado: 35,
      tags: ["equilibrio", "peso-visual"],
      habilidades: ["aplicar-equilibrio-peso-visual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_078",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "perspectiva-profundidade",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Ponto de fuga em perspectiva?",
      opcoes: [
        "Onde linhas convergem",
        "Onde cores mudam",
        "Onde formas param",
        "Onde luzes brilham"
      ],
      correta: "Onde linhas convergem",
      comentario: "Ponto de fuga e onde linhas paralelas parecem se encontrar.",
      tempoEstimado: 40,
      tags: ["perspectiva", "ponto-fuga"],
      habilidades: ["analisar-ponto-fuga"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_079",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "luz-sombra",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como sombra indica direcao luz?",
      opcoes: [
        "Posicao sombra",
        "Cor sombra",
        "Tamanho sombra",
        "Forma sombra"
      ],
      correta: "Posicao sombra",
      comentario: "Posicao da sombra mostra de onde vem a luz.",
      tempoEstimado: 40,
      tags: ["sombra", "direcao-luz"],
      habilidades: ["analisar-sombras-direcao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_080",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "movimento-dinamismo",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Como dinamismo afeta composicao?",
      opcoes: [
        "Cria energia",
        "Cria calma",
        "Cria equilibrio",
        "Cria estaticidade"
      ],
      correta: "Cria energia",
      comentario: "Dinamismo adiciona energia e movimento a obra.",
      tempoEstimado: 40,
      tags: ["dinamismo", "composicao"],
      habilidades: ["avaliar-dinamismo-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_081",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e uma forma geometrica?",
      opcoes: [
        "Circulo",
        "Nuvem",
        "Folha",
        "Montanha"
      ],
      correta: "Circulo",
      comentario: "Formas geometricas sao regulares como circulo, quadrado.",
      tempoEstimado: 20,
      tags: ["forma", "geometrica"],
      habilidades: ["identificar-formas-geometricas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_082",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual linha e horizontal?",
      opcoes: [
        "Esquerda-direita",
        "Cima-baixo",
        "Diagonal",
        "Curva"
      ],
      correta: "Esquerda-direita",
      comentario: "Linha horizontal vai da esquerda para direita.",
      tempoEstimado: 20,
      tags: ["linha", "horizontal"],
      habilidades: ["compreender-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_083",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor e primaria?",
      opcoes: [
        "Vermelho",
        "Rosa",
        "Laranja",
        "Roxo"
      ],
      correta: "Vermelho",
      comentario: "Cores primarias sao vermelho, azul, amarelo.",
      tempoEstimado: 25,
      tags: ["cor", "primaria"],
      habilidades: ["identificar-cores-primarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_084",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que e sombra?",
      opcoes: [
        "Luz direta",
        "Area sem luz",
        "Cor brilhante",
        "Textura lisa"
      ],
      correta: "Area sem luz",
      comentario: "Sombra e a area onde a luz nao chega.",
      tempoEstimado: 30,
      tags: ["sombra", "luz"],
      habilidades: ["compreender-luz-sombra"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_085",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual textura e rugosa?",
      opcoes: [
        "Papel areia",
        "Vidro",
        "Seda",
        "Agua"
      ],
      correta: "Papel areia",
      comentario: "Textura rugosa sente-se aspra ao toque.",
      tempoEstimado: 30,
      tags: ["textura", "rugosa"],
      habilidades: ["analisar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_086",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que cria volume?",
      opcoes: [
        "Sombras e luzes",
        "Cores planas",
        "Linhas retas",
        "Formas 2D"
      ],
      correta: "Sombras e luzes",
      comentario: "Sombras e luzes criam ilusao de volume.",
      tempoEstimado: 30,
      tags: ["volume", "sombras"],
      habilidades: ["compreender-volume"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_087",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual composicao e equilibrada?",
      opcoes: [
        "Elementos centrados",
        "Tudo a esquerda",
        "Tudo a direita",
        "Desordenado"
      ],
      correta: "Elementos centrados",
      comentario: "Equilibrio ocorre quando elementos estao distribuidos harmoniosamente.",
      tempoEstimado: 35,
      tags: ["equilibrio", "composicao"],
      habilidades: ["identificar-equilibrio-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_088",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "O que e ritmo visual?",
      opcoes: [
        "Repeticao de elementos",
        "Cor unica",
        "Forma irregular",
        "Luz fraca"
      ],
      correta: "Repeticao de elementos",
      comentario: "Ritmo visual criado por repeticao de formas ou cores.",
      tempoEstimado: 40,
      tags: ["ritmo", "composicao"],
      habilidades: ["analisar-ritmo-visual"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_089",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como materiais influenciam expressao?",
      opcoes: [
        "Escolhem estilo",
        "Ignoram cor",
        "Simplificam forma",
        "Removem textura"
      ],
      correta: "Escolhem estilo",
      comentario: "Materiais como oleo ou acrilico influenciam o estilo da obra.",
      tempoEstimado: 40,
      tags: ["materiais", "expressao"],
      habilidades: ["analisar-influencia-materiais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_090",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que elementos visuais sao importantes?",
      opcoes: [
        "Comunicam ideias",
        "Apenas decoram",
        "Ignoram emocao",
        "Simplificam arte"
      ],
      correta: "Comunicam ideias",
      comentario: "Elementos visuais ajudam a comunicar ideias e emocao.",
      tempoEstimado: 40,
      tags: ["expressao", "importancia"],
      habilidades: ["avaliar-importancia-elementos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_091",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "O que e uma forma organica?",
      opcoes: [
        "Arvore",
        "Quadrado",
        "Triangulo",
        "Circulo"
      ],
      correta: "Arvore",
      comentario: "Formas organicas sao irregulares como natureza.",
      tempoEstimado: 20,
      tags: ["forma", "organica"],
      habilidades: ["identificar-formas-organicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_092",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "linha-forma",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual linha e vertical?",
      opcoes: [
        "Cima-baixo",
        "Esquerda-direita",
        "Diagonal",
        "Curva"
      ],
      correta: "Cima-baixo",
      comentario: "Linha vertical vai de cima para baixo.",
      tempoEstimado: 20,
      tags: ["linha", "vertical"],
      habilidades: ["compreender-tipos-linha"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_093",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 3,
      cognicao: "conhecimento",
      tipo: "multipla_escolha",
      enunciado: "Qual cor e secundaria?",
      opcoes: [
        "Verde",
        "Vermelho",
        "Azul",
        "Amarelo"
      ],
      correta: "Verde",
      comentario: "Cores secundarias sao misturas de primarias.",
      tempoEstimado: 25,
      tags: ["cor", "secundaria"],
      habilidades: ["identificar-cores-secundarias"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_094",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "cor-luz",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que e reflexo?",
      opcoes: [
        "Luz refletida",
        "Sombra escura",
        "Cor opaca",
        "Textura dura"
      ],
      correta: "Luz refletida",
      comentario: "Reflexo e luz que volta de superficie brilhante.",
      tempoEstimado: 30,
      tags: ["reflexo", "luz"],
      habilidades: ["compreender-luz-reflexo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_095",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 5,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual textura e lisa?",
      opcoes: [
        "Vidro",
        "Papel areia",
        "Tecido",
        "Madeira"
      ],
      correta: "Vidro",
      comentario: "Textura lisa sente-se suave ao toque.",
      tempoEstimado: 30,
      tags: ["textura", "lisa"],
      habilidades: ["analisar-texturas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_096",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "textura-volume",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 6,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que cria profundidade?",
      opcoes: [
        "Perspectiva",
        "Cores planas",
        "Linhas retas",
        "Formas 2D"
      ],
      correta: "Perspectiva",
      comentario: "Perspectiva cria ilusao de profundidade.",
      tempoEstimado: 30,
      tags: ["profundidade", "perspectiva"],
      habilidades: ["compreender-profundidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_097",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 7,
      cognicao: "aplicacao",
      tipo: "multipla_escolha",
      enunciado: "Qual composicao e dinamica?",
      opcoes: [
        "Elementos em movimento",
        "Tudo estatico",
        "Tudo centralizado",
        "Desordenado"
      ],
      correta: "Elementos em movimento",
      comentario: "Dinamismo ocorre quando elementos sugerem movimento.",
      tempoEstimado: 35,
      tags: ["dinamismo", "composicao"],
      habilidades: ["identificar-dinamismo-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_098",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "composicao-equilibrio",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "O que e proporcao?",
      opcoes: [
        "Relacao entre tamanhos",
        "Cor unica",
        "Forma irregular",
        "Luz fraca"
      ],
      correta: "Relacao entre tamanhos",
      comentario: "Proporcao e a relacao harmoniosa entre tamanhos.",
      tempoEstimado: 40,
      tags: ["proporcao", "composicao"],
      habilidades: ["analisar-proporcao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_099",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "materiais-basicos",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 9,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Como materiais influenciam durabilidade?",
      opcoes: [
        "Escolhem resistencia",
        "Ignoram tempo",
        "Simplificam cor",
        "Removem forma"
      ],
      correta: "Escolhem resistencia",
      comentario: "Materiais como oleo duram mais que acrilico.",
      tempoEstimado: 40,
      tags: ["materiais", "durabilidade"],
      habilidades: ["analisar-durabilidade-materiais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "ev_100",
      serie: [1],
      materia: "Artes",
      topico: "Elementos Visuais",
      subtopico: "expressao-visual",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 10,
      cognicao: "avaliacao",
      tipo: "multipla_escolha",
      enunciado: "Por que composicao e essencial?",
      opcoes: [
        "Organiza elementos",
        "Apenas colore",
        "Ignora forma",
        "Simplifica luz"
      ],
      correta: "Organiza elementos",
      comentario: "Composicao organiza elementos para impacto visual.",
      tempoEstimado: 40,
      tags: ["composicao", "essencial"],
      habilidades: ["avaliar-importancia-composicao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    }
  ]
};
