export const razoesProporcoes = {
  id: "matematica_razoes_proporcoes",
  materia: "Matemática",
  serie: [1],
  topico: "Razões e Proporções",

  metadados: {
    disciplinaId: "matematica",
    base: "ESCOLAR",
    eixo: "Algebra",
    frente: "Proporcionalidade",
    searchAliases: [
      "razao",
      "proporcao",
      "regra de tres",
      "escala",
      "proporcionalidade"
    ],
    subtopicosBase: [
      "Conceito de razao",
      "Conceito de proporcao",
      "Simplificacao",
      "Grandezas proporcionais",
      "Escalas",
      "Divisao proporcional",
      "Regra de tres simples"
    ],
    habilidadesBase: [
      "interpretar razao",
      "resolver proporcoes",
      "simplificar razoes",
      "identificar grandezas proporcionais",
      "resolver regra de tres simples",
      "aplicar escala",
      "resolver divisao proporcional"
    ]
  },

  questoes: [
    {
  id: "rp_001",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 1,
  cognicao: "interpretacao",
  tipo: "multipla_escolha",
  enunciado: "A razão entre 4 e 2 é:",
  opcoes: ["1", "2", "3", "4"],
  correta: "2",
  comentario: "Razão é divisão: 4 ÷ 2 = 2.",
  tempoEstimado: 20,
  tags: ["razao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_002",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 2,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Calcule a razão 10:5.",
  opcoes: [],
  correta: "2",
  comentario: "10 ÷ 5 = 2.",
  tempoEstimado: 20,
  tags: ["razao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_003",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 2,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique a razão 6:8.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida ambos os termos por 2.",
  tempoEstimado: 20,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_004",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 2,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "2/3 e 4/6 formam uma proporção.",
  opcoes: [],
  correta: true,
  comentario: "As frações são equivalentes.",
  tempoEstimado: 20,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_005",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 3,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["1:2", "3:4"],
  correta: "3:4",
  comentario: "1:2 = 0,5 e 3:4 = 0,75.",
  tempoEstimado: 20,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_006",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 2,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Calcule a razão 12:3.",
  opcoes: [],
  correta: "4",
  comentario: "12 ÷ 3 = 4.",
  tempoEstimado: 20,
  tags: ["razao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_007",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 3,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique a razão 9:12.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida ambos os termos por 3.",
  tempoEstimado: 20,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_008",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 3,
  cognicao: "interpretacao",
  tipo: "multipla_escolha",
  enunciado: "Qual par forma uma proporção?",
  opcoes: ["2/5 e 3/7", "1/2 e 2/4", "3/8 e 5/9", "4/7 e 2/5"],
  correta: "1/2 e 2/4",
  comentario: "As duas razões são equivalentes.",
  tempoEstimado: 20,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_009",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 3,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se a quantidade de maçãs dobra e o preço total também dobra, as grandezas são diretamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Quando uma dobra e a outra também, há proporcionalidade direta.",
  tempoEstimado: 20,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_010",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "facil",
  dificuldadeNivel: 3,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é menor?",
  opcoes: ["2:5", "1:2"],
  correta: "2:5",
  comentario: "2:5 = 0,4 e 1:2 = 0,5.",
  tempoEstimado: 20,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_021",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Se 4 camisetas custam 60 reais, quanto custam 6 camisetas?",
  opcoes: [],
  correta: "90",
  comentario: "60 ÷ 4 = 15 por camiseta; 6 × 15 = 90.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_022",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se a velocidade aumenta e o tempo para percorrer a mesma distância diminui, as grandezas são inversamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Mais velocidade implica menos tempo, mantendo a distância fixa.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_023",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 48 em partes proporcionais a 2 e 4.",
  opcoes: [],
  correta: "16 e 32",
  comentario: "A razão 2:4 equivale a 1:2; total de partes = 3.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["resolver divisao proporcional"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_024",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 4,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "A razão entre 15 e 20, simplificada, é:",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida ambos os números por 5.",
  tempoEstimado: 25,
  tags: ["razao", "simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_025",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Em uma escala 1:200, 3 cm no desenho representam quantos metros reais?",
  opcoes: [],
  correta: "6",
  comentario: "3 cm representam 600 cm, que equivalem a 6 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["aplicar escala"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_026",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva 3/5 = 9/x.",
  opcoes: [],
  correta: "15",
  comentario: "3x = 45, então x = 15.",
  tempoEstimado: 25,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_027",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique a razão 21:28.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida ambos os termos por 7.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_028",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "multipla_escolha",
  enunciado: "Quais grandezas são diretamente proporcionais?",
  opcoes: [
    "quantidade comprada e valor pago",
    "velocidade e tempo, em mesma distância",
    "número de operários e tempo, em mesmo trabalho",
    "preço e desconto fixo"
  ],
  correta: "quantidade comprada e valor pago",
  comentario: "Se o preço unitário é fixo, comprando mais, paga-se mais na mesma proporção.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_029",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Se 5 litros custam 35 reais, quanto custam 8 litros?",
  opcoes: [],
  correta: "56",
  comentario: "35 ÷ 5 = 7 por litro; 8 × 7 = 56.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_030",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["7:12", "5:8"],
  correta: "5:8",
  comentario: "7/12 ≈ 0,583 e 5/8 = 0,625.",
  tempoEstimado: 25,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_031",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva 4/7 = x/21.",
  opcoes: [],
  correta: "12",
  comentario: "7x = 84, então x = 12.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_032",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Se 12 máquinas produzem 360 peças por dia, quantas peças 15 máquinas produzem por dia no mesmo ritmo?",
  opcoes: [],
  correta: "450",
  comentario: "Proporção direta: 360 ÷ 12 = 30 por máquina; 15 × 30 = 450.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_033",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 72 em partes proporcionais a 3, 4 e 5.",
  opcoes: [],
  correta: "18, 24 e 30",
  comentario: "Soma da razão = 12. Cada parte vale 6.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["resolver divisao proporcional"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_034",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Em uma escala 1:250, um comprimento real de 10 m será representado por quantos cm no desenho?",
  opcoes: [],
  correta: "4",
  comentario: "10 m = 1000 cm; 1000 ÷ 250 = 4 cm.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["aplicar escala"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_035",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se a distância é fixa, o tempo gasto e a velocidade são grandezas inversamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Mais velocidade implica menos tempo.",
  tempoEstimado: 30,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_036",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["11:18", "5:8"],
  correta: "5:8",
  comentario: "11/18 ≈ 0,611 e 5/8 = 0,625.",
  tempoEstimado: 30,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_037",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva 6/9 = 14/x.",
  opcoes: [],
  correta: "21",
  comentario: "6x = 126, então x = 21.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_038",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Se 8 pessoas consomem 24 litros de água por dia, quantos litros 14 pessoas consomem no mesmo ritmo?",
  opcoes: [],
  correta: "42",
  comentario: "24 ÷ 8 = 3 litros por pessoa; 14 × 3 = 42.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_039",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 96 em partes proporcionais a 2, 3 e 7.",
  opcoes: [],
  correta: "16, 24 e 56",
  comentario: "Soma da razão = 12. Cada parte vale 8.",
  tempoEstimado: 35,
  tags: ["divisao-proporcional"],
  habilidades: ["resolver divisao proporcional"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_040",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Em uma escala 1:500, um objeto mede 3 cm no desenho. Qual é a medida real em metros?",
  opcoes: [],
  correta: "15",
  comentario: "3 × 500 = 1500 cm = 15 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["aplicar escala"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_051",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 4,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["3:5", "4:7"],
  correta: "3:5",
  comentario: "3/5 = 0,6 e 4/7 ≈ 0,57.",
  tempoEstimado: 25,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_052",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 4,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 24:36.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 12.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_053",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 4/5 = x/20.",
  opcoes: [],
  correta: "16",
  comentario: "5x = 80.",
  tempoEstimado: 25,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_054",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se dobrar o número de itens, dobrar o valor pago indica proporcionalidade direta.",
  opcoes: [],
  correta: true,
  comentario: "Relação direta.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_055",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Escala 1:20 → 5 cm representa quanto real?",
  opcoes: [],
  correta: "100",
  comentario: "5 × 20.",
  tempoEstimado: 25,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_056",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "2 kg custam 14 reais. Quanto custam 5 kg?",
  opcoes: [],
  correta: "35",
  comentario: "7 por kg.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_057",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 60 em razão 2:3.",
  opcoes: [],
  correta: "24 e 36",
  comentario: "Total 5 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_058",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["7:10", "2:3"],
  correta: "7:10",
  comentario: "7/10 = 0,7 e 2/3 ≈ 0,66.",
  tempoEstimado: 25,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_059",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 3/4 = x/16.",
  opcoes: [],
  correta: "12",
  comentario: "4x = 48.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_060",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Mais trabalhadores → menos tempo (mesmo trabalho) = inversa.",
  opcoes: [],
  correta: true,
  comentario: "Inversamente proporcional.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_061",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:250 → 8 cm representa quantos metros?",
  opcoes: [],
  correta: "20",
  comentario: "2000 cm = 20 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_062",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 90 em razão 2:3:4.",
  opcoes: [],
  correta: "20, 30 e 40",
  comentario: "Soma 9 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_063",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 5/6 = x/18.",
  opcoes: [],
  correta: "15",
  comentario: "6x = 90.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_064",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["9:14", "4:6"],
  correta: "4:6",
  comentario: "0,64 vs 0,66.",
  tempoEstimado: 30,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_065",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "6 máquinas fazem 120 peças. 15 máquinas fazem quantas?",
  opcoes: [],
  correta: "300",
  comentario: "20 por máquina.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_066",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 4,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 30:45.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 15.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_067",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["5:9", "4:7"],
  correta: "4:7",
  comentario: "≈0,57 vs ≈0,55.",
  tempoEstimado: 25,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_068",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 7/8 = x/32.",
  opcoes: [],
  correta: "28",
  comentario: "8x = 224.",
  tempoEstimado: 25,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_069",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se uma grandeza dobra e a outra triplica, não são diretamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "A razão não permanece constante.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_070",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Escala 1:30 → 6 cm representa quanto real?",
  opcoes: [],
  correta: "180",
  comentario: "6 × 30.",
  tempoEstimado: 25,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_071",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "4 litros custam 28 reais. Quanto custam 7 litros?",
  opcoes: [],
  correta: "49",
  comentario: "7 por litro.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_072",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 84 na razão 3:4.",
  opcoes: [],
  correta: "36 e 48",
  comentario: "7 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_073",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 6/7 = x/21.",
  opcoes: [],
  correta: "18",
  comentario: "7x = 126.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_074",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["8:11", "5:7"],
  correta: "5:7",
  comentario: "≈0,73 vs ≈0,71.",
  tempoEstimado: 25,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_075",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se uma cresce e a outra diminui proporcionalmente, é relação inversa.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_076",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:500 → 2 cm representa quantos metros?",
  opcoes: [],
  correta: "10",
  comentario: "1000 cm = 10 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_077",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 120 na razão 1:2:3.",
  opcoes: [],
  correta: "20, 40 e 60",
  comentario: "6 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_078",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 9/10 = x/50.",
  opcoes: [],
  correta: "45",
  comentario: "10x = 450.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_079",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["11:16", "7:10"],
  correta: "7:10",
  comentario: "≈0,687 vs 0,7.",
  tempoEstimado: 30,
  tags: ["razao", "comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_080",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "8 operários fazem um trabalho em 6 dias. Quantos dias 4 operários levam?",
  opcoes: [],
  correta: "12",
  comentario: "Inversamente proporcional.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_087",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 12/15 = x/45.",
  opcoes: [],
  correta: "36",
  comentario: "15x = 540.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_088",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 140 na razão 3:4:7.",
  opcoes: [],
  correta: "30, 40 e 70",
  comentario: "14 partes.",
  tempoEstimado: 35,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_089",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["13:20", "3:5"],
  correta: "13:20",
  comentario: "0,65 vs 0,6.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_090",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "10 pessoas fazem um trabalho em 8 dias. 20 pessoas fazem em quantos dias?",
  opcoes: [],
  correta: "4",
  comentario: "Inversamente proporcional.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_091",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 16:40.",
  opcoes: [],
  correta: "2:5",
  comentario: "Divida por 8.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_092",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 10/12 = x/24.",
  opcoes: [],
  correta: "20",
  comentario: "12x = 240.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_093",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 36 na razão 1:2:3.",
  opcoes: [],
  correta: "6, 12 e 18",
  comentario: "6 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_094",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["9:13", "7:10"],
  correta: "7:10",
  comentario: "≈0,69 vs 0,7.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_095",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se x dobra e y dobra, a relação é diretamente proporcional.",
  opcoes: [],
  correta: true,
  comentario: "Relação direta.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_096",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:400 → 5 cm representam quantos metros?",
  opcoes: [],
  correta: "20",
  comentario: "2000 cm = 20 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_097",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 14/21 = x/42.",
  opcoes: [],
  correta: "28",
  comentario: "21x = 588.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_098",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 150 na razão 2:3:5.",
  opcoes: [],
  correta: "30, 45 e 75",
  comentario: "10 partes.",
  tempoEstimado: 35,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_099",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual razão é maior?",
  opcoes: ["17:25", "2:3"],
  correta: "17:25",
  comentario: "0,68 vs ≈0,66.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_100",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "12 trabalhadores fazem um trabalho em 10 dias. 15 fazem em quantos dias?",
  opcoes: [],
  correta: "8",
  comentario: "Inversamente proporcional.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_101",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é equivalente a 2:3?",
  opcoes: ["4:6", "3:5"],
  correta: "4:6",
  comentario: "Mesma proporção.",
  tempoEstimado: 25,
  tags: ["razao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_102",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 4,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 18:24.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida por 6.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_103",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 2/3 = x/12.",
  opcoes: [],
  correta: "8",
  comentario: "3x = 24.",
  tempoEstimado: 25,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_104",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se uma grandeza dobra e a outra também dobra, são diretamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Razão constante.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_105",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Escala 1:10 → 12 cm representa quanto real?",
  opcoes: [],
  correta: "120",
  comentario: "12 × 10.",
  tempoEstimado: 25,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_106",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "5 kg custam 25 reais. Quanto custam 8 kg?",
  opcoes: [],
  correta: "40",
  comentario: "5 por kg.",
  tempoEstimado: 30,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_107",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 70 na razão 2:5.",
  opcoes: [],
  correta: "20 e 50",
  comentario: "7 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_108",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 9/11 = x/33.",
  opcoes: [],
  correta: "27",
  comentario: "11x = 297.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_109",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["3:8", "4:9"],
  correta: "4:9",
  comentario: "≈0,37 vs 0,44.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_110",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se aumentar uma grandeza e diminuir a outra na mesma proporção, é inversa.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_111",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:200 → 4 cm representam quantos metros?",
  opcoes: [],
  correta: "8",
  comentario: "800 cm = 8 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_112",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 180 na razão 2:3:4.",
  opcoes: [],
  correta: "40, 60 e 80",
  comentario: "9 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_113",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 11/13 = x/39.",
  opcoes: [],
  correta: "33",
  comentario: "13x = 429.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_114",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["15:22", "7:10"],
  correta: "7:10",
  comentario: "≈0,68 vs 0,7.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_115",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "15 máquinas produzem 300 peças. 25 produzem quantas?",
  opcoes: [],
  correta: "500",
  comentario: "20 por máquina.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_116",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 50:75.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 25.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_117",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 7/9 = x/27.",
  opcoes: [],
  correta: "21",
  comentario: "9x = 189.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_118",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 90 na razão 1:2:3.",
  opcoes: [],
  correta: "15, 30 e 45",
  comentario: "6 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_119",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["4:9", "5:11"],
  correta: "5:11",
  comentario: "≈0,44 vs 0,45.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_120",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se duas grandezas mantêm razão constante, são proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_121",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:300 → 3 cm representam quantos metros?",
  opcoes: [],
  correta: "9",
  comentario: "900 cm = 9 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_122",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 210 na razão 2:5:7.",
  opcoes: [],
  correta: "30, 75 e 105",
  comentario: "14 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_123",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 13/17 = x/34.",
  opcoes: [],
  correta: "26",
  comentario: "17x = 442.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_124",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["19:30", "2:3"],
  correta: "2:3",
  comentario: "≈0,63 vs 0,66.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_125",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "18 operários fazem uma obra em 12 dias. 9 operários fazem em quantos dias?",
  opcoes: [],
  correta: "24",
  comentario: "Inversamente proporcional.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_126",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 54:72.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida por 18.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_127",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 5/8 = x/40.",
  opcoes: [],
  correta: "25",
  comentario: "8x = 200.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_128",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 72 na razão 2:3:4.",
  opcoes: [],
  correta: "16, 24 e 32",
  comentario: "9 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_129",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["6:13", "5:11"],
  correta: "5:11",
  comentario: "≈0,46 vs 0,45.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_130",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Grandezas inversas mantêm produto constante.",
  opcoes: [],
  correta: true,
  comentario: "Ex: trabalho.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_131",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:600 → 5 cm representam quantos metros?",
  opcoes: [],
  correta: "30",
  comentario: "3000 cm = 30 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_132",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 160 na razão 1:3:4.",
  opcoes: [],
  correta: "20, 60 e 80",
  comentario: "8 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_133",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 15/18 = x/36.",
  opcoes: [],
  correta: "30",
  comentario: "18x = 540.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_134",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["21:32", "2:3"],
  correta: "2:3",
  comentario: "≈0,65 vs 0,66.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_135",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "20 operários fazem em 6 dias. 30 fazem em quantos dias?",
  opcoes: [],
  correta: "4",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_136",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 64:96.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 32.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_137",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 4/9 = x/27.",
  opcoes: [],
  correta: "12",
  comentario: "9x = 108.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_138",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 45 na razão 2:1.",
  opcoes: [],
  correta: "30 e 15",
  comentario: "3 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_139",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["7:15", "1:2"],
  correta: "1:2",
  comentario: "≈0,46 vs 0,5.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_140",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se o produto permanece constante, é relação inversa.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_141",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:800 → 2 cm representam quantos metros?",
  opcoes: [],
  correta: "16",
  comentario: "1600 cm = 16 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_142",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 200 na razão 3:2:5.",
  opcoes: [],
  correta: "60, 40 e 100",
  comentario: "10 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_143",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 16/20 = x/40.",
  opcoes: [],
  correta: "32",
  comentario: "20x = 640.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_144",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["23:36", "5:8"],
  correta: "5:8",
  comentario: "≈0,63 vs 0,625.",
  tempoEstimado: 30,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_145",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "25 operários fazem em 8 dias. 10 fazem em quantos dias?",
  opcoes: [],
  correta: "20",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_146",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Simplifique 36:54.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 18.",
  tempoEstimado: 25,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_147",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de proporcao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "calculo",
  tipo: "input",
  enunciado: "Resolva: 6/11 = x/22.",
  opcoes: [],
  correta: "12",
  comentario: "11x = 132.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_148",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 63 na razão 2:1.",
  opcoes: [],
  correta: "42 e 21",
  comentario: "3 partes.",
  tempoEstimado: 30,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_149",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Conceito de razao",
  dificuldadeLabel: "media",
  dificuldadeNivel: 5,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["8:17", "1:2"],
  correta: "1:2",
  comentario: "≈0,47 vs 0,5.",
  tempoEstimado: 25,
  tags: ["razao","comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_150",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "media",
  dificuldadeNivel: 6,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Grandezas diretamente proporcionais mantêm quociente constante.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 25,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_151",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão NÃO é equivalente a 3:5?",
  opcoes: ["6:10", "9:15", "12:25"],
  correta: "12:25",
  comentario: "As duas primeiras mantêm proporção.",
  tempoEstimado: 30,
  tags: ["equivalencia"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_152",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 84:126.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 42.",
  tempoEstimado: 30,
  tags: ["simplificacao"],
  habilidades: ["simplificar razoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_153",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 4/7 = x/28.",
  opcoes: [],
  correta: "16",
  comentario: "7x = 112.",
  tempoEstimado: 30,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_154",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é menor?",
  opcoes: ["11:18", "5:8"],
  correta: "11:18",
  comentario: "≈0,61 vs 0,625.",
  tempoEstimado: 30,
  tags: ["comparacao"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_155",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se uma grandeza triplica e a outra também, a relação continua direta.",
  opcoes: [],
  correta: true,
  comentario: "Razão constante.",
  tempoEstimado: 30,
  tags: ["grandezas-proporcionais"],
  habilidades: ["identificar grandezas proporcionais"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},

{
  id: "rp_156",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:500 → 7 cm representam quantos metros?",
  opcoes: [],
  correta: "35",
  comentario: "3500 cm = 35 m.",
  tempoEstimado: 30,
  tags: ["escala"],
  habilidades: ["interpretar escalas"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_157",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 210 na razão 3:4:5.",
  opcoes: [],
  correta: "52,5, 70 e 87,5",
  comentario: "12 partes.",
  tempoEstimado: 35,
  tags: ["divisao-proporcional"],
  habilidades: ["dividir proporcionalmente"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_158",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 7/12 = x/48.",
  opcoes: [],
  correta: "28",
  comentario: "12x = 336.",
  tempoEstimado: 35,
  tags: ["proporcao"],
  habilidades: ["resolver proporcoes"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_159",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual razão é equivalente a 4:7?",
  opcoes: ["8:14", "12:20"],
  correta: "8:14",
  comentario: "Mesma proporção.",
  tempoEstimado: 30,
  tags: ["equivalencia"],
  habilidades: ["interpretar razao"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_161",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual é equivalente a 5:8?",
  opcoes: ["10:16", "15:20"],
  correta: "10:16",
  comentario: "Mesma proporção.",
  tempoEstimado: 30,
  tags: ["equivalencia"]
},
{
  id: "rp_162",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 96:144.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 48.",
  tempoEstimado: 30,
  tags: ["simplificacao"]
},
{
  id: "rp_163",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 6/13 = x/52.",
  opcoes: [],
  correta: "24",
  comentario: "13x = 312.",
  tempoEstimado: 30,
  tags: ["proporcao"]
},
{
  id: "rp_164",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual é maior?",
  opcoes: ["7:12", "3:5"],
  correta: "3:5",
  comentario: "≈0,58 vs 0,6.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_165",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se duas grandezas aumentam na mesma proporção, são diretamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 30,
  tags: ["grandezas"]
},

{
  id: "rp_166",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:400 → 9 cm representam quantos metros?",
  opcoes: [],
  correta: "36",
  comentario: "3600 cm = 36 m.",
  tempoEstimado: 30,
  tags: ["escala"]
},
{
  id: "rp_167",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 300 na razão 2:3:5.",
  opcoes: [],
  correta: "60, 90 e 150",
  comentario: "10 partes.",
  tempoEstimado: 35,
  tags: ["divisao"]
},
{
  id: "rp_168",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 13/17 = x/34.",
  opcoes: [],
  correta: "26",
  comentario: "17x = 442.",
  tempoEstimado: 35,
  tags: ["proporcao"]
},
{
  id: "rp_169",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual NÃO é equivalente a 6:7?",
  opcoes: ["12:14", "18:21", "24:30"],
  correta: "24:30",
  comentario: "Proporção diferente.",
  tempoEstimado: 30,
  tags: ["equivalencia"]
},
{
  id: "rp_170",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "18 operários fazem em 5 dias. 9 fazem em quantos dias?",
  opcoes: [],
  correta: "10",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra"]
},

{
  id: "rp_171",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 132:198.",
  opcoes: [],
  correta: "2:3",
  comentario: "Divida por 66.",
  tempoEstimado: 30,
  tags: ["simplificacao"]
},
{
  id: "rp_172",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual menor?",
  opcoes: ["4:7", "5:9"],
  correta: "4:7",
  comentario: "≈0,57 vs 0,55.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_173",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Grandezas inversamente proporcionais mantêm razão constante.",
  opcoes: [],
  correta: false,
  comentario: "Mantêm produto constante.",
  tempoEstimado: 30,
  tags: ["grandezas"]
},
{
  id: "rp_174",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 14/21 = x/63.",
  opcoes: [],
  correta: "42",
  comentario: "21x = 882.",
  tempoEstimado: 35,
  tags: ["proporcao"]
},
{
  id: "rp_175",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:300 → 4 cm representam quantos metros?",
  opcoes: [],
  correta: "12",
  comentario: "1200 cm = 12 m.",
  tempoEstimado: 30,
  tags: ["escala"]
},
{
  id: "rp_160",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "8 trabalhadores fazem em 15 dias. 12 fazem em quantos dias?",
  opcoes: [],
  correta: "10",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra-de-tres"],
  habilidades: ["resolver regra de tres simples"],
  collections: ["questions"],
  sourceType: "original",
  sourceExam: "",
  sourceYear: null,
  competencies: [],
  status: "revisada"
},
{
  id: "rp_176",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual NÃO é equivalente a 2:3?",
  opcoes: ["4:6", "10:15", "8:11"],
  correta: "8:11",
  comentario: "As duas primeiras mantêm proporção.",
  tempoEstimado: 30,
  tags: ["equivalencia"]
},
{
  id: "rp_177",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 150:210.",
  opcoes: [],
  correta: "5:7",
  comentario: "Divida por 30.",
  tempoEstimado: 30,
  tags: ["simplificacao"]
},
{
  id: "rp_178",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 9/14 = x/56.",
  opcoes: [],
  correta: "36",
  comentario: "14x = 504.",
  tempoEstimado: 30,
  tags: ["proporcao"]
},
{
  id: "rp_179",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual é maior?",
  opcoes: ["13:21", "5:8"],
  correta: "5:8",
  comentario: "≈0,619 vs 0,625.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_180",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se duas grandezas dobram juntas, são diretamente proporcionais.",
  opcoes: [],
  correta: true,
  comentario: "Mantêm razão constante.",
  tempoEstimado: 30,
  tags: ["grandezas"]
},

{
  id: "rp_181",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:250 → 12 cm representam quantos metros?",
  opcoes: [],
  correta: "30",
  comentario: "3000 cm = 30 m.",
  tempoEstimado: 30,
  tags: ["escala"]
},
{
  id: "rp_182",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 360 na razão 2:3:5.",
  opcoes: [],
  correta: "72, 108 e 180",
  comentario: "10 partes.",
  tempoEstimado: 35,
  tags: ["divisao"]
},
{
  id: "rp_183",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 11/13 = x/52.",
  opcoes: [],
  correta: "44",
  comentario: "13x = 572.",
  tempoEstimado: 35,
  tags: ["proporcao"]
},
{
  id: "rp_184",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual é equivalente a 7:9?",
  opcoes: ["14:18", "21:30"],
  correta: "14:18",
  comentario: "Mesma proporção.",
  tempoEstimado: 30,
  tags: ["equivalencia"]
},
{
  id: "rp_185",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "15 máquinas produzem em 4 dias. 10 produzem em quantos dias?",
  opcoes: [],
  correta: "6",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra"]
},

{
  id: "rp_186",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 225:300.",
  opcoes: [],
  correta: "3:4",
  comentario: "Divida por 75.",
  tempoEstimado: 30,
  tags: ["simplificacao"]
},
{
  id: "rp_187",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual menor?",
  opcoes: ["9:14", "2:3"],
  correta: "9:14",
  comentario: "≈0,64 vs 0,66.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_188",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Se uma aumenta e outra diminui mantendo produto constante, são inversas.",
  opcoes: [],
  correta: true,
  comentario: "Definição.",
  tempoEstimado: 30,
  tags: ["grandezas"]
},
{
  id: "rp_189",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 18/24 = x/72.",
  opcoes: [],
  correta: "54",
  comentario: "24x = 1296.",
  tempoEstimado: 35,
  tags: ["proporcao"]
},
{
  id: "rp_190",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:1000 → 3 cm representam quantos metros?",
  opcoes: [],
  correta: "30",
  comentario: "3000 cm = 30 m.",
  tempoEstimado: 30,
  tags: ["escala"]
},

{
  id: "rp_191",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Divisao proporcional",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Divida 480 na razão 1:2:3:4.",
  opcoes: [],
  correta: "48, 96, 144 e 192",
  comentario: "10 partes.",
  tempoEstimado: 35,
  tags: ["divisao"]
},
{
  id: "rp_192",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Equivalencia",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual NÃO equivale a 5:6?",
  opcoes: ["10:12", "15:18", "20:25"],
  correta: "20:25",
  comentario: "Razão diferente.",
  tempoEstimado: 30,
  tags: ["equivalencia"]
},
{
  id: "rp_193",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual maior?",
  opcoes: ["17:25", "2:3"],
  correta: "2:3",
  comentario: "≈0,68 vs 0,66.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_194",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "12 homens fazem em 10 dias. 8 homens fazem em quantos dias?",
  opcoes: [],
  correta: "15",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra"]
},
{
  id: "rp_195",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Simplificacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 8,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Simplifique 121:143.",
  opcoes: [],
  correta: "11:13",
  comentario: "Divida por 11.",
  tempoEstimado: 30,
  tags: ["simplificacao"]
},

{
  id: "rp_196",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Proporcao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Resolva: 21/28 = x/84.",
  opcoes: [],
  correta: "63",
  comentario: "28x = 1764.",
  tempoEstimado: 35,
  tags: ["proporcao"]
},
{
  id: "rp_197",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Grandezas proporcionais",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "vf",
  enunciado: "Grandezas diretamente proporcionais mantêm produto constante.",
  opcoes: [],
  correta: false,
  comentario: "Mantêm razão constante.",
  tempoEstimado: 30,
  tags: ["grandezas"]
},
{
  id: "rp_198",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Escalas",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "Escala 1:200 → 15 cm representam quantos metros?",
  opcoes: [],
  correta: "30",
  comentario: "3000 cm.",
  tempoEstimado: 30,
  tags: ["escala"]
},
{
  id: "rp_199",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Comparacao",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 9,
  cognicao: "interpretacao",
  tipo: "comparacao",
  enunciado: "Qual menor?",
  opcoes: ["19:30", "3:5"],
  correta: "19:30",
  comentario: "≈0,63 vs 0,6.",
  tempoEstimado: 30,
  tags: ["comparacao"]
},
{
  id: "rp_200",
  serie: [1],
  materia: "Matemática",
  topico: "Razões e Proporções",
  subtopico: "Regra de tres simples",
  dificuldadeLabel: "dificil",
  dificuldadeNivel: 10,
  cognicao: "estrategia",
  tipo: "input",
  enunciado: "5 torneiras enchem em 8h. 2 torneiras levam quanto?",
  opcoes: [],
  correta: "20",
  comentario: "Inversa.",
  tempoEstimado: 35,
  tags: ["regra"]
}
  ]
};