export const esportesBasicos = {
  id: "educacao-fisica_esportes_basicos",
  materia: "Educacao Fisica",
  serie: [1],
  topico: "Esportes Basicos",
  metadados: {
    disciplinaId: "educacao-fisica",
    base: "ESCOLAR",
    eixo: "Educacao Fisica",
    frente: "Esportes Basicos",
    searchAliases: [
      "esportes basicos",
      "fundamentos esportivos",
      "regras basicas",
      "tecnicas fundamentais",
      "seguranca no esporte",
      "esportes coletivos",
      "esportes individuais"
    ],
    subtopicosBase: [
      "Fundamentos dos esportes",
      "Regras basicas",
      "Tecnicas fundamentais",
      "Seguranca no esporte",
      "Esportes coletivos vs individuais",
      "Habilidades motoras basicas",
      "Preparacao fisica",
      "Etica esportiva"
    ],
    habilidadesBase: [
      "identificar fundamentos dos esportes basicos",
      "compreender regras e tecnicas fundamentais",
      "aplicar principios de seguranca no esporte",
      "diferenciar esportes coletivos e individuais",
      "reconhecer importancia da etica esportiva",
      "interpretar situacoes aplicadas em esportes basicos"
    ],
    auditado: false
  },
  questoes: [
    {
      id: "eb_001",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "O que sao esportes basicos na educacao fisica?",
      opcoes: [
        "Apenas modalidades olimpicas",
        "Atividades fundamentais que ensinam habilidades motoras essenciais",
        "Exclusivamente competicoes profissionais",
        "Jogos de video e simulacoes"
      ],
      correta: "Atividades fundamentais que ensinam habilidades motoras essenciais",
      comentario: "Esportes basicos incluem corrida, salto, lancamento e outros que formam a base para praticas esportivas mais complexas.",
      tempoEstimado: 20,
      tags: ["esportes-basicos", "fundamentos"],
      habilidades: ["identificar-conceito-de-esportes-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_002",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Por que as regras sao importantes nos esportes?",
      opcoes: [
        "Para tornar o jogo mais dificil",
        "Garantir seguranca e igualdade entre os participantes",
        "Exclusivamente para punir jogadores",
        "Nao sao importantes"
      ],
      correta: "Garantir seguranca e igualdade entre os participantes",
      comentario: "As regras estabelecem limites e condicoes justas, promovendo um ambiente seguro e competitivo.",
      tempoEstimado: 25,
      tags: ["regras", "seguranca", "igualdade"],
      habilidades: ["explicar-importancia-das-regras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_003",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual e uma tecnica fundamental no atletismo?",
      opcoes: [
        "Danca contemporanea",
        "Corrida com passada correta",
        "Jogo de xadrez",
        "Pintura artistica"
      ],
      correta: "Corrida com passada correta",
      comentario: "No atletismo, tecnicas como a passada correta na corrida sao fundamentais para eficiencia e prevencao de lesoes.",
      tempoEstimado: 30,
      tags: ["tecnicas", "atletismo", "corrida"],
      habilidades: ["reconhecer-tecnicas-fundamentais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_004",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida de seguranca e essencial antes de praticar qualquer esporte?",
      opcoes: [
        "Usar equipamentos adequados",
        "Competir sem limites de tempo",
        "Ignorar dores e desconfortos",
        "Praticar sem aquecimento"
      ],
      correta: "Usar equipamentos adequados",
      comentario: "Equipamentos de protecao adequados reduzem o risco de acidentes e lesoes durante a pratica esportiva.",
      tempoEstimado: 25,
      tags: ["seguranca", "equipamentos", "prevencao"],
      habilidades: ["identificar-medidas-de-seguranca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_006",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade motora basica e a corrida?",
      opcoes: [
        "Forca",
        "Locomocao",
        "Equilibrio estatico",
        "Precisao"
      ],
      correta: "Locomocao",
      comentario: "Corrida envolve deslocamento rapido, fundamental para muitos esportes.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "locomocao"],
      habilidades: ["identificar-habilidades-basicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_007",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual componente da preparacao fisica?",
      opcoes: [
        "Alongamento",
        "Dieta rica em gordura",
        "Sedentarismo",
        "Fumar"
      ],
      correta: "Alongamento",
      comentario: "Alongamento aumenta flexibilidade, previne lesoes e melhora performance.",
      tempoEstimado: 35,
      tags: ["preparacao-fisica", "alongamento"],
      habilidades: ["compreender-componentes-preparacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_008",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual principio da etica esportiva?",
      opcoes: [
        "Trapacear para ganhar",
        "Respeito as regras",
        "Ignorar adversarios",
        "Competir sem limites"
      ],
      correta: "Respeito as regras",
      comentario: "Etica esportiva inclui fair play, respeito e integridade.",
      tempoEstimado: 40,
      tags: ["etica-esportiva", "respeito"],
      habilidades: ["interpretar-principios-eticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_009",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento basico do esporte?",
      opcoes: [
        "Competicao",
        "Habilidades motoras",
        "Equipamentos caros",
        "Publico grande"
      ],
      correta: "Habilidades motoras",
      comentario: "Habilidades como correr, saltar formam base de todos os esportes.",
      tempoEstimado: 20,
      tags: ["fundamentos", "habilidades"],
      habilidades: ["identificar-fundamentos-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_010",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra basica em jogos coletivos?",
      opcoes: [
        "Nao respeitar limites",
        "Jogar com as maos",
        "Empurrar colegas",
        "Seguir instrucoes do professor"
      ],
      correta: "Seguir instrucoes do professor",
      comentario: "Regras garantem seguranca e aprendizado, supervisionadas pelo professor.",
      tempoEstimado: 30,
      tags: ["regras", "jogos-coletivos"],
      habilidades: ["compreender-importancia-regras"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_011",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica fundamental no lancamento?",
      opcoes: [
        "Lancar com braco reto",
        "Usar impulso do corpo",
        "Lancar para tras",
        "Nao usar forca"
      ],
      correta: "Usar impulso do corpo",
      comentario: "Impulso corporal aumenta velocidade e distancia do lancamento.",
      tempoEstimado: 35,
      tags: ["tecnicas", "lancamento"],
      habilidades: ["interpretar-tecnicas-fundamentais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_012",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual medida de seguranca em corridas?",
      opcoes: [
        "Correr descalco",
        "Aquecer antes",
        "Pular obstaculos altos",
        "Competir sozinho"
      ],
      correta: "Aquecer antes",
      comentario: "Aquecimento previne lesoes musculares e prepara o corpo.",
      tempoEstimado: 40,
      tags: ["seguranca", "aquecimento"],
      habilidades: ["analisar-medidas-seguranca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_013",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo de esporte individual?",
      opcoes: [
        "Futebol",
        "Natacao",
        "Basquete",
        "Volei"
      ],
      correta: "Natacao",
      comentario: "Natacao e praticada individualmente, sem dependencia de equipe.",
      tempoEstimado: 25,
      tags: ["esportes-individuais", "natacao"],
      habilidades: ["identificar-tipos-esportes"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_014",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para saltos?",
      opcoes: [
        "Forca explosiva",
        "Resistencia longa",
        "Flexibilidade extrema",
        "Precisao fina"
      ],
      correta: "Forca explosiva",
      comentario: "Saltos requerem forca rapida para impulsionar o corpo.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "saltos"],
      habilidades: ["compreender-habilidades-saltos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_015",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio de preparacao?",
      opcoes: [
        "Correr sem parar",
        "Polichinelos",
        "Dormir",
        "Comer muito"
      ],
      correta: "Polichinelos",
      comentario: "Polichinelos aquecem musculos e aumentam frequencia cardiaca.",
      tempoEstimado: 35,
      tags: ["preparacao-fisica", "polichinelos"],
      habilidades: ["interpretar-exercicios-preparacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_016",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual comportamento anti-etico?",
      opcoes: [
        "Elogiar adversario",
        "Trapacear",
        "Respeitar juiz",
        "Jogar limpo"
      ],
      correta: "Trapacear",
      comentario: "Trapacear viola principios de integridade e fair play.",
      tempoEstimado: 40,
      tags: ["etica-esportiva", "trapaca"],
      habilidades: ["analisar-comportamentos-eticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_017",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui corrida e salto?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Atletismo",
      comentario: "Atletismo abrange corridas, saltos e lancamentos como base.",
      tempoEstimado: 20,
      tags: ["fundamentos", "atletismo"],
      habilidades: ["identificar-fundamentos-atletismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_018",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em queimada?",
      opcoes: [
        "Correr para tras",
        "Nao revidar",
        "Jogar a bola",
        "Ignorar grito"
      ],
      correta: "Nao revidar",
      comentario: "Em queimada, nao se pode revidar para evitar lesoes.",
      tempoEstimado: 30,
      tags: ["regras", "queimada"],
      habilidades: ["compreender-regras-queimada"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_019",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para chute em futebol?",
      opcoes: [
        "Chutar com a ponta",
        "Usar parte interna do pe",
        "Chutar para cima",
        "Nao usar forca"
      ],
      correta: "Usar parte interna do pe",
      comentario: "Parte interna garante acuracia e controle no chute.",
      tempoEstimado: 35,
      tags: ["tecnicas", "futebol"],
      habilidades: ["interpretar-tecnicas-chute"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_020",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes sem aquecimento?",
      opcoes: [
        "Melhor performance",
        "Lesoes musculares",
        "Maior resistencia",
        "Menos fadiga"
      ],
      correta: "Lesoes musculares",
      comentario: "Sem aquecimento, musculos frios se lesionam facilmente.",
      tempoEstimado: 40,
      tags: ["seguranca", "lesoes"],
      habilidades: ["analisar-riscos-sem-aquecimento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_021",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual esporte coletivo?",
      opcoes: [
        "Futebol",
        "Natacao",
        "Atletismo",
        "Ciclismo"
      ],
      correta: "Futebol",
      comentario: "Futebol envolve equipe competindo contra outra.",
      tempoEstimado: 25,
      tags: ["esportes-coletivos", "futebol"],
      habilidades: ["identificar-esportes-coletivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_022",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para saltos?",
      opcoes: [
        "Forca explosiva",
        "Resistencia longa",
        "Flexibilidade extrema",
        "Precisao fina"
      ],
      correta: "Forca explosiva",
      comentario: "Saltos requerem forca rapida para impulsionar.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "saltos"],
      habilidades: ["compreender-habilidades-saltos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_023",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio de alongamento?",
      opcoes: [
        "Corrida intensa",
        "Esticar bracos",
        "Pular corda",
        "Levantar peso"
      ],
      correta: "Esticar bracos",
      comentario: "Alongamento aumenta flexibilidade e previne lesoes.",
      tempoEstimado: 35,
      tags: ["preparacao-fisica", "alongamento"],
      habilidades: ["interpretar-exercicios-alongamento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_024",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual comportamento etico?",
      opcoes: [
        "Respeitar juiz",
        "Trapacear",
        "Empurrar oponente",
        "Ignorar regras"
      ],
      correta: "Respeitar juiz",
      comentario: "Respeito ao juiz garante fair play e integridade.",
      tempoEstimado: 40,
      tags: ["etica-esportiva", "respeito"],
      habilidades: ["analisar-comportamentos-eticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_025",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento basico?",
      opcoes: [
        "Habilidades motoras",
        "Equipamentos caros",
        "Publico grande",
        "Premios altos"
      ],
      correta: "Habilidades motoras",
      comentario: "Habilidades como correr formam base de esportes.",
      tempoEstimado: 20,
      tags: ["fundamentos", "habilidades"],
      habilidades: ["identificar-fundamentos-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_026",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em basquete?",
      opcoes: [
        "Usar maos",
        "Chutar bola",
        "Correr com bola",
        "Jogar fora"
      ],
      correta: "Usar maos",
      comentario: "Basquete permite driblar e passar com maos.",
      tempoEstimado: 30,
      tags: ["regras", "basquete"],
      habilidades: ["compreender-regras-basquete"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_027",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para passe em volei?",
      opcoes: [
        "Usar punhos",
        "Braços abertos",
        "Pernas",
        "Cabeca"
      ],
      correta: "Braços abertos",
      comentario: "Passe de baixo usa bracos abertos para controlar bola.",
      tempoEstimado: 35,
      tags: ["tecnicas", "volei"],
      habilidades: ["interpretar-tecnicas-passe"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_028",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes de contato?",
      opcoes: [
        "Lesoes",
        "Melhor forma",
        "Maior velocidade",
        "Menos fadiga"
      ],
      correta: "Lesoes",
      comentario: "Contato fisico pode causar contusoes e fraturas.",
      tempoEstimado: 40,
      tags: ["seguranca", "lesoes"],
      habilidades: ["analisar-riscos-contato"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_029",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual vantagem de esportes individuais?",
      opcoes: [
        "Trabalho em equipe",
        "Autonomia",
        "Dependencia",
        "Cooperacao"
      ],
      correta: "Autonomia",
      comentario: "Individuais permitem foco pessoal e independencia.",
      tempoEstimado: 30,
      tags: ["esportes-individuais", "autonomia"],
      habilidades: ["compreender-vantagens-individuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_030",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para lancamentos?",
      opcoes: [
        "Precisao",
        "Velocidade maxima",
        "Resistencia longa",
        "Equilibrio estatico"
      ],
      correta: "Precisao",
      comentario: "Lancamentos requerem mira e controle de trajetoria.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "lancamentos"],
      habilidades: ["interpretar-habilidades-lancamentos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_031",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual componente de preparacao?",
      opcoes: [
        "Treino de forca",
        "Dormir durante treino",
        "Comer junk food",
        "Ficar doente"
      ],
      correta: "Treino de forca",
      comentario: "Forca muscular e essencial para performance esportiva.",
      tempoEstimado: 40,
      tags: ["preparacao-fisica", "forca"],
      habilidades: ["analisar-componentes-forca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_032",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual principio etico?",
      opcoes: [
        "Fair play",
        "Trapaca",
        "Violencia",
        "Desrespeito"
      ],
      correta: "Fair play",
      comentario: "Fair play significa jogar limpo e respeitar regras.",
      tempoEstimado: 25,
      tags: ["etica-esportiva", "fair-play"],
      habilidades: ["identificar-principios-eticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_033",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui corrida?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Atletismo",
      comentario: "Atletismo abrange corridas, saltos e lancamentos.",
      tempoEstimado: 30,
      tags: ["fundamentos", "atletismo"],
      habilidades: ["compreender-fundamentos-atletismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_034",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em futebol?",
      opcoes: [
        "Usar maos",
        "Chutar bola",
        "Correr com bola nas maos",
        "Jogar fora da quadra"
      ],
      correta: "Chutar bola",
      comentario: "Futebol permite chutes, mas nao uso de maos exceto goleiro.",
      tempoEstimado: 35,
      tags: ["regras", "futebol"],
      habilidades: ["interpretar-regras-futebol"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_035",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para saque em volei?",
      opcoes: [
        "Saque por cima",
        "Usar pe",
        "Saque com mao fechada",
        "Jogar bola"
      ],
      correta: "Saque por cima",
      comentario: "Saque por cima arremessa bola sobre rede com braco estendido.",
      tempoEstimado: 40,
      tags: ["tecnicas", "saque"],
      habilidades: ["analisar-tecnicas-saque"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_036",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida de seguranca?",
      opcoes: [
        "Usar equipamentos",
        "Correr descalco",
        "Pular alto sem rede",
        "Empurrar colegas"
      ],
      correta: "Usar equipamentos",
      comentario: "Equipamentos como capacetes previnem lesoes.",
      tempoEstimado: 20,
      tags: ["seguranca", "equipamentos"],
      habilidades: ["identificar-medidas-seguranca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_037",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual esporte individual?",
      opcoes: [
        "Basquete",
        "Tenis",
        "Futebol",
        "Volei"
      ],
      correta: "Tenis",
      comentario: "Tenis e praticado um contra um ou contra parede.",
      tempoEstimado: 30,
      tags: ["esportes-individuais", "tenis"],
      habilidades: ["compreender-esportes-individuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_038",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para ginastica?",
      opcoes: [
        "Flexibilidade",
        "Velocidade",
        "Forca bruta",
        "Resistencia longa"
      ],
      correta: "Flexibilidade",
      comentario: "Ginastica requer movimentos flexiveis e controle.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "flexibilidade"],
      habilidades: ["interpretar-habilidades-ginastica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_039",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio cardiovascular?",
      opcoes: [
        "Caminhada",
        "Levantar peso",
        "Alongamento",
        "Abdominais"
      ],
      correta: "Caminhada",
      comentario: "Caminhada acelera coracao e melhora circulacao.",
      tempoEstimado: 30,
      tags: ["preparacao-fisica", "cardiovascular"],
      habilidades: ["compreender-exercicios-cardiovasculares"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_041",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui ginastica?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Ginastica",
      comentario: "Ginastica desenvolve flexibilidade e controle corporal.",
      tempoEstimado: 30,
      tags: ["fundamentos", "ginastica"],
      habilidades: ["compreender-fundamentos-ginastica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_042",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em handebol?",
      opcoes: [
        "Passar com pe",
        "Passar com mao",
        "Correr com bola",
        "Chutar alto"
      ],
      correta: "Passar com mao",
      comentario: "Handebol permite passes e arremessos com maos.",
      tempoEstimado: 35,
      tags: ["regras", "handebol"],
      habilidades: ["interpretar-regras-handebol"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_043",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para defesa em basquete?",
      opcoes: [
        "Bloquear",
        "Marcar",
        "Passar",
        "Arremessar"
      ],
      correta: "Marcar",
      comentario: "Marcacao impede o oponente de avancar ou arremessar.",
      tempoEstimado: 40,
      tags: ["tecnicas", "defesa"],
      habilidades: ["analisar-tecnicas-defesa"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_044",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida para evitar torcao?",
      opcoes: [
        "Aquecer",
        "Correr rapido",
        "Pular alto",
        "Empurrar"
      ],
      correta: "Aquecer",
      comentario: "Aquecimento prepara articulacoes e previne torcoes.",
      tempoEstimado: 20,
      tags: ["seguranca", "torcao"],
      habilidades: ["identificar-medidas-torcao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_045",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual vantagem coletiva?",
      opcoes: [
        "Trabalho em equipe",
        "Autonomia total",
        "Dependencia minima",
        "Isolamento"
      ],
      correta: "Trabalho em equipe",
      comentario: "Coletivos ensinam cooperacao e estrategia conjunta.",
      tempoEstimado: 30,
      tags: ["coletivos", "trabalho-equipe"],
      habilidades: ["compreender-vantagens-coletivas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_046",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para ciclismo?",
      opcoes: [
        "Equilibrio",
        "Forca",
        "Velocidade",
        "Agilidade"
      ],
      correta: "Equilibrio",
      comentario: "Equilibrio e essencial para manter bicicleta em movimento.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "equilibrio"],
      habilidades: ["interpretar-habilidades-ciclismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_047",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para resistencia muscular?",
      opcoes: [
        "Corrida longa",
        "Flexoes",
        "Alongamento",
        "Danca"
      ],
      correta: "Flexoes",
      comentario: "Flexoes fortalecem musculos superiores com repeticoes.",
      tempoEstimado: 40,
      tags: ["preparacao-fisica", "resistencia"],
      habilidades: ["analisar-exercicios-resistencia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_048",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual valor etico?",
      opcoes: [
        "Honestidade",
        "Trapaca",
        "Violencia",
        "Desrespeito"
      ],
      correta: "Honestidade",
      comentario: "Honestidade garante integridade nas competicoes.",
      tempoEstimado: 25,
      tags: ["etica-esportiva", "honestidade"],
      habilidades: ["identificar-valores-eticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_049",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui natacao?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Natacao",
      comentario: "Natacao desenvolve resistencia e tecnica na agua.",
      tempoEstimado: 30,
      tags: ["fundamentos", "natacao"],
      habilidades: ["compreender-fundamentos-natacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_050",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em volei?",
      opcoes: [
        "Toque com pe",
        "Toque com mao",
        "Correr com bola",
        "Chutar"
      ],
      correta: "Toque com mao",
      comentario: "Volei permite toques com maos para rebater bola.",
      tempoEstimado: 35,
      tags: ["regras", "volei"],
      habilidades: ["interpretar-regras-volei"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_051",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para arremesso em handebol?",
      opcoes: [
        "Arremessar baixo",
        "Arremessar alto",
        "Passar com pe",
        "Correr"
      ],
      correta: "Arremessar alto",
      comentario: "Arremesso alto visa gol sobre defesa.",
      tempoEstimado: 40,
      tags: ["tecnicas", "arremesso"],
      habilidades: ["analisar-tecnicas-arremesso"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_052",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes de equipe?",
      opcoes: [
        "Lesoes por contato",
        "Melhor forma",
        "Maior velocidade",
        "Menos fadiga"
      ],
      correta: "Lesoes por contato",
      comentario: "Contato fisico pode causar contusoes em equipes.",
      tempoEstimado: 30,
      tags: ["seguranca", "contato"],
      habilidades: ["compreender-riscos-equipe"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_053",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual desvantagem coletiva?",
      opcoes: [
        "Cooperacao",
        "Dependencia de outros",
        "Autonomia",
        "Isolamento"
      ],
      correta: "Dependencia de outros",
      comentario: "Coletivos dependem de desempenho da equipe.",
      tempoEstimado: 35,
      tags: ["coletivos", "dependencia"],
      habilidades: ["interpretar-desvantagens-coletivas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_054",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para patinacao?",
      opcoes: [
        "Equilibrio dinamico",
        "Forca estatica",
        "Velocidade linear",
        "Agilidade curta"
      ],
      correta: "Equilibrio dinamico",
      comentario: "Patinacao requer equilibrio em movimento continuo.",
      tempoEstimado: 40,
      tags: ["habilidades-motoras", "patinacao"],
      habilidades: ["analisar-habilidades-patinacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_055",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio basico?",
      opcoes: [
        "Abdominais",
        "Danca",
        "Caminhada",
        "Natacao"
      ],
      correta: "Abdominais",
      comentario: "Abdominais fortalecem core essencial para esportes.",
      tempoEstimado: 20,
      tags: ["preparacao-fisica", "abdominais"],
      habilidades: ["identificar-exercicios-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_056",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual comportamento etico em derrota?",
      opcoes: [
        "Reclamar",
        "Parabenizar vencedor",
        "Ignorar",
        "Culpar equipe"
      ],
      correta: "Parabenizar vencedor",
      comentario: "Parabenizar mostra respeito e esportes.",
      tempoEstimado: 30,
      tags: ["etica-esportiva", "derrota"],
      habilidades: ["compreender-comportamentos-derrota"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_057",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui ciclismo?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Ciclismo",
      comentario: "Ciclismo desenvolve resistencia e velocidade em bicicleta.",
      tempoEstimado: 35,
      tags: ["fundamentos", "ciclismo"],
      habilidades: ["interpretar-fundamentos-ciclismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_058",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em queimada?",
      opcoes: [
        "Revide",
        "Nao revidar",
        "Empurrar",
        "Correr para tras"
      ],
      correta: "Nao revidar",
      comentario: "Nao revidar previne lesoes em queimada.",
      tempoEstimado: 40,
      tags: ["regras", "queimada"],
      habilidades: ["analisar-regras-queimada"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_059",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica basica em corrida?",
      opcoes: [
        "Passo ritmado",
        "Salto alto",
        "Lancamento",
        "Nado"
      ],
      correta: "Passo ritmado",
      comentario: "Passo ritmado otimiza velocidade e eficiencia.",
      tempoEstimado: 25,
      tags: ["tecnicas", "corrida"],
      habilidades: ["identificar-tecnicas-corrida"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_060",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida para hidratação?",
      opcoes: [
        "Beber agua",
        "Correr sem parar",
        "Comer muito",
        "Dormir"
      ],
      correta: "Beber agua",
      comentario: "Hidratação previne desidratação durante atividade.",
      tempoEstimado: 30,
      tags: ["seguranca", "hidratacao"],
      habilidades: ["compreender-medidas-hidratacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_061",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual vantagem individual?",
      opcoes: [
        "Autonomia",
        "Dependencia",
        "Cooperacao",
        "Equipe"
      ],
      correta: "Autonomia",
      comentario: "Individuais permitem controle total sobre performance.",
      tempoEstimado: 35,
      tags: ["individuais", "autonomia"],
      habilidades: ["interpretar-vantagens-individuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_062",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para corrida de longa distancia?",
      opcoes: [
        "Resistencia cardiovascular",
        "Forca explosiva",
        "Velocidade maxima",
        "Agilidade curta"
      ],
      correta: "Resistencia cardiovascular",
      comentario: "Resistencia permite manter ritmo por longos periodos.",
      tempoEstimado: 40,
      tags: ["habilidades-motoras", "corrida-longa"],
      habilidades: ["analisar-habilidades-corrida-longa"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_063",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para alongamento?",
      opcoes: [
        "Esticar musculos",
        "Correr rapido",
        "Pular alto",
        "Empurrar"
      ],
      correta: "Esticar musculos",
      comentario: "Alongamento aumenta flexibilidade e previne lesoes.",
      tempoEstimado: 20,
      tags: ["preparacao-fisica", "alongamento"],
      habilidades: ["identificar-exercicios-alongamento"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_064",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual comportamento etico em vitoria?",
      opcoes: [
        "Humildade",
        "Arrogancia",
        "Desrespeito",
        "Ignorar"
      ],
      correta: "Humildade",
      comentario: "Humildade mostra respeito e maturidade apos vitoria.",
      tempoEstimado: 30,
      tags: ["etica-esportiva", "humildade"],
      habilidades: ["compreender-comportamentos-vitoria"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_065",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui atletismo?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Natacao",
        "Ciclismo"
      ],
      correta: "Atletismo",
      comentario: "Atletismo inclui corridas, saltos e lancamentos.",
      tempoEstimado: 35,
      tags: ["fundamentos", "atletismo"],
      habilidades: ["interpretar-fundamentos-atletismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_066",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em futsal?",
      opcoes: [
        "Toque com pe",
        "Toque com mao",
        "Correr com bola",
        "Chutar alto"
      ],
      correta: "Toque com pe",
      comentario: "Futsal permite toques com pe para controlar bola.",
      tempoEstimado: 40,
      tags: ["regras", "futsal"],
      habilidades: ["analisar-regras-futsal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_067",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica basica em salto?",
      opcoes: [
        "Impulso",
        "Nado",
        "Lancamento",
        "Drible"
      ],
      correta: "Impulso",
      comentario: "Impulso gera forca para elevar corpo no salto.",
      tempoEstimado: 25,
      tags: ["tecnicas", "salto"],
      habilidades: ["identificar-tecnicas-salto"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_068",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes aquáticos?",
      opcoes: [
        "Afogamento",
        "Queimadura",
        "Fratura",
        "Torcao"
      ],
      correta: "Afogamento",
      comentario: "Afogamento e risco principal em atividades na agua.",
      tempoEstimado: 30,
      tags: ["seguranca", "aquaticos"],
      habilidades: ["compreender-riscos-aquaticos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_069",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual desvantagem coletiva?",
      opcoes: [
        "Pressao de grupo",
        "Autonomia total",
        "Isolamento",
        "Independencia"
      ],
      correta: "Pressao de grupo",
      comentario: "Coletivos podem causar pressao para desempenho da equipe.",
      tempoEstimado: 35,
      tags: ["coletivos", "pressao"],
      habilidades: ["interpretar-desvantagens-pressao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_070",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para ginastica artistica?",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para ginastica artistica?",
      opcoes: [
        "Equilibrio e flexibilidade",
        "Forca bruta",
        "Velocidade linear",
        "Agilidade curta"
      ],
      correta: "Equilibrio e flexibilidade",
      comentario: "Ginastica requer equilibrio preciso e flexibilidade extrema.",
      tempoEstimado: 40,
      tags: ["habilidades-motoras", "ginastica-artistica"],
      habilidades: ["analisar-habilidades-ginastica"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_071",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para resistencia?",
      opcoes: [
        "Corrida continua",
        "Salto unico",
        "Lancamento",
        "Drible"
      ],
      correta: "Corrida continua",
      comentario: "Corrida continua desenvolve resistencia cardiovascular.",
      tempoEstimado: 30,
      tags: ["preparacao-fisica", "resistencia"],
      habilidades: ["compreender-exercicios-resistencia"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_072",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual valor etico em derrota?",
      opcoes: [
        "Aceitacao",
        "Revolta",
        "Culpa",
        "Ignorancia"
      ],
      correta: "Aceitacao",
      comentario: "Aceitar derrota graciosamente mostra maturidade.",
      tempoEstimado: 35,
      tags: ["etica-esportiva", "aceitacao"],
      habilidades: ["interpretar-valores-derrota"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_073",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui artes marciais?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Artes marciais",
        "Natacao"
      ],
      correta: "Artes marciais",
      comentario: "Artes marciais incluem judo, karatê, com foco em tecnica e disciplina.",
      tempoEstimado: 40,
      tags: ["fundamentos", "artes-marciais"],
      habilidades: ["analisar-fundamentos-artes-marciais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_074",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra basica em todos os esportes?",
      opcoes: [
        "Respeitar regras",
        "Trapacear",
        "Ignorar",
        "Competir deslealmente"
      ],
      correta: "Respeitar regras",
      comentario: "Respeito as regras garante jogo justo e seguro.",
      tempoEstimado: 20,
      tags: ["regras", "respeito"],
      habilidades: ["identificar-regras-basicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_075",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para defesa em volei?",
      opcoes: [
        "Bloquear",
        "Atacar",
        "Servir",
        "Receber"
      ],
      correta: "Bloquear",
      comentario: "Bloqueio impede ataque do oponente na rede.",
      tempoEstimado: 30,
      tags: ["tecnicas", "defesa-volei"],
      habilidades: ["compreender-tecnicas-defesa-volei"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_076",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida para evitar contusoes?",
      opcoes: [
        "Usar equipamentos",
        "Correr sem protecao",
        "Pular alto sem preparo",
        "Empurrar forte"
      ],
      correta: "Usar equipamentos",
      comentario: "Equipamentos protegem contra impactos e contusoes.",
      tempoEstimado: 35,
      tags: ["seguranca", "contusoes"],
      habilidades: ["interpretar-medidas-contusoes"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_077",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto psicologico em coletivos?",
      opcoes: [
        "Desenvolvimento de lideranca",
        "Isolamento emocional",
        "Dependencia excessiva",
        "Autonomia reduzida"
      ],
      correta: "Desenvolvimento de lideranca",
      comentario: "Coletivos ensinam lideranca e responsabilidade compartilhada.",
      tempoEstimado: 40,
      tags: ["coletivos", "lideranca"],
      habilidades: ["analisar-impactos-psicologicos-coletivos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_078",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para natação?",
      opcoes: [
        "Coordenacao respiração-movimento",
        "Forca terrestre",
        "Velocidade em terra",
        "Agilidade seca"
      ],
      correta: "Coordenacao respiração-movimento",
      comentario: "Natacao requer sincronizar respiracao com braçadas.",
      tempoEstimado: 25,
      tags: ["habilidades-motoras", "natacao"],
      habilidades: ["identificar-habilidades-natacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_079",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para velocidade?",
      opcoes: [
        "Sprints curtos",
        "Corrida longa",
        "Alongamento",
        "Danca"
      ],
      correta: "Sprints curtos",
      comentario: "Sprints desenvolvem velocidade maxima em curtas distancias.",
      tempoEstimado: 30,
      tags: ["preparacao-fisica", "velocidade"],
      habilidades: ["compreender-exercicios-velocidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_081",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui dança?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Danca",
        "Natacao"
      ],
      correta: "Danca",
      comentario: "Danca desenvolve ritmo e expressao corporal.",
      tempoEstimado: 20,
      tags: ["fundamentos", "danca"],
      habilidades: ["identificar-fundamentos-danca"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_082",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em basquete?",
      opcoes: [
        "Passar com mao",
        "Passar com pe",
        "Correr com bola",
        "Chutar"
      ],
      correta: "Passar com mao",
      comentario: "Basquete permite passes e drible com maos.",
      tempoEstimado: 30,
      tags: ["regras", "basquete"],
      habilidades: ["compreender-regras-basquete"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_083",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para saque em volei?",
      opcoes: [
        "Saque por cima",
        "Bloquear",
        "Receber",
        "Atacar"
      ],
      correta: "Saque por cima",
      comentario: "Saque por cima inicia jogo com bola sobre rede.",
      tempoEstimado: 35,
      tags: ["tecnicas", "saque-volei"],
      habilidades: ["interpretar-tecnicas-saque-volei"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_084",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes de contato?",
      opcoes: [
        "Lesoes articulares",
        "Queimadura solar",
        "Desidratação",
        "Fadiga muscular"
      ],
      correta: "Lesoes articulares",
      comentario: "Contato fisico pode causar torcoes e fraturas.",
      tempoEstimado: 40,
      tags: ["seguranca", "contato"],
      habilidades: ["analisar-riscos-contato"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_085",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exemplo individual?",
      opcoes: [
        "Corrida",
        "Futebol",
        "Basquete",
        "Volei"
      ],
      correta: "Corrida",
      comentario: "Corrida e praticada individualmente contra tempo.",
      tempoEstimado: 25,
      tags: ["individuais", "corrida"],
      habilidades: ["identificar-exemplos-individuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_086",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para ciclismo?",
      opcoes: [
        "Equilibrio dinamico",
        "Forca estatica",
        "Velocidade curta",
        "Agilidade parada"
      ],
      correta: "Equilibrio dinamico",
      comentario: "Ciclismo requer equilibrio em movimento continuo.",
      tempoEstimado: 30,
      tags: ["habilidades-motoras", "ciclismo"],
      habilidades: ["compreender-habilidades-ciclismo"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_087",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para flexibilidade?",
      opcoes: [
        "Alongamento dinamico",
        "Corrida intensa",
        "Levantamento pesado",
        "Salto alto"
      ],
      correta: "Alongamento dinamico",
      comentario: "Alongamento dinamico aumenta amplitude de movimento.",
      tempoEstimado: 35,
      tags: ["preparacao-fisica", "flexibilidade"],
      habilidades: ["interpretar-exercicios-flexibilidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_088",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 8,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual impacto da doping?",
      opcoes: [
        "Vantagem injusta",
        "Saude prejudicada",
        "Ambas",
        "Nenhuma"
      ],
      correta: "Ambas",
      comentario: "Doping da vantagem injusta e prejudica saude.",
      tempoEstimado: 40,
      tags: ["etica-esportiva", "doping"],
      habilidades: ["analisar-impactos-doping"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_089",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui patinacao?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Patinacao",
        "Natacao"
      ],
      correta: "Patinacao",
      comentario: "Patinacao desenvolve equilibrio e velocidade sobre rodas.",
      tempoEstimado: 30,
      tags: ["fundamentos", "patinacao"],
      habilidades: ["compreender-fundamentos-patinacao"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_090",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em queimada?",
      opcoes: [
        "Nao revidar",
        "Empurrar",
        "Correr para tras",
        "Chutar"
      ],
      correta: "Nao revidar",
      comentario: "Nao revidar previne lesoes em queimada.",
      tempoEstimado: 35,
      tags: ["regras", "queimada"],
      habilidades: ["interpretar-regras-queimada"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_091",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para defesa em handebol?",
      opcoes: [
        "Marcacao individual",
        "Atacar",
        "Servir",
        "Receber"
      ],
      correta: "Marcacao individual",
      comentario: "Marcacao impede oponente de avancar ou arremessar.",
      tempoEstimado: 40,
      tags: ["tecnicas", "defesa-handebol"],
      habilidades: ["analisar-tecnicas-defesa-handebol"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_092",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 1,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual medida basica de seguranca?",
      opcoes: [
        "Aquecer",
        "Correr rapido",
        "Pular sem preparo",
        "Empurrar"
      ],
      correta: "Aquecer",
      comentario: "Aquecimento prepara corpo e previne lesoes.",
      tempoEstimado: 20,
      tags: ["seguranca", "aquecimento"],
      habilidades: ["identificar-medidas-basicas"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_093",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Esportes coletivos vs individuais",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual vantagem coletiva?",
      opcoes: [
        "Solidariedade",
        "Autonomia total",
        "Isolamento",
        "Independencia"
      ],
      correta: "Solidariedade",
      comentario: "Coletivos promovem solidariedade e apoio mutuo.",
      tempoEstimado: 30,
      tags: ["coletivos", "solidariedade"],
      habilidades: ["compreender-vantagens-solidariedade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_094",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Habilidades motoras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual habilidade para artes marciais?",
      opcoes: [
        "Precisao nos golpes",
        "Forca bruta",
        "Velocidade linear",
        "Agilidade curta"
      ],
      correta: "Precisao nos golpes",
      comentario: "Artes marciais enfatizam precisao tecnica nos movimentos.",
      tempoEstimado: 35,
      tags: ["habilidades-motoras", "artes-marciais"],
      habilidades: ["interpretar-habilidades-artes-marciais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_095",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Preparacao fisica",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual exercicio para agilidade?",
      opcoes: [
        "Cone drills",
        "Corrida longa",
        "Levantamento estatico",
        "Alongamento passivo"
      ],
      correta: "Cone drills",
      comentario: "Cone drills melhoram mudancas rapidas de direcao.",
      tempoEstimado: 40,
      tags: ["preparacao-fisica", "agilidade"],
      habilidades: ["analisar-exercicios-agilidade"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_096",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Etica esportiva",
      dificuldadeLabel: "facil",
      dificuldadeNivel: 2,
      cognicao: "identificacao",
      tipo: "multipla_escolha",
      enunciado: "Qual valor etico basico?",
      opcoes: [
        "Respeito",
        "Trapaca",
        "Violencia",
        "Desonestidade"
      ],
      correta: "Respeito",
      comentario: "Respeito aos oponentes e regras e fundamental.",
      tempoEstimado: 25,
      tags: ["etica-esportiva", "respeito"],
      habilidades: ["identificar-valores-basicos"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_097",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Fundamentos dos esportes",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual fundamento inclui capoeira?",
      opcoes: [
        "Atletismo",
        "Ginastica",
        "Capoeira",
        "Natacao"
      ],
      correta: "Capoeira",
      comentario: "Capoeira combina movimento, musica e defesa pessoal.",
      tempoEstimado: 30,
      tags: ["fundamentos", "capoeira"],
      habilidades: ["compreender-fundamentos-capoeira"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_098",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Regras basicas",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 4,
      cognicao: "interpretacao",
      tipo: "multipla_escolha",
      enunciado: "Qual regra em futsal?",
      opcoes: [
        "Toque com pe",
        "Toque com mao",
        "Correr com bola",
        "Chutar alto"
      ],
      correta: "Toque com pe",
      comentario: "Futsal permite toques com pe para controle da bola.",
      tempoEstimado: 35,
      tags: ["regras", "futsal"],
      habilidades: ["interpretar-regras-futsal"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_099",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Tecnicas fundamentais",
      dificuldadeLabel: "dificil",
      dificuldadeNivel: 5,
      cognicao: "analise",
      tipo: "multipla_escolha",
      enunciado: "Qual tecnica para ataque em volei?",
      opcoes: [
        "Spike",
        "Bloquear",
        "Receber",
        "Servir"
      ],
      correta: "Spike",
      comentario: "Spike e ataque forte para marcar ponto.",
      tempoEstimado: 40,
      tags: ["tecnicas", "ataque-volei"],
      habilidades: ["analisar-tecnicas-ataque-volei"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    },
    {
      id: "eb_100",
      serie: [1],
      materia: "Educacao Fisica",
      topico: "Esportes Basicos",
      subtopico: "Seguranca no esporte",
      dificuldadeLabel: "medio",
      dificuldadeNivel: 3,
      cognicao: "compreensao",
      tipo: "multipla_escolha",
      enunciado: "Qual risco em esportes individuais?",
      opcoes: [
        "Fadiga extrema",
        "Lesoes por contato",
        "Pressao de grupo",
        "Dependencia"
      ],
      correta: "Fadiga extrema",
      comentario: "Individuais podem causar fadiga por esforco isolado.",
      tempoEstimado: 30,
      tags: ["seguranca", "individuais"],
      habilidades: ["compreender-riscos-individuais"],
      collections: ["questions"],
      sourceType: "original",
      sourceExam: "",
      sourceYear: null,
      competencies: [],
      status: "revisada"
    }
  ]
};
